In [4]:
!pip install polars

Defaulting to user installation because normal site-packages is not writeable
Collecting polars
  Downloading polars-1.35.2-py3-none-any.whl.metadata (10 kB)
Collecting polars-runtime-32==1.35.2 (from polars)
  Downloading polars_runtime_32-1.35.2-cp39-abi3-win_amd64.whl.metadata (1.5 kB)
Downloading polars-1.35.2-py3-none-any.whl (783 kB)
   ---------------------------------------- 0.0/783.6 kB ? eta -:--:--
   ---------------------------------------- 783.6/783.6 kB 9.1 MB/s  0:00:00
Downloading polars_runtime_32-1.35.2-cp39-abi3-win_amd64.whl (41.3 MB)
   ---------------------------------------- 0.0/41.3 MB ? eta -:--:--
   ---- ----------------------------------- 4.7/41.3 MB 23.1 MB/s eta 0:00:02
   -------- ------------------------------- 8.7/41.3 MB 23.3 MB/s eta 0:00:02
   -------- ------------------------------- 8.7/41.3 MB 23.3 MB/s eta 0:00:02
   --------- ------------------------------ 9.7/41.3 MB 11.7 MB/s eta 0:00:03
   ---------- ----------------------------- 11.3/41.3 MB 10.8 MB/s eta 0:00:03
   -------------- ------------------------- 15.2/41.3 MB 12.2 MB/s eta 0:00:03
   ------------------- -------------------- 19.9/41.3 MB 13.5 MB/s eta 0:00:02
   --------------------- ------------------ 22.3/41.3 MB 13.2 MB/s eta 0:00:02
   ------------------------ --------------- 25.7/41.3 MB 13.6 MB/s eta 0:00:02
   ---------------------------- ----------- 29.1/41.3 MB 13.9 MB/s eta 0:00:01
   ------------------------------- -------- 32.5/41.3 MB 14.1 MB/s eta 0:00:01
   ---------------------------------- ----- 35.7/41.3 MB 14.2 MB/s eta 0:00:01
   ------------------------------------- -- 38.8/41.3 MB 14.3 MB/s eta 0:00:01
   ---------------------------------------  41.2/41.3 MB 14.2 MB/s eta 0:00:01
   ---------------------------------------- 41.3/41.3 MB 13.7 MB/s  0:00:02
Installing collected packages: polars-runtime-32, polars

   ---------------------------------------- 0/2 [polars-runtime-32]
   ---------------------------------------- 0/2 [polars-runtime-32]
   ---------------------------------------- 0/2 [polars-runtime-32]
   ---------------------------------------- 0/2 [polars-runtime-32]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   ---------------------------------------- 2/2 [polars]

Successfully installed polars-1.35.2 polars-runtime-32-1.35.2

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\jasmi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [94]:
!pip install seaborn

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 25.2 -> 25.3

Collecting seaborn

[notice] To update, run: C:\Users\jasmi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (2.3.5)
Requirement already satisfied: pandas>=1.2 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

In [74]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.3.5-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.0 MB 2.4 MB/s eta 0:00:05
   ---- ----------------------------------- 1.3/11.0 MB 2.1 MB/s eta 0:00:05
   ------ --------------------------------- 1.8/11.0 MB 2.3 MB/s eta 0:00:05
   -------- ------------------------------- 2.4/11.0 MB 2.2 MB/s eta 0:00:04
   ---------- ----------------------------- 2.9/11.0 MB 2.4 MB/s eta 0:00:04
   ------------- -------------------------- 3.7/11.0 MB 2.5 MB/s eta 0:00:03
   --------------- ------------------------ 4.2/11.0 MB 2.6 MB/s eta 0:00:03
   ----------------- ---------------------- 4.7/11.0 MB 2.7 MB/s eta 0:00:03
   ------------------- -------------------- 5.2/11.0 MB 2.6 MB/s eta 0:00:03
   -------------------- ------------------- 5.8/11.0 MB 2.6 MB/s eta 0:00:03
   ----------------------- ---------------- 6.6/11.0 MB 2.6 MB/s eta 0:00:02
   ------------------------- -------------- 7.1/11.0 MB 2.6 MB/s eta 0:00:02
   ---------------------------- ----------- 7.9/11.0 MB 2.7 MB/s eta 0:00:02
   ------------------------------- -------- 8.7/11.0 MB 2.7 MB/s eta 0:00:01
   --------------------------------- ------ 9.2/11.0 MB 2.8 MB/s eta 0:00:01
   ----------------------------------- ---- 9.7/11.0 MB 2.8 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/11.0 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 2.7 MB/s  0:00:04
Downloading numpy-2.3.5-cp313-cp313-win_amd64.whl (12.8 MB)
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.8 MB 2.6 MB/s eta 0:00:05
   ---- ----------------------------------- 1.3/12.8 MB 2.4 MB/s eta 0:00:05
   ----- ---------------------------------- 1.8/12.8 MB 2.5 MB/s eta 0:00:05
   -------- ------------------------------- 2.6/12.8 MB 2.5 MB/s eta 0:00:05
   --------- ------------------------------ 3.1/12.8 MB 2.6 MB/s eta 0:00:04
   ----------- ---------------------------- 3.7/12.8 MB 2.6 MB/s eta 0:00:04
   ------------- -------------------------- 4.2/12.8 MB 2.6 MB/s eta 0:00:04
   --------------- ------------------------ 5.0/12.8 MB 2.7 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.8 MB 2.7 MB/s eta 0:00:03
   ------------------- -------------------- 6.3/12.8 MB 2.8 MB/s eta 0:00:03
   ---------------------- ----------------- 7.1/12.8 MB 2.8 MB/s eta 0:00:03
   ------------------------ --------------- 7.9/12.8 MB 2.9 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.8 MB 3.0 MB/s eta 0:00:02
   ------------------------------ --------- 9.7/12.8 MB 3.1 MB/s eta 0:00:01
   -------------------------------- ------- 10.5/12.8 MB 3.2 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.8 MB 3.2 MB/s eta 0:00:01
   ------------------------------------- -- 12.1/12.8 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 3.2 MB/s  0:00:03
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Installing collected packages: pytz, numpy, pandas

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\jasmi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [88]:
!pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 25.2 -> 25.3

Collecting matplotlib

[notice] To update, run: C:\Users\jasmi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

  Downloading matplotlib-3.10.7-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.61.0-cp313-cp313-win_amd64.whl.metadata (115 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.9-cp313-cp313-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.0.0-cp313-cp313-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.2.5-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.7-cp313-cp313-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------- ----------------------------- 2.1/8.1 MB 10.8 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.1 MB 14.5 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 13.6 MB/s  0:00:00
Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.61.0-cp313-cp313-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 24.3 MB/s  0:00:00
Downloading kiwisolver-1.4.9-cp313-cp313-win_amd64.whl (73 kB)
Downloading pillow-12.0.0-cp313-cp313-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   -------------------- ------------------- 3.7/7.0 MB 17.0 MB/s eta 0:00:01
   ---------------------------------------- 7.0/7.0 MB 20.2 MB/s  0:00:00
Downloading pyparsing-3.2.5-py3-none-any.whl (113 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------------- 7/7 [matplotlib]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.61.0 kiwisolver-1.4.9 matplotlib-3.10.7 pillow-12.0.0 pyparsing-3.2.5

In [10]:
pip install openpyxl xlsx2csv fastexcel

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting xlsx2csv
  Downloading xlsx2csv-0.8.4-py3-none-any.whl.metadata (5.7 kB)
Collecting fastexcel
  Downloading fastexcel-0.18.0-cp310-abi3-win_amd64.whl.metadata (7.4 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading xlsx2csv-0.8.4-py3-none-any.whl (15 kB)
Downloading fastexcel-0.18.0-cp310-abi3-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.9 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.9 MB 1.3 MB/s eta 0:00:02
   -------------- ------------------------- 1.0/2.9 MB 1.5 MB/s eta 0:00:02
   ------------------ --------------------- 1.3/2.9 MB 1.5 MB/s eta 0:00:02
   --------------------- ------------------ 1.6/2.9 MB 1.5 MB/s eta 0:00:01
   ----------------------------- ---------- 2.1/2.9 MB 1.6 MB/s eta 0:00:01
   ------------------------------------ --- 2.6/2.9 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 1.7 MB/s  0:00:01
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: xlsx2csv, fastexcel, et-xmlfile, openpyxl

   ---------------------------------------- 0/4 [xlsx2csv]
   ---------- ----------------------------- 1/4 [fastexcel]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ---------------------------------------- 4/4 [openpyxl]

Successfully installed et-xmlfile-2.0.0 fastexcel-0.18.0 openpyxl-3.1.5 xlsx2csv-0.8.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\jasmi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [71]:
!pip install plotly

Defaulting to user installation because normal site-packages is not writeable
Collecting plotly
  Downloading plotly-6.5.0-py3-none-any.whl.metadata (8.5 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Downloading narwhals-2.13.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: packaging in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from plotly) (25.0)
Downloading plotly-6.5.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------- ----------------------------- 2.6/9.9 MB 21.7 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 31.2 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 28.5 MB/s  0:00:00
Downloading narwhals-2.13.0-py3-none-any.whl (426 kB)
Installing collected packages: narwhals, plotly

   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   ---------------------------------------- 2/2 [plotly]

Successfully installed narwhals-2.13.0 plotly-6.5.0

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\jasmi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [1]:
import polars as pl
import plotly.io as pio
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from typing import List, Dict, Set

In [2]:
pio.renderers.default = "notebook"

In [3]:
df = pl.read_parquet('all_clean_ready_to_combine.parquet')

In [4]:
df.describe()

shape: (9, 45)
┌────────────┬──────────┬───────────────┬────────────┬───┬───────────────┬───────────────┬─────────────┬───────────────┐
│ statistic  ┆ Height_M ┆ name          ┆ Height_Flr ┆ … ┆ MC_subtype    ┆ MC_subtype_to ┆ year_built  ┆ seismic_build │
│ ---        ┆ ---      ┆ ---           ┆ ---        ┆   ┆ ---           ┆ _specific     ┆ ---         ┆ _quality      │
│ str        ┆ f64      ┆ str           ┆ f64        ┆   ┆ str           ┆ ---           ┆ f64         ┆ ---           │
│            ┆          ┆               ┆            ┆   ┆               ┆ str           ┆             ┆ str           │
╞════════════╪══════════╪═══════════════╪════════════╪═══╪═══════════════╪═══════════════╪═════════════╪═══════════════╡
│ count      ┆ 178287.0 ┆ 329381        ┆ 87347.0    ┆ … ┆ 590201        ┆ 586273        ┆ 631712.0    ┆ 464082        │
│ null_count ┆ 524898.0 ┆ 373804        ┆ 615838.0   ┆ … ┆ 112984        ┆ 116912        ┆ 71473.0     ┆ 239103        │
│ mean       ┆ 7.130547 ┆ null          ┆ 3.337711   ┆ … ┆ null          ┆ null          ┆ 1981.447123 ┆ null          │
│ std        ┆ 3.64762  ┆ null          ┆ 3.105043   ┆ … ┆ null          ┆ null          ┆ 25.550448   ┆ null          │
│ min        ┆ -0.13    ┆               ┆ -1.0       ┆ … ┆ Apartment     ┆ AGR1          ┆ 1862.0      ┆ inferior      │
│            ┆          ┆               ┆            ┆   ┆ (High Rise)   ┆               ┆             ┆               │
│ 25%        ┆ 5.051146 ┆ null          ┆ 2.0        ┆ … ┆ null          ┆ null          ┆ 1966.0      ┆ null          │
│ 50%        ┆ 7.27     ┆ null          ┆ 3.0        ┆ … ┆ null          ┆ null          ┆ 1986.0      ┆ null          │
│ 75%        ┆ 9.16     ┆ null          ┆ 5.0        ┆ … ┆ null          ┆ null          ┆ 2002.0      ┆ null          │
│ max        ┆ 164.46   ┆ 大統華 T&T    ┆ 171.0      ┆ … ┆ Wharf         ┆ RES4          ┆ 2025.0      ┆ superior      │
│            ┆          ┆ Supermarket   ┆            ┆   ┆               ┆               ┆             ┆               │
└────────────┴──────────┴───────────────┴────────────┴───┴───────────────┴───────────────┴─────────────┴───────────────┘

# Time to COMBINE LIKE FIELDS

---

### These are the cleaned fields:

---

#### General occupancy fields: 

- BLDGCLASS_to_general

- development_type (null Nonresidential, and rename to Residential)

- R_or_C rename to Commercial

- BUILDING_U_to_general

#### Specific occupancy fields: 

- type_to_specific

- NONRESIDENTIAL_SUBTYPE_to_specific

- DEVELOPMENT_SUBTYPE_to_specific

- BUILDING_U_to_specific

- BLDG_TYPE_to_specific

- BLDG_SUBTYP_to_specific

- PRIMARY_USE_to_specific 

- Subtype renamed to Offices

- ACTUAL_USE_DESCRIPTION_to_specific

- MANUAL_CLASS_TYPE to MC_subtype to MC_subtype_to_specific


#### Construction Typology Fields: 

- STRUCTURAL to construction_typology_codes

- STRUCTUR00 to construction_typology_descriptions

- FOUNDATION_TYPE

- MANUAL_CLASS_TYPE to MC_quality to seismic_build_quality


#### Seismic Code fields: 

- MANUAL_CLASS_TYPE to MC_quality to seismic_build_quality

- MANUAL_CLASS_TYPE to MC_storeys  

- MANUAL_CLASS_TYPE to MC_age (range of architectural age) + CONSTRUCTION_YEAR + Year_Built + YEAR_BUILT to year_built

#### Starting with the obvious combinations:
1. Building_Area_M2 + TOTAL_FINISHED_AREA_SQFT
2. CONSTRUCTION_YEAR + Year_Built + YEAR_BUILT
3. Height_M + Height_Flr + STOREYS
4. SQM_FTPRNT + Shape_Area
5. NUM_RES + POPULATION
6. name + BLDG_NAME (might help us impute other attributes if others are missing)
7. ADDRESS + Address_1 + Full_Street_Address (important for ground-truthing)

In [5]:
# overlap summary table to analyze and combine accordingly
from typing import Optional

def create_overlap_summary_table(
    df: pl.DataFrame,
    col1: str,
    col2: str,
    col3: Optional[str] = None,
    col4: Optional[str] = None,
    col5: Optional[str] = None,
):
    """
    Create a visual summary table of row overlap for up to 5 fields.
    """
    cols = [col1, col2, col3, col4, col5]
    cols = [c for c in cols if c is not None]

    group_exprs = [
        pl.col(c).is_not_null().alias(f"Has_{c}")
        for c in cols
    ]

    return (
        df.group_by(group_exprs)
          .len()
          .sort("len", descending=True)
    )

___
1. Building_Area_M2 + TOTAL_FINISHED_AREA_SQFT
---

In [6]:
# 1. Convert units: SQFT to M2 (1 sqft = 0.092903 m²), and rename
# Convert and rename in one step
df = df.with_columns([(pl.col('TOTAL_FINISHED_AREA_SQFT') * 0.092903).alias('TOTAL_FINISHED_AREA_M2')]).drop('TOTAL_FINISHED_AREA_SQFT')

In [7]:

create_overlap_summary_table(df, 'Building_Area_M2', 'TOTAL_FINISHED_AREA_M2')

shape: (4, 3)
┌──────────────────────┬────────────────────────────┬────────┐
│ Has_Building_Area_M2 ┆ Has_TOTAL_FINISHED_AREA_M2 ┆ len    │
│ ---                  ┆ ---                        ┆ ---    │
│ bool                 ┆ bool                       ┆ u32    │
╞══════════════════════╪════════════════════════════╪════════╡
│ false                ┆ true                       ┆ 584632 │
│ false                ┆ false                      ┆ 108364 │
│ true                 ┆ true                       ┆ 8608   │
│ true                 ┆ false                      ┆ 1581   │
└──────────────────────┴────────────────────────────┴────────┘

In [8]:
#Before combining, let's check schema...
print(df.select(['Building_Area_M2', 'TOTAL_FINISHED_AREA_M2']).schema)

Schema({'Building_Area_M2': String, 'TOTAL_FINISHED_AREA_M2': Float64})

In [9]:
# 2. Convert schema
df = df.with_columns([pl.col('Building_Area_M2').cast(pl.Float64, strict=False).alias('Building_Area_M2')])

In [10]:
#now let's see co-occuring rows side by side
co_occurring = df.filter(
    (pl.col('Building_Area_M2').is_not_null()) & 
    (pl.col('TOTAL_FINISHED_AREA_M2').is_not_null()) &
    (pl.col('Building_Area_M2') != 0) &
    (pl.col('TOTAL_FINISHED_AREA_M2') != 0)
).select(['Building_Area_M2', 'TOTAL_FINISHED_AREA_M2']).head(20)

print(co_occurring)

shape: (20, 2)
┌──────────────────┬────────────────────────┐
│ Building_Area_M2 ┆ TOTAL_FINISHED_AREA_M2 │
│ ---              ┆ ---                    │
│ f64              ┆ f64                    │
╞══════════════════╪════════════════════════╡
│ 1469.7456        ┆ 141.398366             │
│ 3923.9952        ┆ 180.882141             │
│ 548.64           ┆ 195.467912             │
│ 1842.17          ┆ 1598.674824            │
│ 98.2             ┆ 200.67048              │
│ …                ┆ …                      │
│ 1809.38          ┆ 2879.435582            │
│ 1210.71          ┆ 2879.435582            │
│ 495.64           ┆ 2879.435582            │
│ 8150.2           ┆ 7179.822549            │
│ 642.15           ┆ 7179.822549            │
└──────────────────┴────────────────────────┘

Okay there seems to be some disparity here... I will ground truth the row where Building_Area_M2 = 642.15, since it deviates furthest from TOTAL_FINISHED_AREA_M2 the most. I will find the corresponding address:

In [11]:
address = df.filter(
    pl.col('Building_Area_M2').cast(pl.Float64, strict=False) == 642.15
).select(['Full_Street_Address', 'Building_Area_M2', 'TOTAL_FINISHED_AREA_M2'])

print(address)

shape: (1, 3)
┌─────────────────────────────────┬──────────────────┬────────────────────────┐
│ Full_Street_Address             ┆ Building_Area_M2 ┆ TOTAL_FINISHED_AREA_M2 │
│ ---                             ┆ ---              ┆ ---                    │
│ str                             ┆ f64              ┆ f64                    │
╞═════════════════════════════════╪══════════════════╪════════════════════════╡
│ 813 AGNES ST NEW WESTMINSTER V… ┆ 642.15           ┆ 7179.822549            │
└─────────────────────────────────┴──────────────────┴────────────────────────┘

*found on rew* - Floors: 15 - therefore second column is correct. 
Let's try Building_Area_M2 = 3923.9952:

In [12]:
address = df.filter(
    pl.col('Building_Area_M2').cast(pl.Float64, strict=False) == 3923.9952
).select(['Full_Street_Address', 'Building_Area_M2', 'TOTAL_FINISHED_AREA_M2'])

print(address)

shape: (1, 3)
┌─────────────────────────────────┬──────────────────┬────────────────────────┐
│ Full_Street_Address             ┆ Building_Area_M2 ┆ TOTAL_FINISHED_AREA_M2 │
│ ---                             ┆ ---              ┆ ---                    │
│ str                             ┆ f64              ┆ f64                    │
╞═════════════════════════════════╪══════════════════╪════════════════════════╡
│ 17910 COLEBROOK RD SURREY V3Z … ┆ 3923.9952        ┆ 180.882141             │
└─────────────────────────────────┴──────────────────┴────────────────────────┘

This is a homeless shelter, menaing the first column is correct. I think it's safe to just take the highest value from each column for any of the co-occuring rows.

In [13]:
# 3. COMBINE: create new column Total_Building_Area_M2 | for co-occurring rows, take the maximum of the two values | for single values, just use that value
df = df.with_columns([
    pl.when(
        pl.col('Building_Area_M2').cast(pl.Float64, strict=False).is_not_null() &
        pl.col('TOTAL_FINISHED_AREA_M2').is_not_null()
    )
    .then(
        pl.max_horizontal([
            pl.col('Building_Area_M2').cast(pl.Float64, strict=False),
            pl.col('TOTAL_FINISHED_AREA_M2')
        ])
    )
    .otherwise(
        pl.coalesce([
            pl.col('Building_Area_M2').cast(pl.Float64, strict=False),
            pl.col('TOTAL_FINISHED_AREA_M2')
        ])
    )
    .alias('building_area_M2')
])

# Verify the results
print(df.select([
    'Building_Area_M2', 
    'TOTAL_FINISHED_AREA_M2', 
    'building_area_M2'
]).head(20))

shape: (20, 3)
┌──────────────────┬────────────────────────┬──────────────────┐
│ Building_Area_M2 ┆ TOTAL_FINISHED_AREA_M2 ┆ building_area_M2 │
│ ---              ┆ ---                    ┆ ---              │
│ f64              ┆ f64                    ┆ f64              │
╞══════════════════╪════════════════════════╪══════════════════╡
│ null             ┆ 202.52854              ┆ 202.52854        │
│ null             ┆ 662.862905             ┆ 662.862905       │
│ null             ┆ 193.23824              ┆ 193.23824        │
│ null             ┆ 394.744847             ┆ 394.744847       │
│ null             ┆ 244.427793             ┆ 244.427793       │
│ …                ┆ …                      ┆ …                │
│ null             ┆ 709.314405             ┆ 709.314405       │
│ null             ┆ 444.07634              ┆ 444.07634        │
│ null             ┆ 392.793884             ┆ 392.793884       │
│ null             ┆ 238.110389             ┆ 238.110389       │
│ null             ┆ 501.954909             ┆ 501.954909       │
└──────────────────┴────────────────────────┴──────────────────┘

In [14]:
# 4. drop the old columns

df = df.drop(['Building_Area_M2', 'TOTAL_FINISHED_AREA_M2'])

---
3. Height_M + Height_Flr + STOREYS + MC_Storeys
---

In [15]:
# 1. change to consistent units (change M to floors, 3.3 M = 1 flr) and consistent schemas
def height_to_storeys(height_col):
    """Convert Height_M to estimated storeys (3.3m per storey)"""
    return (height_col / 3.3).ceil().cast(pl.Int32)

# Use it:
df = df.with_columns([
    height_to_storeys(pl.col('Height_M')).alias('storeys_from_height')
])

In [16]:
# check schemas
df.select(['storeys_from_height', 'Height_Flr', 'STOREYS','MC_storeys']).schema

Schema([('storeys_from_height', Int32),
        ('Height_Flr', Float64),
        ('STOREYS', Float64),
        ('MC_storeys', Float64)])

#### MC_Storeys has values of 1.5 storeys. I will combine the other fields as integers first, then change the data type to float64 to combine with MC_storeys

In [17]:
# 1. convert schema to integers (no decimals needed)
df = df.with_columns([
    pl.col('Height_Flr').cast(pl.Int32, strict=False),
    pl.col('STOREYS').cast(pl.Int32, strict=False),
])

In [18]:
create_overlap_summary_table(df, 'storeys_from_height', 'Height_Flr', 'STOREYS', 'MC_storeys')

shape: (16, 5)
┌─────────────────────────┬────────────────┬─────────────┬────────────────┬────────┐
│ Has_storeys_from_height ┆ Has_Height_Flr ┆ Has_STOREYS ┆ Has_MC_storeys ┆ len    │
│ ---                     ┆ ---            ┆ ---         ┆ ---            ┆ ---    │
│ bool                    ┆ bool           ┆ bool        ┆ bool           ┆ u32    │
╞═════════════════════════╪════════════════╪═════════════╪════════════════╪════════╡
│ false                   ┆ false          ┆ true        ┆ true           ┆ 331791 │
│ true                    ┆ false          ┆ true        ┆ true           ┆ 139005 │
│ false                   ┆ true           ┆ true        ┆ true           ┆ 66851  │
│ false                   ┆ false          ┆ false       ┆ false          ┆ 63936  │
│ false                   ┆ false          ┆ true        ┆ false          ┆ 50791  │
│ …                       ┆ …              ┆ …           ┆ …              ┆ …      │
│ true                    ┆ true           ┆ true        ┆ false          ┆ 577    │
│ false                   ┆ false          ┆ false       ┆ true           ┆ 319    │
│ true                    ┆ false          ┆ false       ┆ true           ┆ 40     │
│ true                    ┆ true           ┆ false       ┆ true           ┆ 18     │
│ false                   ┆ true           ┆ false       ┆ true           ┆ 15     │
└─────────────────────────┴────────────────┴─────────────┴────────────────┴────────┘

In [19]:
# 2. Combine the 4, taking highest value 
df = df.with_columns([
    pl.max_horizontal(['storeys_from_height', 'Height_Flr', 'STOREYS',])
      .alias('building_storeys_int')
])

In [20]:
# check schemas
df.select(['building_storeys_int', 'MC_storeys']).schema

Schema([('building_storeys_int', Int32), ('MC_storeys', Float64)])

In [21]:
# 1. since there is 1.5 storeys in MC_storeys, I will convert to float64
df = df.with_columns([
    pl.col('building_storeys_int').cast(pl.Float64, strict=False),
])

In [22]:
# 2. take the highest of the columns, since the default seems to be 1

df = df.with_columns(
    pl.max_horizontal(['building_storeys_int', 'MC_storeys']).alias('building_storeys')
)

In [23]:
# 3. drop old columns 
df = df.drop(['storeys_from_height', 'Height_Flr', 'STOREYS', 'Height_M'])

In [24]:
# 3. drop old columns
df = df.drop(['building_storeys_int', 'MC_storeys'])

---
4. For SQM_FTPRNT + Shape_Area, populate new column with SQM footprint first, then use shape area

---

In [25]:
df.select(['SQM_FTPRNT', 'Shape_Area']).schema

Schema([('SQM_FTPRNT', Float64), ('Shape_Area', Float64)])

In [26]:
df = df.with_columns(
    pl.col('SQM_FTPRNT').fill_null(pl.col('Shape_Area')).alias('building_footprint_M2')
)

In [27]:
# drop old column
df = df.drop('SQM_FTPRNT')

---
5. NUM_RES + POPULATION

---

In [28]:
df.select(['NUM_RES', 'POPULATION']).schema

Schema([('NUM_RES', Float64), ('POPULATION', Float64)])

In [29]:
print(create_overlap_summary_table(df, 'NUM_RES', 'POPULATION'))

shape: (3, 3)
┌─────────────┬────────────────┬────────┐
│ Has_NUM_RES ┆ Has_POPULATION ┆ len    │
│ ---         ┆ ---            ┆ ---    │
│ bool        ┆ bool           ┆ u32    │
╞═════════════╪════════════════╪════════╡
│ false       ┆ false          ┆ 670626 │
│ false       ┆ true           ┆ 23273  │
│ true        ┆ false          ┆ 9286   │
└─────────────┴────────────────┴────────┘

In [30]:
# easy combination - no overlap!

df = df.with_columns(
    pl.coalesce(['NUM_RES', 'POPULATION']).alias('building_population')
)

In [31]:
df = df.drop(['NUM_RES', 'POPULATION'])

---
6. name + BLDG_NAME (might help us impute other attributes if others are missing)

---

In [32]:
df.select(['name', 'BLDG_NAME']).schema

Schema([('name', String), ('BLDG_NAME', String)])

In [33]:
print(create_overlap_summary_table(df, 'name', 'BLDG_NAME'))

shape: (3, 3)
┌──────────┬───────────────┬────────┐
│ Has_name ┆ Has_BLDG_NAME ┆ len    │
│ ---      ┆ ---           ┆ ---    │
│ bool     ┆ bool          ┆ u32    │
╞══════════╪═══════════════╪════════╡
│ false    ┆ false         ┆ 373804 │
│ true     ┆ false         ┆ 306108 │
│ true     ┆ true          ┆ 23273  │
└──────────┴───────────────┴────────┘

In [34]:
df['name'].describe()

shape: (4, 2)
┌────────────┬────────────────────────┐
│ statistic  ┆ value                  │
│ ---        ┆ ---                    │
│ str        ┆ str                    │
╞════════════╪════════════════════════╡
│ count      ┆ 329381                 │
│ null_count ┆ 373804                 │
│ min        ┆                        │
│ max        ┆ 大統華 T&T Supermarket │
└────────────┴────────────────────────┘

In [35]:
#replace empty strings with null
df = df.with_columns(
    pl.col('name').replace('BUILDING', None).alias('name')
)

In [36]:
# get rows where both columns are not null, then take first 20
comparison = df.filter(
    pl.col('name').is_not_null() & pl.col('BLDG_NAME').is_not_null()
).select(['name', 'BLDG_NAME']).head(10)

print(comparison)

shape: (10, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ name                            ┆ BLDG_NAME                       │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ LOG RESIDENCE                   ┆ LOG RESIDENCE                   │
│ RESIDENTIAL (1864 BELLE ISLE P… ┆ RESIDENTIAL (1864 BELLE ISLE P… │
│ WOOLCOX RESIDENCE               ┆ WOOLCOX RESIDENCE               │
│ BOBAK RESIDENCE                 ┆ BOBAK RESIDENCE                 │
│ BARNES RESIDENCE                ┆ BARNES RESIDENCE                │
│ PERRY RESIDENCE                 ┆ PERRY RESIDENCE                 │
│ SKELCHER RESIDENCE              ┆ SKELCHER RESIDENCE              │
│ HOFFMAN RESIDENCE               ┆ HOFFMAN RESIDENCE               │
│ LENNOX RESIDENCE                ┆ LENNOX RESIDENCE                │
│ LONEY RESIDENCE                 ┆ LONEY RESIDENCE                 │
└─────────────────────────────────┴─────────────────────────────────┘

In [37]:
#replace BUILDING with null (it's not a name)
df = df.with_columns([
    pl.col('name').replace('BUILDING', None).alias('name'),
    pl.col('BLDG_NAME').replace('BUILDING', None).alias('BLDG_NAME')
])

In [38]:
print(create_overlap_summary_table(df, 'name', 'BLDG_NAME'))

shape: (3, 3)
┌──────────┬───────────────┬────────┐
│ Has_name ┆ Has_BLDG_NAME ┆ len    │
│ ---      ┆ ---           ┆ ---    │
│ bool     ┆ bool          ┆ u32    │
╞══════════╪═══════════════╪════════╡
│ false    ┆ false         ┆ 394311 │
│ true     ┆ false         ┆ 306108 │
│ true     ┆ true          ┆ 2766   │
└──────────┴───────────────┴────────┘

In [39]:
# get rows where both columns are not null, then take first 20
print(df.filter(
    pl.col('name').is_not_null() & pl.col('BLDG_NAME').is_not_null()
).select(['name', 'BLDG_NAME']).head(10))

shape: (10, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ name                            ┆ BLDG_NAME                       │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ LOG RESIDENCE                   ┆ LOG RESIDENCE                   │
│ RESIDENTIAL (1864 BELLE ISLE P… ┆ RESIDENTIAL (1864 BELLE ISLE P… │
│ WOOLCOX RESIDENCE               ┆ WOOLCOX RESIDENCE               │
│ BOBAK RESIDENCE                 ┆ BOBAK RESIDENCE                 │
│ BARNES RESIDENCE                ┆ BARNES RESIDENCE                │
│ PERRY RESIDENCE                 ┆ PERRY RESIDENCE                 │
│ SKELCHER RESIDENCE              ┆ SKELCHER RESIDENCE              │
│ HOFFMAN RESIDENCE               ┆ HOFFMAN RESIDENCE               │
│ LENNOX RESIDENCE                ┆ LENNOX RESIDENCE                │
│ LONEY RESIDENCE                 ┆ LONEY RESIDENCE                 │
└─────────────────────────────────┴─────────────────────────────────┘

In [40]:
#They look the same. I am just going to drop name
df = df.drop('name')

In [41]:
df = df.rename({'BLDG_NAME': 'building_name'})

---
7. ADDRESS + Address_1 + Full_Street_Address (important for ground-truthing)

---

In [42]:
print(create_overlap_summary_table(df, 'ADDRESS', 'Address_1', 'Full_Street_Address'))

shape: (8, 4)
┌─────────────┬───────────────┬─────────────────────────┬────────┐
│ Has_ADDRESS ┆ Has_Address_1 ┆ Has_Full_Street_Address ┆ len    │
│ ---         ┆ ---           ┆ ---                     ┆ ---    │
│ bool        ┆ bool          ┆ bool                    ┆ u32    │
╞═════════════╪═══════════════╪═════════════════════════╪════════╡
│ false       ┆ false         ┆ true                    ┆ 589763 │
│ false       ┆ false         ┆ false                   ┆ 72324  │
│ true        ┆ false         ┆ true                    ┆ 38015  │
│ true        ┆ false         ┆ false                   ┆ 1923   │
│ false       ┆ true          ┆ false                   ┆ 1015   │
│ false       ┆ true          ┆ true                    ┆ 100    │
│ true        ┆ true          ┆ false                   ┆ 39     │
│ true        ┆ true          ┆ true                    ┆ 6      │
└─────────────┴───────────────┴─────────────────────────┴────────┘

In [43]:
print(df.filter(
    pl.col('ADDRESS').is_not_null() & pl.col('Address_1').is_not_null() & pl.col('Full_Street_Address').is_not_null()
).select(['ADDRESS', 'Address_1', 'Full_Street_Address']))

shape: (6, 3)
┌──────────────────┬──────────────────┬─────────────────────────────────┐
│ ADDRESS          ┆ Address_1        ┆ Full_Street_Address             │
│ ---              ┆ ---              ┆ ---                             │
│ str              ┆ str              ┆ str                             │
╞══════════════════╪══════════════════╪═════════════════════════════════╡
│ 549 COLUMBIA ST  ┆ 549 Columbia     ┆ 549 COLUMBIA ST NEW WESTMINSTE… │
│ 681 COLUMBIA ST  ┆ 681 Columbia St  ┆ 680 CLARKSON ST NEW WESTMINSTE… │
│ 1003 COLUMBIA ST ┆ 1001 Columbia St ┆ 98 TENTH ST NEW WESTMINSTER V3… │
│ 610 SIXTH ST     ┆ 610 6th St       ┆ 612 SIXTH ST NEW WESTMINSTER V… │
│ 55 TENTH ST      ┆ 889 Carnarvon St ┆ 55 TENTH ST NEW WESTMINSTER V3… │
│ 55 TENTH ST      ┆ 889 Carnarvon St ┆ 55 TENTH ST NEW WESTMINSTER V3… │
└──────────────────┴──────────────────┴─────────────────────────────────┘

In [44]:
# create 'address' column with priority: Full_Street_Address > ADDRESS > Address_1
df = df.with_columns(
    pl.coalesce(['Full_Street_Address', 'ADDRESS', 'Address_1']).alias('building_address')
)

In [45]:
# drop old columns
df = df.drop(['Full_Street_Address', 'ADDRESS', 'Address_1'])

### ok... now let's see what we are working with

In [46]:
df.describe()

shape: (9, 37)
┌────────────┬──────────────┬──────────────┬──────────────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ statistic  ┆ development_ ┆ building_nam ┆ Construction ┆ … ┆ building_sto ┆ building_fo ┆ building_po ┆ building_ad │
│ ---        ┆ type         ┆ e            ┆ _Typology_Co ┆   ┆ reys         ┆ otprint_M2  ┆ pulation    ┆ dress       │
│ str        ┆ ---          ┆ ---          ┆ de           ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│            ┆ str          ┆ str          ┆ ---          ┆   ┆ f64          ┆ f64         ┆ f64         ┆ str         │
│            ┆              ┆              ┆ str          ┆   ┆              ┆             ┆             ┆             │
╞════════════╪══════════════╪══════════════╪══════════════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ count      ┆ 128482       ┆ 2766         ┆ 23273        ┆ … ┆ 639249.0     ┆ 703185.0    ┆ 32559.0     ┆ 630861      │
│ null_count ┆ 574703       ┆ 700419       ┆ 679912       ┆ … ┆ 63936.0      ┆ 0.0         ┆ 670626.0    ┆ 72324       │
│ mean       ┆ null         ┆ null         ┆ null         ┆ … ┆ 2.146546     ┆ 894.380175  ┆ 4.21161     ┆ null        │
│ std        ┆ null         ┆ null         ┆ null         ┆ … ┆ 1.491064     ┆ 39954.17624 ┆ 14.388201   ┆ null        │
│            ┆              ┆              ┆              ┆   ┆              ┆ 1           ┆             ┆             │
│ min        ┆ Residential  ┆ 27 NORTH     ┆              ┆ … ┆ 0.0          ┆ 0.0         ┆ 0.0         ┆ MAPLE RIDGE │
│            ┆              ┆              ┆              ┆   ┆              ┆             ┆             ┆ BC          │
│ 25%        ┆ null         ┆ null         ┆ null         ┆ … ┆ 1.0          ┆ 78.433903   ┆ 2.0         ┆ null        │
│ 50%        ┆ null         ┆ null         ┆ null         ┆ … ┆ 2.0          ┆ 162.582184  ┆ 3.147       ┆ null        │
│ 75%        ┆ null         ┆ null         ┆ null         ┆ … ┆ 2.0          ┆ 254.033691  ┆ 3.348       ┆ null        │
│ max        ┆ Residential  ┆ YORKWOOD     ┆ W2           ┆ … ┆ 171.0        ┆ 2.6705e7    ┆ 790.409     ┆ WOODS RD    │
│            ┆              ┆ PARK         ┆              ┆   ┆              ┆             ┆             ┆ BOWEN       │
│            ┆              ┆              ┆              ┆   ┆              ┆             ┆             ┆ ISLAND BC   │
└────────────┴──────────────┴──────────────┴──────────────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [47]:
#oops
df = df.rename({'development_type': 'Residential'})

In [48]:
#Checkpoint!

df.write_parquet('general_combinations_made.parquet')

## Combinations made: 
- Height_M + Height_Flr + STOREYS + MC_storeys = building_storeys
- SQM_FTPRNT + Shape_Area = building_footprint_M2
- NUM_RES + POPULATION = building_population
- Building_Area_M2 + TOTAL_FINISHED_AREA_SQFT = total_building_area_M2
- name + BLDG_NAME = building_name
- ADDRESS + Address_1 + Full_Street_Address = building_address

## Combinations to be made
- all Specific Occupancy fields (10 fields)
1. type_to_specific
2. NONRESIDENTIAL_SUBTYPE_to_specific
3. DEVELOPMENT_SUBTYPE_to_specific
4. BUILDING_U_to_specific
5. BLDG_TYPE_to_specific
6. BLDG_SUBTYP_to_specific
7. PRIMARY_USE_to_specific
8. Offices
9. ACTUAL_USE_DESCRIPTION_to_specific
10. MC_subtype_to_specific

- all General Occupancy fields (4 fields)
1. BUILDING_U_to_general
2. BLDGCLASS_to_general
3. Commercial
4. Residential

These will need a bit more attention...