In [4]:
!pip install polars

Defaulting to user installation because normal site-packages is not writeable
Collecting polars
  Downloading polars-1.35.2-py3-none-any.whl.metadata (10 kB)
Collecting polars-runtime-32==1.35.2 (from polars)
  Downloading polars_runtime_32-1.35.2-cp39-abi3-win_amd64.whl.metadata (1.5 kB)
Downloading polars-1.35.2-py3-none-any.whl (783 kB)
   ---------------------------------------- 0.0/783.6 kB ? eta -:--:--
   ---------------------------------------- 783.6/783.6 kB 9.1 MB/s  0:00:00
Downloading polars_runtime_32-1.35.2-cp39-abi3-win_amd64.whl (41.3 MB)
   ---------------------------------------- 0.0/41.3 MB ? eta -:--:--
   ---- ----------------------------------- 4.7/41.3 MB 23.1 MB/s eta 0:00:02
   -------- ------------------------------- 8.7/41.3 MB 23.3 MB/s eta 0:00:02
   -------- ------------------------------- 8.7/41.3 MB 23.3 MB/s eta 0:00:02
   --------- ------------------------------ 9.7/41.3 MB 11.7 MB/s eta 0:00:03
   ---------- ----------------------------- 11.3/41.3 MB 10.8 MB/s eta 0:00:03
   -------------- ------------------------- 15.2/41.3 MB 12.2 MB/s eta 0:00:03
   ------------------- -------------------- 19.9/41.3 MB 13.5 MB/s eta 0:00:02
   --------------------- ------------------ 22.3/41.3 MB 13.2 MB/s eta 0:00:02
   ------------------------ --------------- 25.7/41.3 MB 13.6 MB/s eta 0:00:02
   ---------------------------- ----------- 29.1/41.3 MB 13.9 MB/s eta 0:00:01
   ------------------------------- -------- 32.5/41.3 MB 14.1 MB/s eta 0:00:01
   ---------------------------------- ----- 35.7/41.3 MB 14.2 MB/s eta 0:00:01
   ------------------------------------- -- 38.8/41.3 MB 14.3 MB/s eta 0:00:01
   ---------------------------------------  41.2/41.3 MB 14.2 MB/s eta 0:00:01
   ---------------------------------------- 41.3/41.3 MB 13.7 MB/s  0:00:02
Installing collected packages: polars-runtime-32, polars

   ---------------------------------------- 0/2 [polars-runtime-32]
   ---------------------------------------- 0/2 [polars-runtime-32]
   ---------------------------------------- 0/2 [polars-runtime-32]
   ---------------------------------------- 0/2 [polars-runtime-32]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   ---------------------------------------- 2/2 [polars]

Successfully installed polars-1.35.2 polars-runtime-32-1.35.2

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\jasmi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [94]:
!pip install seaborn

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 25.2 -> 25.3

Collecting seaborn

[notice] To update, run: C:\Users\jasmi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (2.3.5)
Requirement already satisfied: pandas>=1.2 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

In [74]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.3.5-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.0 MB 2.4 MB/s eta 0:00:05
   ---- ----------------------------------- 1.3/11.0 MB 2.1 MB/s eta 0:00:05
   ------ --------------------------------- 1.8/11.0 MB 2.3 MB/s eta 0:00:05
   -------- ------------------------------- 2.4/11.0 MB 2.2 MB/s eta 0:00:04
   ---------- ----------------------------- 2.9/11.0 MB 2.4 MB/s eta 0:00:04
   ------------- -------------------------- 3.7/11.0 MB 2.5 MB/s eta 0:00:03
   --------------- ------------------------ 4.2/11.0 MB 2.6 MB/s eta 0:00:03
   ----------------- ---------------------- 4.7/11.0 MB 2.7 MB/s eta 0:00:03
   ------------------- -------------------- 5.2/11.0 MB 2.6 MB/s eta 0:00:03
   -------------------- ------------------- 5.8/11.0 MB 2.6 MB/s eta 0:00:03
   ----------------------- ---------------- 6.6/11.0 MB 2.6 MB/s eta 0:00:02
   ------------------------- -------------- 7.1/11.0 MB 2.6 MB/s eta 0:00:02
   ---------------------------- ----------- 7.9/11.0 MB 2.7 MB/s eta 0:00:02
   ------------------------------- -------- 8.7/11.0 MB 2.7 MB/s eta 0:00:01
   --------------------------------- ------ 9.2/11.0 MB 2.8 MB/s eta 0:00:01
   ----------------------------------- ---- 9.7/11.0 MB 2.8 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/11.0 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 2.7 MB/s  0:00:04
Downloading numpy-2.3.5-cp313-cp313-win_amd64.whl (12.8 MB)
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.8 MB 2.6 MB/s eta 0:00:05
   ---- ----------------------------------- 1.3/12.8 MB 2.4 MB/s eta 0:00:05
   ----- ---------------------------------- 1.8/12.8 MB 2.5 MB/s eta 0:00:05
   -------- ------------------------------- 2.6/12.8 MB 2.5 MB/s eta 0:00:05
   --------- ------------------------------ 3.1/12.8 MB 2.6 MB/s eta 0:00:04
   ----------- ---------------------------- 3.7/12.8 MB 2.6 MB/s eta 0:00:04
   ------------- -------------------------- 4.2/12.8 MB 2.6 MB/s eta 0:00:04
   --------------- ------------------------ 5.0/12.8 MB 2.7 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.8 MB 2.7 MB/s eta 0:00:03
   ------------------- -------------------- 6.3/12.8 MB 2.8 MB/s eta 0:00:03
   ---------------------- ----------------- 7.1/12.8 MB 2.8 MB/s eta 0:00:03
   ------------------------ --------------- 7.9/12.8 MB 2.9 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.8 MB 3.0 MB/s eta 0:00:02
   ------------------------------ --------- 9.7/12.8 MB 3.1 MB/s eta 0:00:01
   -------------------------------- ------- 10.5/12.8 MB 3.2 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.8 MB 3.2 MB/s eta 0:00:01
   ------------------------------------- -- 12.1/12.8 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 3.2 MB/s  0:00:03
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Installing collected packages: pytz, numpy, pandas

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\jasmi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [88]:
!pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 25.2 -> 25.3

Collecting matplotlib

[notice] To update, run: C:\Users\jasmi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

  Downloading matplotlib-3.10.7-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.61.0-cp313-cp313-win_amd64.whl.metadata (115 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.9-cp313-cp313-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.0.0-cp313-cp313-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.2.5-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.7-cp313-cp313-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------- ----------------------------- 2.1/8.1 MB 10.8 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.1 MB 14.5 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 13.6 MB/s  0:00:00
Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.61.0-cp313-cp313-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 24.3 MB/s  0:00:00
Downloading kiwisolver-1.4.9-cp313-cp313-win_amd64.whl (73 kB)
Downloading pillow-12.0.0-cp313-cp313-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   -------------------- ------------------- 3.7/7.0 MB 17.0 MB/s eta 0:00:01
   ---------------------------------------- 7.0/7.0 MB 20.2 MB/s  0:00:00
Downloading pyparsing-3.2.5-py3-none-any.whl (113 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------------- 7/7 [matplotlib]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.61.0 kiwisolver-1.4.9 matplotlib-3.10.7 pillow-12.0.0 pyparsing-3.2.5

In [10]:
pip install openpyxl xlsx2csv fastexcel

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting xlsx2csv
  Downloading xlsx2csv-0.8.4-py3-none-any.whl.metadata (5.7 kB)
Collecting fastexcel
  Downloading fastexcel-0.18.0-cp310-abi3-win_amd64.whl.metadata (7.4 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading xlsx2csv-0.8.4-py3-none-any.whl (15 kB)
Downloading fastexcel-0.18.0-cp310-abi3-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.9 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.9 MB 1.3 MB/s eta 0:00:02
   -------------- ------------------------- 1.0/2.9 MB 1.5 MB/s eta 0:00:02
   ------------------ --------------------- 1.3/2.9 MB 1.5 MB/s eta 0:00:02
   --------------------- ------------------ 1.6/2.9 MB 1.5 MB/s eta 0:00:01
   ----------------------------- ---------- 2.1/2.9 MB 1.6 MB/s eta 0:00:01
   ------------------------------------ --- 2.6/2.9 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 1.7 MB/s  0:00:01
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: xlsx2csv, fastexcel, et-xmlfile, openpyxl

   ---------------------------------------- 0/4 [xlsx2csv]
   ---------- ----------------------------- 1/4 [fastexcel]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ------------------------------ --------- 3/4 [openpyxl]
   ---------------------------------------- 4/4 [openpyxl]

Successfully installed et-xmlfile-2.0.0 fastexcel-0.18.0 openpyxl-3.1.5 xlsx2csv-0.8.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\jasmi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [71]:
!pip install plotly

Defaulting to user installation because normal site-packages is not writeable
Collecting plotly
  Downloading plotly-6.5.0-py3-none-any.whl.metadata (8.5 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Downloading narwhals-2.13.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: packaging in c:\users\jasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from plotly) (25.0)
Downloading plotly-6.5.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------- ----------------------------- 2.6/9.9 MB 21.7 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 31.2 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 28.5 MB/s  0:00:00
Downloading narwhals-2.13.0-py3-none-any.whl (426 kB)
Installing collected packages: narwhals, plotly

   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   ---------------------------------------- 2/2 [plotly]

Successfully installed narwhals-2.13.0 plotly-6.5.0

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\jasmi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


# METRO VANCOUVER SEISMIC RISK ANALYSIS: End GOALS
## 1. Create the HAZUS fields:
- Seismic Design Level
- Construction Typology
- General Occupancy Class
- Specific Occupancy Class
## 2. Create my own fields: 
- Size: will include (footprint x storeys x basement) + underground carports (20 m^2 each)
- With the size, I will bring this value into Arcgis Pro to create a Building Density field. This is an important metric to consider when concerning the possibility of building collapse. 
## 3. Create Composite Indices: 
1. Building Exposure Index
2. Building Vulnerability Index
3. Final Composite Building Risk Index

## *WHY HAZUS?* Categorizing buildings within the FEMA HAZUS framework is essential because it is an internationally accepted standardized methodology. This allows for risk systems that are consistent and comparable. 

### *Please expand the cell below to see the classification system created by HAZUS for each of the aforementioned fields:*

---
### Seismic Design Level 
#### Table 5-22 Hazus Tsunami Seismic Design Levels by Field Name

| DesignLevelID | EqDesignLevelId | DesignLevelDesc | Description |
|:-------------:|:---------------:|:----------------|:------------|
| 1 | PC | Pre-Code | **Pre-Code (Pre-1975):** Buildings constructed before 1975 generally had minimal or no specific seismic design requirements compared to modern standards. These buildings are considered to have the highest seismic risk today and may require retrofitting to improve performance. |
| 2 | LC | Low Code | **Low Code (1975–1990):** Seismic requirements began to be included in the building codes in the 1950s, but the 1975-1990 period saw relatively modest requirements. These standards are still considered "low code" by modern assessments. |
| 3 | MC | Moderate Code | **Moderate Code (1990–2005):** The 1990s and early 2000s saw progressively improved and strengthened provisions in the National Building Code of Canada (NBC), which Vancouver adopted into its own building bylaws. |
| 4 | HC | High Code | **High Code (Post-2005):** Modern seismic design in Vancouver follows the rigorous standards of the current BC Building Code and Vancouver Building By-law, which are based on the latest editions of the NBC (e.g., NBC 2020). |

# Seismic Design Level by Construction Quality

| Construction Quality | High-Code | Moderate-Code | Low-Code | None |
|---------------------|-----------|---------------|----------|---------|
| Superior | Special$^1$ | High-Code | Moderate-Code | Low-Code |
| Ordinary | High-Code | Moderate-Code | Low-Code | Pre-Code |
| Inferior | Moderate-Code | Low-Code | Pre-Code | Pre-Code |

---

$^1$ Special designation for superior construction quality with high-code seismic design level.

---
### Construction Typology: 
##### Table 4-2 Earthquake and Tsunami Model Specific Building Types

| Specific Building Type Label | Description | Height Range - Name | Height Range - Stories | Typical Height - Stories | Typical Height - Feet |
|------------------------------|-------------|---------------------|------------------------|--------------------------|---------------------|
| W1 | Wood, Light Frame (≤ 5,000 ft²) | N/A | 1 – 2 | 1 | 14 |
| W2 | Wood, Commercial & Industrial (> 5,000 ft²) | N/A | All | 2 | 24 |
| S1L | Steel Moment Frame | Low-Rise | 1 – 3 | 2 | 24 |
| S1M | Steel Moment Frame | Mid-Rise | 4 – 7 | 5 | 60 |
| S1H | Steel Moment Frame | High-Rise | 8+ | 13 | 156 |
| S2L | Steel Braced Frame | Low-Rise | 1 – 3 | 2 | 24 |
| S2M | Steel Braced Frame | Mid-Rise | 4 – 7 | 5 | 60 |
| S2H | Steel Braced Frame | High-Rise | 8+ | 13 | 156 |
| S3 | Steel Light Frame | N/A | All | 1 | 15 |
| S4L | Steel Frame with Cast-in-Place Concrete Shear Walls | Low-Rise | 1 – 3 | 2 | 24 |
| S4M | Steel Frame with Cast-in-Place Concrete Shear Walls | Mid-Rise | 4 – 7 | 5 | 60 |
| S4H | Steel Frame with Cast-in-Place Concrete Shear Walls | High-Rise | 8+ | 13 | 156 |
| S5L | Steel Frame with Unreinforced Masonry Infill Walls | Low-Rise | 1 – 3 | 2 | 24 |
| S5M | Steel Frame with Unreinforced Masonry Infill Walls | Mid-Rise | 4 – 7 | 5 | 60 |
| S5H | Steel Frame with Unreinforced Masonry Infill Walls | High-Rise | 8+ | 13 | 156 |
| C1L | Concrete Moment Frame | Low-Rise | 1 – 3 | 2 | 20 |
| C1M | Concrete Moment Frame | Mid-Rise | 4 – 7 | 5 | 50 |
| C1H | Concrete Moment Frame | High-Rise | 8+ | 12 | 120 |
| C2L | Concrete Shear Walls | Low-Rise | 1 – 3 | 2 | 20 |
| C2M | Concrete Shear Walls | Mid-Rise | 4 – 7 | 5 | 50 |
| C2H | Concrete Shear Walls | High-Rise | 8+ | 12 | 120 |
| C3L | Concrete Frame with Unreinforced Masonry Infill Walls | Low-Rise | 1 – 3 | 2 | 20 |
| C3M | Concrete Frame with Unreinforced Masonry Infill Walls | Mid-Rise | 4 – 7 | 5 | 50 |
| C3H | Concrete Frame with Unreinforced Masonry Infill Walls | High-Rise | 8+ | 12 | 120 |
| PC1 | Precast Concrete Tilt-Up Walls | N/A | All | 1 | 15 |
| PC2L | Precast Concrete Frames with Concrete Shear Walls | Low-Rise | 1 – 3 | 2 | 20 |
| PC2M | Precast Concrete Frames with Concrete Shear Walls | Mid-Rise | 4 – 7 | 5 | 50 |
| PC2H | Precast Concrete Frames with Concrete Shear Walls | High-Rise | 8+ | 12 | 120 |
| RM1L | Reinforced Masonry Bearing Walls with Wood or Metal Deck Diaphragms | Low-Rise | 1-3 | 2 | 20 |
| RM1M | Reinforced Masonry Bearing Walls with Wood or Metal Deck Diaphragms | Mid-Rise | 4+ | 5 | 50 |
| RM2L | Reinforced Masonry Bearing Walls with Precast Concrete Diaphragms | Low-Rise | 1 – 3 | 2 | 20 |
| RM2M | Reinforced Masonry Bearing Walls with Precast Concrete Diaphragms | Mid-Rise | 4 – 7 | 5 | 50 |
| RM2H | Reinforced Masonry Bearing Walls with Precast Concrete Diaphragms | High-Rise | 8+ | 12 | 120 |
| URML | Unreinforced Masonry Bearing Walls | Low-Rise | 1 – 2 | 1 | 15 |
| URMM | Unreinforced Masonry Bearing Walls | Mid-Rise | 3+ | 3 | 35 |
| MH | Mobile Homes | N/A | All | 1 | 10 |

---
### General and Specific Occupancy Class
#### Table 4-1 Hazus General and Specific Occupancy Classes

| Hazus General Occupancy Class | Hazus Specific Occupancy Class | Class Description |
|-------------------------------|-------------------------------|-------------------|
| Residential | RES1 | Single-family Dwelling |
| Residential | RES2 | Mobile Home |
| Residential | RES3A | Multi-Family Dwelling – Duplex |
| Residential | RES3B | Multi-Family Dwelling – 3-4 Units |
| Residential | RES3C | Multi-Family Dwelling – 5-9 Units |
| Residential | RES3D | Multi-Family Dwelling – 10-19 Units |
| Residential | RES3E | Multi-Family Dwelling – 20-49 Units |
| Residential | RES3F | Multi-Family Dwelling – 50+ Units |
| Residential | RES4 | Temporary Lodging |
| Residential | RES5 | Institutional Dormitory |
| Residential | RES6 | Nursing Home |
| Commercial | COM1 | Retail Trade |
| Commercial | COM2 | Wholesale Trade |
| Commercial | COM3 | Personal and Repair Services |
| Commercial | COM4 | Business/Professional/Technical Services |
| Commercial | COM5 | Depository Institutions (Banks) |
| Commercial | COM6 | Hospital |
| Commercial | COM7 | Medical Office/Clinic |
| Commercial | COM8 | Entertainment & Recreation |
| Commercial | COM9 | Theaters |
| Commercial | COM10 | Parking |
| Industrial | IND1 | Heavy |
| Industrial | IND2 | Light |
| Industrial | IND3 | Food/Drugs/Chemicals |
| Industrial | IND4 | Metals/Minerals Processing |
| Industrial | IND5 | High Technology |
| Industrial | IND6 | Construction |
| Agriculture | AGR1 | Agriculture |
| Religion | REL1 | Church/Non-Profit |
| Government | GOV1 | General Services |
| Government | GOV2 | Emergency Response |
| Education | EDU1 | Schools/Libraries |
| Education | EDU2 | Colleges/Universities |



Source: https://www.fema.gov/sites/default/files/documents/fema_hazus-6-inventory-technical-manual.pdf

In [12]:
import polars as pl
import plotly.io as pio
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from typing import List, Dict, Set

In [13]:
pio.renderers.default = "notebook"

### OK, so we have compiled RAW building data into a single database...

# TIME FOR AN INITIAL CLEAN!

## Goals
#### 1. Explore and drop null columns
#### 2. Use dictionary mapping to clean remaining columns and update the values into HAZUS-compatible terminology, in order to have consistent and combinable values that will be used to compute the final HAZUS metrics.

## 1. EXPLORING DATA AND DROPPING NULL/UNNESSECARY COLUMNS

In [14]:
df = pl.read_parquet(r"C:\Users\jasmi\OneDrive\Documents\ArcGIS\Projects\TheBigOne_2025\data.parquet")

In [15]:
print(df.shape, '\n\n', df.columns)

(703185, 72)

 ['Height_M', 'fclass', 'name', 'type', 'Height_Flr', 'DEVELOPMENT_TYPE', 'NONRESIDENTIAL_SUBTYPE', 'CONSTRUCTION_YEAR', 'Building_Area_M2', 'ADDRESS', 'DEVELOPMENT_SUBTYPE', 'Perimeter', 'SQM_FTPRNT', 'NUM_RES', 'BUILDING_U', 'BLDG_NAME', 'BLDGCLASS_', 'BLDGTYPE', 'BLDGSUBTYP', 'PRIMARYUSE', 'SECONDARYU', 'POPULATION', 'AM_DEPT', 'STRUCTURAL', 'STRUCTUR00', 'YearBuilt', 'Address_1', 'R_or_C', 'Subtype', 'Full_Street_Address', 'MANUAL_CLASS_CODE', 'YEAR_BUILT', 'STOREYS', 'CONSTRUCTION_CODE', 'MANUAL_CLASS_DESCRIPTION', 'ACTUAL_USE_CODE', 'ACTUAL_USE_DESCRIPTION', 'FOUNDATION_TYPE', 'CARPORTS', 'ZONING', 'General_Occupancy_Class', 'Specific_Occupancy_Class', 'Construction_Typology', 'TOTAL_FINISHED_AREA_SQFT', 'Shape_Length_1', 'Shape_Area_1', 'Class', 'YEAR_BUILT_1', 'STOREYS_1', 'PARKING_UNDERGROUND_STALLS', 'GROSS_BUILDING_AREA', 'Total_Building_Units', 'HEATING_TYPE', 'ELEVATOR_FLAG', 'CONSTRUCTION_TYPE_CODE', 'ZONING_1', 'FEATURE_AREA_SQM', 'FEATURE_PATH_LENGTH_M', 'ACTUAL_USE_CODE_1', 'ACTUAL_USE_DESCRIPTION_1', 'NEIGHBOURHOOD', 'MANUAL_CLASS_CODE_1', 'MANUAL_CLASS_DESCRIPTION_1', 'ADDRESS_COUNT', 'POSTAL_CODE', 'Full_Street_Address_1', 'General_Occupancy_Class_1', 'Specific_Occupancy_Class_1', 'Construction_Typology_1', 'Shape_Length', 'Shape_Area', 'Permanent_ID']

In [16]:
df.describe()

shape: (9, 73)
┌────────────┬──────────┬──────────┬─────────────┬───┬───────────────────┬──────────────┬──────────────┬───────────────┐
│ statistic  ┆ Height_M ┆ fclass   ┆ name        ┆ … ┆ Construction_Typo ┆ Shape_Length ┆ Shape_Area   ┆ Permanent_ID  │
│ ---        ┆ ---      ┆ ---      ┆ ---         ┆   ┆ logy_1            ┆ ---          ┆ ---          ┆ ---           │
│ str        ┆ f64      ┆ str      ┆ str         ┆   ┆ ---               ┆ f64          ┆ f64          ┆ f64           │
│            ┆          ┆          ┆             ┆   ┆ f64               ┆              ┆              ┆               │
╞════════════╪══════════╪══════════╪═════════════╪═══╪═══════════════════╪══════════════╪══════════════╪═══════════════╡
│ count      ┆ 178287.0 ┆ 329381   ┆ 329381      ┆ … ┆ 0.0               ┆ 703185.0     ┆ 703185.0     ┆ 703185.0      │
│ null_count ┆ 524898.0 ┆ 373804   ┆ 373804      ┆ … ┆ 703185.0          ┆ 0.0          ┆ 0.0          ┆ 0.0           │
│ mean       ┆ 7.130547 ┆ null     ┆ null        ┆ … ┆ null              ┆ 98.917458    ┆ 1179.63946   ┆ 351593.0      │
│ std        ┆ 3.64762  ┆ null     ┆ null        ┆ … ┆ null              ┆ 164.353805   ┆ 40004.230917 ┆ 202992.168858 │
│ min        ┆ -0.13    ┆ 0        ┆             ┆ … ┆ null              ┆ 0.0          ┆ 0.0          ┆ 1.0           │
│ 25%        ┆ 5.051146 ┆ null     ┆ null        ┆ … ┆ null              ┆ 55.335164    ┆ 177.862653   ┆ 175797.0      │
│ 50%        ┆ 7.27     ┆ null     ┆ null        ┆ … ┆ null              ┆ 82.732855    ┆ 374.919742   ┆ 351593.0      │
│ 75%        ┆ 9.16     ┆ null     ┆ null        ┆ … ┆ null              ┆ 104.718722   ┆ 552.98138    ┆ 527389.0      │
│ max        ┆ 164.46   ┆ building ┆ 大統華 T&T  ┆ … ┆ null              ┆ 35455.556898 ┆ 2.6705e7     ┆ 703185.0      │
│            ┆          ┆          ┆ Supermarket ┆   ┆                   ┆              ┆              ┆               │
└────────────┴──────────┴──────────┴─────────────┴───┴───────────────────┴──────────────┴──────────────┴───────────────┘

In [17]:
#the HAZUS fields (first three listed) were attempts in arcgis pro - software too slow / process to arduous
df = df.drop("General_Occupancy_Class", "Specific_Occupancy_Class", "Construction_Typology", "Shape_Length_1", "Shape_Area_1", "Class" )

#### Dropping 100% null columns

In [18]:
null_analysis = pl.DataFrame({
    'column': df.columns,
    'null_count': df.null_count().row(0),
}).with_columns(
    null_pct = (pl.col('null_count') / len(df) * 100).round(2)
).sort('null_pct', descending=True)

with pl.Config(tbl_rows=-1):
    print(null_analysis)

shape: (66, 3)
┌────────────────────────────┬────────────┬──────────┐
│ column                     ┆ null_count ┆ null_pct │
│ ---                        ┆ ---        ┆ ---      │
│ str                        ┆ i64        ┆ f64      │
╞════════════════════════════╪════════════╪══════════╡
│ YEAR_BUILT_1               ┆ 703185     ┆ 100.0    │
│ STOREYS_1                  ┆ 703185     ┆ 100.0    │
│ PARKING_UNDERGROUND_STALLS ┆ 703185     ┆ 100.0    │
│ GROSS_BUILDING_AREA        ┆ 703185     ┆ 100.0    │
│ Total_Building_Units       ┆ 703185     ┆ 100.0    │
│ HEATING_TYPE               ┆ 703185     ┆ 100.0    │
│ ELEVATOR_FLAG              ┆ 703185     ┆ 100.0    │
│ CONSTRUCTION_TYPE_CODE     ┆ 703185     ┆ 100.0    │
│ ZONING_1                   ┆ 703185     ┆ 100.0    │
│ FEATURE_AREA_SQM           ┆ 703185     ┆ 100.0    │
│ FEATURE_PATH_LENGTH_M      ┆ 703185     ┆ 100.0    │
│ ACTUAL_USE_CODE_1          ┆ 703185     ┆ 100.0    │
│ ACTUAL_USE_DESCRIPTION_1   ┆ 703185     ┆ 100.0    │
│ NEIGHBOURHOOD              ┆ 703185     ┆ 100.0    │
│ MANUAL_CLASS_CODE_1        ┆ 703185     ┆ 100.0    │
│ MANUAL_CLASS_DESCRIPTION_1 ┆ 703185     ┆ 100.0    │
│ ADDRESS_COUNT              ┆ 703185     ┆ 100.0    │
│ POSTAL_CODE                ┆ 703185     ┆ 100.0    │
│ Full_Street_Address_1      ┆ 703185     ┆ 100.0    │
│ General_Occupancy_Class_1  ┆ 703185     ┆ 100.0    │
│ Specific_Occupancy_Class_1 ┆ 703185     ┆ 100.0    │
│ Construction_Typology_1    ┆ 703185     ┆ 100.0    │
│ YearBuilt                  ┆ 702025     ┆ 99.84    │
│ Address_1                  ┆ 702025     ┆ 99.84    │
│ R_or_C                     ┆ 702025     ┆ 99.84    │
│ Subtype                    ┆ 702025     ┆ 99.84    │
│ NUM_RES                    ┆ 693899     ┆ 98.68    │
│ Building_Area_M2           ┆ 692996     ┆ 98.55    │
│ BLDG_NAME                  ┆ 679912     ┆ 96.69    │
│ BLDGCLASS_                 ┆ 679912     ┆ 96.69    │
│ BLDGTYPE                   ┆ 679912     ┆ 96.69    │
│ BLDGSUBTYP                 ┆ 679912     ┆ 96.69    │
│ PRIMARYUSE                 ┆ 679912     ┆ 96.69    │
│ SECONDARYU                 ┆ 679912     ┆ 96.69    │
│ POPULATION                 ┆ 679912     ┆ 96.69    │
│ AM_DEPT                    ┆ 679912     ┆ 96.69    │
│ STRUCTURAL                 ┆ 679912     ┆ 96.69    │
│ STRUCTUR00                 ┆ 679912     ┆ 96.69    │
│ DEVELOPMENT_SUBTYPE        ┆ 672488     ┆ 95.63    │
│ CONSTRUCTION_CODE          ┆ 665437     ┆ 94.63    │
│ ADDRESS                    ┆ 663202     ┆ 94.31    │
│ BUILDING_U                 ┆ 648397     ┆ 92.21    │
│ CARPORTS                   ┆ 621058     ┆ 88.32    │
│ Height_Flr                 ┆ 615838     ┆ 87.58    │
│ DEVELOPMENT_TYPE           ┆ 567103     ┆ 80.65    │
│ NONRESIDENTIAL_SUBTYPE     ┆ 567106     ┆ 80.65    │
│ CONSTRUCTION_YEAR          ┆ 534544     ┆ 76.02    │
│ Height_M                   ┆ 524898     ┆ 74.65    │
│ fclass                     ┆ 373804     ┆ 53.16    │
│ name                       ┆ 373804     ┆ 53.16    │
│ type                       ┆ 373804     ┆ 53.16    │
│ ZONING                     ┆ 157229     ┆ 22.36    │
│ FOUNDATION_TYPE            ┆ 152267     ┆ 21.65    │
│ MANUAL_CLASS_DESCRIPTION   ┆ 112984     ┆ 16.07    │
│ ACTUAL_USE_CODE            ┆ 109945     ┆ 15.64    │
│ ACTUAL_USE_DESCRIPTION     ┆ 109945     ┆ 15.64    │
│ TOTAL_FINISHED_AREA_SQFT   ┆ 109945     ┆ 15.64    │
│ STOREYS                    ┆ 88235      ┆ 12.55    │
│ YEAR_BUILT                 ┆ 84533      ┆ 12.02    │
│ MANUAL_CLASS_CODE          ┆ 83201      ┆ 11.83    │
│ Full_Street_Address        ┆ 75301      ┆ 10.71    │
│ SQM_FTPRNT                 ┆ 68348      ┆ 9.72     │
│ Perimeter                  ┆ 34644      ┆ 4.93     │
│ Shape_Length               ┆ 0          ┆ 0.0      │
│ Shape_Area                 ┆ 0          ┆ 0.0      │
│ Permanent_ID               ┆ 0          ┆ 0.0      │
└────────────────────────────┴────────────┴──────────┘

In [19]:
#list of columns with 100% nulls
cols_to_drop = null_analysis.filter(pl.col('null_pct') == 100.0)['column'].to_list()

#drop them
df = df.drop(cols_to_drop)

print(f"Dropped {len(cols_to_drop)} columns")

Dropped 22 columns

In [20]:
null_analysis = pl.DataFrame({
    'column': df.columns,
    'null_count': df.null_count().row(0),
}).with_columns(
    null_pct = (pl.col('null_count') / len(df) * 100).round(2)
).sort('null_pct', descending=True)

with pl.Config(tbl_rows=-1):
    print(null_analysis)

shape: (44, 3)
┌──────────────────────────┬────────────┬──────────┐
│ column                   ┆ null_count ┆ null_pct │
│ ---                      ┆ ---        ┆ ---      │
│ str                      ┆ i64        ┆ f64      │
╞══════════════════════════╪════════════╪══════════╡
│ YearBuilt                ┆ 702025     ┆ 99.84    │
│ Address_1                ┆ 702025     ┆ 99.84    │
│ R_or_C                   ┆ 702025     ┆ 99.84    │
│ Subtype                  ┆ 702025     ┆ 99.84    │
│ NUM_RES                  ┆ 693899     ┆ 98.68    │
│ Building_Area_M2         ┆ 692996     ┆ 98.55    │
│ BLDG_NAME                ┆ 679912     ┆ 96.69    │
│ BLDGCLASS_               ┆ 679912     ┆ 96.69    │
│ BLDGTYPE                 ┆ 679912     ┆ 96.69    │
│ BLDGSUBTYP               ┆ 679912     ┆ 96.69    │
│ PRIMARYUSE               ┆ 679912     ┆ 96.69    │
│ SECONDARYU               ┆ 679912     ┆ 96.69    │
│ POPULATION               ┆ 679912     ┆ 96.69    │
│ AM_DEPT                  ┆ 679912     ┆ 96.69    │
│ STRUCTURAL               ┆ 679912     ┆ 96.69    │
│ STRUCTUR00               ┆ 679912     ┆ 96.69    │
│ DEVELOPMENT_SUBTYPE      ┆ 672488     ┆ 95.63    │
│ CONSTRUCTION_CODE        ┆ 665437     ┆ 94.63    │
│ ADDRESS                  ┆ 663202     ┆ 94.31    │
│ BUILDING_U               ┆ 648397     ┆ 92.21    │
│ CARPORTS                 ┆ 621058     ┆ 88.32    │
│ Height_Flr               ┆ 615838     ┆ 87.58    │
│ DEVELOPMENT_TYPE         ┆ 567103     ┆ 80.65    │
│ NONRESIDENTIAL_SUBTYPE   ┆ 567106     ┆ 80.65    │
│ CONSTRUCTION_YEAR        ┆ 534544     ┆ 76.02    │
│ Height_M                 ┆ 524898     ┆ 74.65    │
│ fclass                   ┆ 373804     ┆ 53.16    │
│ name                     ┆ 373804     ┆ 53.16    │
│ type                     ┆ 373804     ┆ 53.16    │
│ ZONING                   ┆ 157229     ┆ 22.36    │
│ FOUNDATION_TYPE          ┆ 152267     ┆ 21.65    │
│ MANUAL_CLASS_DESCRIPTION ┆ 112984     ┆ 16.07    │
│ ACTUAL_USE_CODE          ┆ 109945     ┆ 15.64    │
│ ACTUAL_USE_DESCRIPTION   ┆ 109945     ┆ 15.64    │
│ TOTAL_FINISHED_AREA_SQFT ┆ 109945     ┆ 15.64    │
│ STOREYS                  ┆ 88235      ┆ 12.55    │
│ YEAR_BUILT               ┆ 84533      ┆ 12.02    │
│ MANUAL_CLASS_CODE        ┆ 83201      ┆ 11.83    │
│ Full_Street_Address      ┆ 75301      ┆ 10.71    │
│ SQM_FTPRNT               ┆ 68348      ┆ 9.72     │
│ Perimeter                ┆ 34644      ┆ 4.93     │
│ Shape_Length             ┆ 0          ┆ 0.0      │
│ Shape_Area               ┆ 0          ┆ 0.0      │
│ Permanent_ID             ┆ 0          ┆ 0.0      │
└──────────────────────────┴────────────┴──────────┘

---


### Let's explore the unique values of each field to get a better understanding of what we are working with


---

In [21]:
#shows all unique values (and their count) for each column. This is to see which fields are similar and can be combined

def vc(df, *columns):
    """Value counts - shows ALL rows for each column"""
    results = {}
    
    for col in columns:
        vc = df[col].value_counts().sort("count", descending=True)
        results[col] = vc
        
        print(f"\n{'='*60}\n {col} ({len(vc)} unique values)\n{'='*60}")
        
        # Show all rows for this column
        with pl.Config(tbl_rows=-1):
            print(vc)
    
    return results

In [22]:
counts = vc(df, "fclass", "type", "DEVELOPMENT_TYPE", "NONRESIDENTIAL_SUBTYPE", "DEVELOPMENT_SUBTYPE", "BUILDING_U", "BLDGCLASS_", "BLDGTYPE", "BLDGSUBTYP", "PRIMARYUSE", "SECONDARYU", "R_or_C","Subtype", "MANUAL_CLASS_DESCRIPTION", "ACTUAL_USE_DESCRIPTION", 	"AM_DEPT",	"STRUCTURAL", "STRUCTUR00", "CONSTRUCTION_CODE", "FOUNDATION_TYPE", "ZONING", "CARPORTS")

============================================================
 fclass (12 unique values)
============================================================
shape: (12, 2)
┌───────────────────────┬────────┐
│ fclass                ┆ count  │
│ ---                   ┆ ---    │
│ str                   ┆ u32    │
╞═══════════════════════╪════════╡
│ null                  ┆ 373804 │
│ building              ┆ 292419 │
│ RESIDENTIAL           ┆ 21401  │
│ 0                     ┆ 13689  │
│ COMMERCIAL            ┆ 487    │
│ INDUSTRIAL            ┆ 457    │
│ RESIDENTIAL AUXILIARY ┆ 321    │
│ AUXILIARY             ┆ 229    │
│ INSTITUTIONAL         ┆ 154    │
│ RECREATION            ┆ 130    │
│ MIXED USE             ┆ 64     │
│ RELIGIOUS             ┆ 30     │
└───────────────────────┴────────┘

============================================================
 type (141 unique values)
============================================================
shape: (141, 2)
┌─────────────────────┬────────┐
│ type                ┆ count  │
│ ---                 ┆ ---    │
│ str                 ┆ u32    │
╞═════════════════════╪════════╡
│ null                ┆ 373804 │
│                     ┆ 189508 │
│ house               ┆ 44870  │
│ detached            ┆ 26494  │
│ SINGLE FAMILY       ┆ 20144  │
│ 0                   ┆ 13689  │
│ residential         ┆ 4904   │
│ apartments          ┆ 4380   │
│ garage              ┆ 4264   │
│ shed                ┆ 4080   │
│ terrace             ┆ 3846   │
│ retail              ┆ 1989   │
│ industrial          ┆ 1425   │
│ MULTI FAMILY        ┆ 1251   │
│ roof                ┆ 1043   │
│ commercial          ┆ 969    │
│ semidetached_house  ┆ 824    │
│ school              ┆ 668    │
│ COMMERCIAL BUILDING ┆ 490    │
│ INDUSTRIAL BUILDING ┆ 457    │
│ greenhouse          ┆ 449    │
│ office              ┆ 332    │
│ CARPORT             ┆ 265    │
│ church              ┆ 214    │
│ static_caravan      ┆ 191    │
│ service             ┆ 186    │
│ PARK BUILDING       ┆ 128    │
│ barn                ┆ 117    │
│ warehouse           ┆ 116    │
│ farm_auxiliary      ┆ 114    │
│ SCHOOL              ┆ 110    │
│ SKI                 ┆ 100    │
│ hotel               ┆ 100    │
│ hangar              ┆ 95     │
│ houseboat           ┆ 84     │
│ cabin               ┆ 82     │
│ carport             ┆ 80     │
│ construction        ┆ 77     │
│ hospital            ┆ 77     │
│ patio               ┆ 70     │
│ MIXED USE           ┆ 65     │
│ bridge              ┆ 62     │
│ AMENITY             ┆ 58     │
│ boathouse           ┆ 56     │
│ UTILITY BUILDING    ┆ 56     │
│ townhouse           ┆ 54     │
│ civic               ┆ 48     │
│ mixed_use           ┆ 45     │
│ train_station       ┆ 43     │
│ garages             ┆ 37     │
│ parking             ┆ 37     │
│ public              ┆ 30     │
│ container           ┆ 29     │
│ fire_station        ┆ 28     │
│ CHURCH              ┆ 27     │
│ stable              ┆ 25     │
│ university          ┆ 23     │
│ TRANSPORT BUILDING  ┆ 22     │
│ no                  ┆ 21     │
│ college             ┆ 19     │
│ FARM BUILDING       ┆ 19     │
│ FIRE                ┆ 17     │
│ government          ┆ 15     │
│ farm                ┆ 14     │
│ hut                 ┆ 14     │
│ GOLF                ┆ 13     │
│ RECREATION FACILITY ┆ 12     │
│ kindergarten        ┆ 11     │
│ transportation      ┆ 11     │
│ storage_tank        ┆ 11     │
│ ruins               ┆ 9      │
│ temple              ┆ 8      │
│ grandstand          ┆ 8      │
│ COMMUNITY CENTRE    ┆ 7      │
│ theatre             ┆ 7      │
│ OPERATIONS CENTRE   ┆ 6      │
│ tent                ┆ 6      │
│ toilets             ┆ 6      │
│ OTHER               ┆ 5      │
│ tower               ┆ 4      │
│ mosque              ┆ 4      │
│ motel               ┆ 4      │
│ stadium             ┆ 4      │
│ demolished          ┆ 4      │
│ livestock           ┆ 4      │
│ museum              ┆ 3      │
│ silo                ┆ 3      │
│ synagogue           ┆ 3      │
│ factory             ┆ 3      │
│ SHED                ┆ 3      │
│ gazebo              ┆ 3      │
│ N/A                 ┆ 3      │
│ sports_centre       ┆ 3      │
│ outbuilding         ┆ 3      │
│ kiosk               ┆ 2      │
│ historic            ┆ 2      │
│ riding_hall         ┆ 2      │
│ sports_hall         ┆ 2      │
│ restaurant          ┆ 2      │
│ STABLES             ┆ 2      │
│ LIBRARY             ┆ 2      │
│ military            ┆ 2      │
│ demountable         ┆ 2      │
│ guardhouse          ┆ 2      │
│ religious           ┆ 2      │
│ bank                ┆ 2      │
│ library             ┆ 2      │
│ dormitory           ┆ 2      │
│ RECYCLING BUILDING  ┆ 2      │
│ gym                 ┆ 2      │
│ ger                 ┆ 2      │
│ bunker              ┆ 1      │
│ yes;roof            ┆ 1      │
│ bungalow            ┆ 1      │
│ recreational        ┆ 1      │
│ MOSQUE              ┆ 1      │
│ ANIMAL SHELTER      ┆ 1      │
│ POLICE              ┆ 1      │
│ gatehouse           ┆ 1      │
│ post_office         ┆ 1      │
│ corridor            ┆ 1      │
│ cinema              ┆ 1      │
│ picnic_shelter      ┆ 1      │
│ MUSEUM              ┆ 1      │
│ conservatory        ┆ 1      │
│ bandstand           ┆ 1      │
│ MUNICIPAL HALL      ┆ 1      │
│ mall                ┆ 1      │
│ pumping_station     ┆ 1      │
│ nursing_home        ┆ 1      │
│ treehouse           ┆ 1      │
│ place_of_worship    ┆ 1      │
│ cathedral           ┆ 1      │
│ petrol_station      ┆ 1      │
│ yes;church          ┆ 1      │
│ HOSPITAL            ┆ 1      │
│ funeral_hall        ┆ 1      │
│ community_hall      ┆ 1      │
│ arbor               ┆ 1      │
│ chapel              ┆ 1      │
│ allotment_house     ┆ 1      │
└─────────────────────┴────────┘

============================================================
 DEVELOPMENT_TYPE (3 unique values)
============================================================
shape: (3, 2)
┌──────────────────┬────────┐
│ DEVELOPMENT_TYPE ┆ count  │
│ ---              ┆ ---    │
│ str              ┆ u32    │
╞══════════════════╪════════╡
│ null             ┆ 567103 │
│ Residential      ┆ 128482 │
│ Nonresidential   ┆ 7600   │
└──────────────────┴────────┘

============================================================
 NONRESIDENTIAL_SUBTYPE (30 unique values)
============================================================
shape: (30, 2)
┌─────────────────────────┬────────┐
│ NONRESIDENTIAL_SUBTYPE  ┆ count  │
│ ---                     ┆ ---    │
│ str                     ┆ u32    │
╞═════════════════════════╪════════╡
│ null                    ┆ 567106 │
│ Not Applicable          ┆ 128476 │
│ Farm Related            ┆ 2308   │
│ Warehouse               ┆ 1593   │
│ Retail                  ┆ 1278   │
│ Manufacturing           ┆ 434    │
│ Office                  ┆ 262    │
│ Automotive Services     ┆ 231    │
│ Education               ┆ 225    │
│ Recreation Related      ┆ 221    │
│ Greenhouse              ┆ 204    │
│ Assembly                ┆ 152    │
│ Truck Parking           ┆ 148    │
│ Recreational Club House ┆ 94     │
│ Rail Yard               ┆ 76     │
│ Utilities               ┆ 72     │
│ Outdoor Metal Storage   ┆ 59     │
│ Lumber Yard             ┆ 58     │
│ Govt Related            ┆ 51     │
│ Automotive Storage      ┆ 33     │
│ Health Related          ┆ 26     │
│ Hotel                   ┆ 18     │
│ Fire Station            ┆ 18     │
│ Commercial (Non-Office) ┆ 12     │
│ Transit Station         ┆ 8      │
│ Library                 ┆ 7      │
│ Transit Parking         ┆ 5      │
│ Shopping Centre         ┆ 4      │
│ Gravel Storage          ┆ 3      │
│ Post Office             ┆ 3      │
└─────────────────────────┴────────┘

============================================================
 DEVELOPMENT_SUBTYPE (19 unique values)
============================================================
shape: (19, 2)
┌─────────────────────────┬────────┐
│ DEVELOPMENT_SUBTYPE     ┆ count  │
│ ---                     ┆ ---    │
│ str                     ┆ u32    │
╞═════════════════════════╪════════╡
│ null                    ┆ 672488 │
│ Secondary Suite         ┆ 28912  │
│ One Family Dwelling     ┆ 745    │
│ Industrial              ┆ 440    │
│ Townhouse               ┆ 163    │
│ Farm Related            ┆ 135    │
│ Commercial (Non-Office) ┆ 83     │
│ Coach House             ┆ 59     │
│ Mobile House            ┆ 30     │
│ Two Family Dwelling     ┆ 26     │
│ Low Rise Apartment      ┆ 24     │
│ Row House               ┆ 16     │
│ Office                  ┆ 13     │
│ Govt Related            ┆ 13     │
│ Education               ┆ 12     │
│ Recreational Club House ┆ 12     │
│ Assembly                ┆ 6      │
│ High Rise Apartment     ┆ 5      │
│ Health Related          ┆ 3      │
└─────────────────────────┴────────┘

============================================================
 BUILDING_U (38 unique values)
============================================================
shape: (38, 2)
┌────────────────────────────────┬────────┐
│ BUILDING_U                     ┆ count  │
│ ---                            ┆ ---    │
│ str                            ┆ u32    │
╞════════════════════════════════╪════════╡
│ null                           ┆ 648397 │
│ Residential                    ┆ 50034  │
│ Industrial                     ┆ 1814   │
│ Agriculture                    ┆ 926    │
│ Commercial                     ┆ 623    │
│                                ┆ 381    │
│ Parks and Recreation           ┆ 365    │
│ Institutional and Public       ┆ 290    │
│ Public School                  ┆ 266    │
│ Emergency                      ┆ 15     │
│ Transportation                 ┆ 13     │
│ Residential and Commercial     ┆ 7      │
│ Parking Lot                    ┆ 6      │
│ Civic Amenity                  ┆ 5      │
│ Commercial-Industrial          ┆ 4      │
│ Commercial-Strata              ┆ 4      │
│ Institutional                  ┆ 4      │
│ Residental                     ┆ 3      │
│ Truck Gardening                ┆ 3      │
│ Reidential                     ┆ 2      │
│ Commercial-Institutional       ┆ 2      │
│ RESIDENTIAL                    ┆ 2      │
│ <ArcGIS Type="Editing"><ArrayO ┆ 2      │
│ 000-008-530                    ┆ 2      │
│ 000-081-801                    ┆ 2      │
│ 000-004-589                    ┆ 1      │
│ Commetcial                     ┆ 1      │
│ Reisdential                    ┆ 1      │
│ Recreation                     ┆ 1      │
│ YhCeyB5B3Pl+EtrLVEE=</Bytes><S ┆ 1      │
│ Non-market Rental Residential  ┆ 1      │
│ Site Option A                  ┆ 1      │
│ 000-085-932                    ┆ 1      │
│ Resiential                     ┆ 1      │
│ Site Option B                  ┆ 1      │
│ Commericial-Industrial         ┆ 1      │
│ 000-000-837                    ┆ 1      │
│ +X4S2stUQRAtsp2HyB5BTDeJmdvLVE ┆ 1      │
└────────────────────────────────┴────────┘

============================================================
 BLDGCLASS_ (10 unique values)
============================================================
shape: (10, 2)
┌───────────────────────┬────────┐
│ BLDGCLASS_            ┆ count  │
│ ---                   ┆ ---    │
│ str                   ┆ u32    │
╞═══════════════════════╪════════╡
│ null                  ┆ 679912 │
│ RESIDENTIAL           ┆ 21401  │
│ COMMERCIAL            ┆ 487    │
│ INDUSTRIAL            ┆ 457    │
│ RESIDENTIAL AUXILIARY ┆ 321    │
│ AUXILIARY             ┆ 229    │
│ INSTITUTIONAL         ┆ 154    │
│ RECREATION            ┆ 130    │
│ MIXED USE             ┆ 64     │
│ RELIGIOUS             ┆ 30     │
└───────────────────────┴────────┘

============================================================
 BLDGTYPE (33 unique values)
============================================================
shape: (33, 2)
┌─────────────────────┬────────┐
│ BLDGTYPE            ┆ count  │
│ ---                 ┆ ---    │
│ str                 ┆ u32    │
╞═════════════════════╪════════╡
│ null                ┆ 679912 │
│ SINGLE FAMILY       ┆ 20144  │
│ MULTI FAMILY        ┆ 1251   │
│ COMMERCIAL BUILDING ┆ 490    │
│ INDUSTRIAL BUILDING ┆ 457    │
│ CARPORT             ┆ 265    │
│ PARK BUILDING       ┆ 128    │
│ SCHOOL              ┆ 110    │
│ SKI                 ┆ 100    │
│ MIXED USE           ┆ 65     │
│ AMENITY             ┆ 58     │
│ UTILITY BUILDING    ┆ 56     │
│ CHURCH              ┆ 27     │
│ TRANSPORT BUILDING  ┆ 22     │
│ FARM BUILDING       ┆ 19     │
│ FIRE                ┆ 17     │
│ GOLF                ┆ 13     │
│ RECREATION FACILITY ┆ 12     │
│ COMMUNITY CENTRE    ┆ 7      │
│ OPERATIONS CENTRE   ┆ 6      │
│ OTHER               ┆ 5      │
│ SHED                ┆ 3      │
│                     ┆ 3      │
│ N/A                 ┆ 3      │
│ LIBRARY             ┆ 2      │
│ RECYCLING BUILDING  ┆ 2      │
│ STABLES             ┆ 2      │
│ MUSEUM              ┆ 1      │
│ HOSPITAL            ┆ 1      │
│ MUNICIPAL HALL      ┆ 1      │
│ POLICE              ┆ 1      │
│ ANIMAL SHELTER      ┆ 1      │
│ MOSQUE              ┆ 1      │
└─────────────────────┴────────┘

============================================================
 BLDGSUBTYP (62 unique values)
============================================================
shape: (62, 2)
┌─────────────────────────────┬────────┐
│ BLDGSUBTYP                  ┆ count  │
│ ---                         ┆ ---    │
│ str                         ┆ u32    │
╞═════════════════════════════╪════════╡
│ null                        ┆ 679912 │
│ DETACHED                    ┆ 20074  │
│ N/A                         ┆ 1328   │
│ TOWNHOUSE                   ┆ 1009   │
│ LOW RISE APARTMENT          ┆ 168    │
│ CABIN                       ┆ 61     │
│ ADMINISTRATION              ┆ 53     │
│ ELEMENTARY                  ┆ 44     │
│ MIXED USE - MULTI FAMILY    ┆ 42     │
│ STORAGE                     ┆ 38     │
│ OPERATIONAL                 ┆ 31     │
│ COACH                       ┆ 30     │
│ POST SECONDARY              ┆ 29     │
│ WASHROOM                    ┆ 29     │
│ DUPLEX                      ┆ 24     │
│                             ┆ 24     │
│ HIGH RISE APARTMENT         ┆ 23     │
│ PRIVATE                     ┆ 19     │
│ MIXED USE - SINGLE FAMILY   ┆ 17     │
│ MAINTENANCE                 ┆ 17     │
│ SECONDARY                   ┆ 15     │
│ WATER TANK                  ┆ 15     │
│ ROAD MAINTENANCE            ┆ 14     │
│ OTHER                       ┆ 12     │
│ WATER TREATMENT PLANT       ┆ 12     │
│ SUBSTATION                  ┆ 12     │
│ WATER PUMP STATION          ┆ 11     │
│ PICNIC SHELTER              ┆ 10     │
│ BARN                        ┆ 10     │
│ FOURPLEX                    ┆ 8      │
│ CARETAKER                   ┆ 6      │
│ DAYCARE CENTRE              ┆ 6      │
│ HOUSEBOAT                   ┆ 6      │
│ BUS SHELTER                 ┆ 6      │
│ FIRE STATION                ┆ 5      │
│ CONCESSION                  ┆ 5      │
│ GENERAL                     ┆ 5      │
│ FIRE TRAINING CENTRE        ┆ 5      │
│ BATTERS CAGE                ┆ 4      │
│ CLUBHOUSE                   ┆ 4      │
│ GAZEBO                      ┆ 3      │
│ SHELTER                     ┆ 3      │
│ TURF CENTRE                 ┆ 3      │
│ WORKSHOP                    ┆ 3      │
│ INTERPRETIVE CENTRE         ┆ 3      │
│ PUBLIC                      ┆ 3      │
│ SEARCH AND RESCUE STATION   ┆ 3      │
│ TRIPLEX                     ┆ 3      │
│ KIOSK                       ┆ 2      │
│ NURSERY                     ┆ 2      │
│ SHOP                        ┆ 2      │
│ BUS WASHROOM                ┆ 2      │
│ YOUTH                       ┆ 1      │
│ SEWAGE TREATMENT PLANT      ┆ 1      │
│ ENERGY RECOVERY FACILITY    ┆ 1      │
│ SCOUT SHELTER               ┆ 1      │
│ GUEST SERVICES              ┆ 1      │
│ GARAGE                      ┆ 1      │
│ POLICE STATION              ┆ 1      │
│ GATEHOUSE                   ┆ 1      │
│ WATER DISTRIBUTION FACILITY ┆ 1      │
│ GVRD TRANSFER STATION       ┆ 1      │
└─────────────────────────────┴────────┘

============================================================
 PRIMARYUSE (8 unique values)
============================================================
shape: (8, 2)
┌──────────────────┬────────┐
│ PRIMARYUSE       ┆ count  │
│ ---              ┆ ---    │
│ str              ┆ u32    │
╞══════════════════╪════════╡
│ null             ┆ 679912 │
│ N/A              ┆ 23137  │
│                  ┆ 65     │
│ MULTI FAMILY     ┆ 42     │
│ COMMERCIAL       ┆ 19     │
│ SINGLE FAMILY    ┆ 6      │
│ COMMUNITY CENTRE ┆ 3      │
│ LIBRARY          ┆ 1      │
└──────────────────┴────────┘

============================================================
 SECONDARYU (8 unique values)
============================================================
shape: (8, 2)
┌───────────────┬────────┐
│ SECONDARYU    ┆ count  │
│ ---           ┆ ---    │
│ str           ┆ u32    │
╞═══════════════╪════════╡
│ null          ┆ 679912 │
│ N/A           ┆ 23140  │
│               ┆ 71     │
│ COMMERCIAL    ┆ 45     │
│ SINGLE FAMILY ┆ 12     │
│ MULTI FAMILY  ┆ 2      │
│ LIBRARY       ┆ 2      │
│ SCHOOL        ┆ 1      │
└───────────────┴────────┘

============================================================
 R_or_C (2 unique values)
============================================================
shape: (2, 2)
┌────────────┬────────┐
│ R_or_C     ┆ count  │
│ ---        ┆ ---    │
│ str        ┆ u32    │
╞════════════╪════════╡
│ null       ┆ 702025 │
│ Commercial ┆ 1160   │
└────────────┴────────┘

============================================================
 Subtype (2 unique values)
============================================================
shape: (2, 2)
┌─────────┬────────┐
│ Subtype ┆ count  │
│ ---     ┆ ---    │
│ str     ┆ u32    │
╞═════════╪════════╡
│ null    ┆ 702025 │
│ Office  ┆ 1160   │
└─────────┴────────┘

============================================================
 MANUAL_CLASS_DESCRIPTION (185 unique values)
============================================================
shape: (185, 2)
┌─────────────────────────────────┬────────┐
│ MANUAL_CLASS_DESCRIPTION        ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ null                            ┆ 112984 │
│ 1 STY SFD - After 1960 - Stand… ┆ 109685 │
│ 2 STY SFD - After 1990 Semi-Cu… ┆ 85520  │
│ 1 STY SFD - After 1930 - Stand… ┆ 60976  │
│ 2 STY SFD - After 1990 - Stand… ┆ 42215  │
│ 2 STY SFD - After 1990 - Custo… ┆ 40398  │
│ Strata Townhouse                ┆ 30159  │
│ 2 STY SFD - After 1930 - Semi-… ┆ 28641  │
│ 1 STY SFD - After 1930 - Semi-… ┆ 21777  │
│ 1 STY SFD - After 1990 - Stand… ┆ 21679  │
│ 2 STY SFD - After 1960 - Stand… ┆ 20479  │
│ 1 STY SFD - After 1990 - Semi-… ┆ 16389  │
│ 2 STY SFD - After 1930 - Custo… ┆ 12977  │
│ 1 STY SFD - After 1930 - Basic  ┆ 9159   │
│ 1.5 STY SFD - Before 1930 - Ba… ┆ 8571   │
│ 1 STY SFD - Before 1930 - Basi… ┆ 6825   │
│ 1.5 STY SFD - Before 1930 - St… ┆ 5485   │
│ 1.5 STY SFD - After 1930 - Sta… ┆ 5075   │
│ 2 STY SFD - Before 1930 - Stan… ┆ 4587   │
│ Strata Apartment - Frame        ┆ 4301   │
│ 2 STY SFD - After 1930 - Stand… ┆ 4279   │
│ 2 STY Duplex - After 1990 - St… ┆ 3865   │
│ Non-Manualized Structures       ┆ 3697   │
│ 2 STY SFD - Before 1930 - Basi… ┆ 3557   │
│ 2 STY Duplex - After 1990 - Se… ┆ 3469   │
│ 1 STY Duplex - After 1960 - St… ┆ 2900   │
│ 1.5 STY SFD - After 1930 - Bas… ┆ 2307   │
│ 1.5 STY SFD - After 1960 - Sta… ┆ 2187   │
│ Strata Apartment - Hi-Rise      ┆ 2009   │
│ 1 STY SFD - After 1990 - Custo… ┆ 1816   │
│ 1 STY SFD - After 1930 - Custo… ┆ 1800   │
│ 1.5 STY SFD - After 1930 - Sem… ┆ 1736   │
│ MH - Single Wide - Ave Q        ┆ 1698   │
│ 1 STY Duplex - After 1930 - St… ┆ 1364   │
│ 2 STY SFD - Before 1930 - Cust… ┆ 1351   │
│ 2 STY Duplex - After 1960 - St… ┆ 1082   │

## The output above shows vital information for how I will clean and combine columns

#### Fields useful for General and Specific Occupancy Class: 
- fclass - general
- type - mix of general and specific, may need to split into two columns
- DEVELOPMENT_TYPE - general, only has "Residential" and "Non-Residential"
- NONRESIDENTIAL_SUBTYPE - somewhat specific, but could give clues towards which general class it belongs
- DEVELOPMENT_SUBTYPE - specific, but could also give clues towards general class
- BUILDING_U - general
- BLDGCLASS_ - general, *** same as fclass! drop fclass
- BLDGTYPE - mix of general and specific 
- BLDGSUBTYP - specific
- PRIMARYUSE - general and specific
- R_or_C - general, only value is "Commercial"
- Subtype - specific, only value is "Office"
- MANUAL_CLASS_DESCRIPTION - needs to be split by -
- ACTUAL_USE_DESCRIPTION - specific
- AM-DEPT - drop
- ZONING - Maybe last resort? need to figure out codes

#### Fields useful for Construction Typology:
- STRUCTURAL - I believe these are hazus codes?
- STRUCTUR00 - Hazus
- CONSTRUCTION_CODE - need to find out what these mean
- FOUNDATION_TYPE
- Height_M + Height_Flr + STOREYS
- MANUAL_CLASS_DESCRIPTION - needs to be split by "-"
- CONSTRUCTION_YEAR + Year_Built + YEAR_BUILT
- Perimeter - drop
- SQM_FTPRNT + Shape_Area
- NUM_RES + POPULATION
- Building_Area_M2 + TOTAL_FINISHED_AREA_SQFT
- Carports?

#### Fields useful for Seismic Design 
- CONSTRUCTION_YEAR + Year_Built + YEAR_BUILT
- MANUAL_CLASS_DESCRIPTION - once the date is split into its own column

#### Other fields to combine: 
- name + BLDG_NAME
- ADDRESS + Address_1 + Full_Street_Address

In [23]:
df = df.drop(['fclass', 'Perimeter', 'AM_DEPT', 'SECONDARYU'])

In [24]:
#now that the unneccessary columns are dropped, I will make this a checkpoint

df.write_parquet('data_with_useful_columns.parquet')

In [25]:
df = pl.read_parquet('data_with_useful_columns.parquet')

## 2. CLEANING + UPDATING VALUES TO MAKE THEM COMBINABLE AND/OR HAZUS COMPATIBLE

---

### 1. Cleaning occupancy-related fields

---

- type_to_specific

- development_type (null Nonresidential, and rename)

- 'NONRESIDENTIAL_SUBTYPE_to_specific'

- 'DEVELOPMENT_SUBTYPE_to_specific'

- BUILDING_U_to_general
- BUILDING_U_to_specific

- BLDGCLASS_to_general

- BLDG_TYPE_to_specific

- BLDG_SUBTYP_to_specific

- PRIMARY_USE_to_specific (null COMMERCIAL)

Drop SECONDARYU

- R_or_C rename to Commercial

- Subtype rename to Offices

- ACTUAL_USE_DESCRIPTION_to_specific

- MANUAL_CLASS_TYPE > MC_age, MC_storeys, MC_subtype, MC_quality

'type' -> 'hazus_class' (will be dropped after imputation step) -> 'type_to_specific'

In [26]:
hazus_mapping = {
    # Residential - RES1 (Single-family)
    'RES1': ['house', 'detached', 'SINGLE FAMILY', 'semidetached_house',
             'bungalow', 'cabin', 'houseboat', 'residential'],

    # Residential - RES2 (Mobile Home)
    'RES2': ['static_caravan', 'demountable'],

    # Residential - RES3A-F (Multi-family)
    'RES3': ['apartments', 'terrace', 'townhouse', 'MULTI FAMILY'],

    # Residential - RES4 (Temporary Lodging)
    'RES4': ['hotel', 'motel', 'tent', 'ger'],

    # Residential - RES5 (Institutional Dormitory)
    'RES5': ['dormitory'],

    # Residential - RES6 (Nursing Home)
    'RES6': ['nursing_home'],

    # Commercial - COM1 (Retail)
    'COM1': ['retail', 'mall', 'kiosk', 'restaurant'],

    # Commercial - COM2 (Wholesale)
    'COM2': ['warehouse'],

    # Commercial - COM3 (Personal/Repair Services)
    'COM3': ['service', 'petrol_station', 'toilets'],

    # Commercial - COM4 (Business/Professional)
    'COM4': ['office', 'COMMERCIAL BUILDING', 'commercial', 'mixed_use',
             'MIXED USE', 'business', 'guardhouse', 'gatehouse', 'funeral_hall'],

    # Commercial - COM5 (Banks)
    'COM5': ['bank'],

    # Commercial - COM6 (Hospital)
    'COM6': ['hospital', 'HOSPITAL'],

    # Commercial - COM7 (Medical Office/Clinic)
    'COM7': [],

    # Commercial - COM8 (Transportation)
    'COM8': ['train_station', 'TRANSPORT BUILDING', 'transportation'],

    # Commercial - COM9 (Recreation / Community / Ancillary)
    'COM9': ['RECREATION FACILITY', 'sports_centre', 'sports_hall', 'gym',
             'recreational', 'SKI', 'GOLF', 'stadium', 'grandstand',
             'PARK BUILDING', 'COMMUNITY CENTRE', 'community_hall', 'AMENITY',
             'roof', 'patio', 'gazebo', 'hut', 'arbor', 'picnic_shelter',
             'bandstand', 'treehouse', 'corridor'],

    # Commercial - COM10 (Theater / Culture)
    'COM10': ['theatre', 'cinema', 'museum', 'MUSEUM'],

    # Industrial - IND1 (Heavy)
    'IND1': ['industrial', 'INDUSTRIAL BUILDING', 'factory', 'RECYCLING BUILDING'],

    # Industrial - IND2 (Light)
    'IND2': ['hangar'],

    # Industrial - IND3 (Food/Drugs/Chemicals)
    'IND3': [],

    # Industrial - IND4 (Metals/Minerals Processing)
    'IND4': [],

    # Industrial - IND5 (High Technology)
    'IND5': [],

    # Industrial - IND6 (Construction)
    'IND6': ['construction'],

    # Agriculture - AGR1
    'AGR1': ['barn', 'farm_auxiliary', 'farm', 'FARM BUILDING', 'greenhouse',
             'stable', 'STABLES', 'livestock', 'silo', 'riding_hall',
             'allotment_house'],

    # Religion - REL1
    'REL1': ['church', 'CHURCH', 'temple', 'mosque', 'MOSQUE', 'synagogue',
             'cathedral', 'chapel', 'place_of_worship', 'religious'],

    # Government - GOV1 (General Services)
    'GOV1': ['civic', 'government', 'public', 'MUNICIPAL HALL', 'post_office',
             'OPERATIONS CENTRE', 'UTILITY BUILDING', 'ANIMAL SHELTER'],

    # Government - GOV2 (Military / Emergency)
    'GOV2': ['fire_station', 'FIRE', 'POLICE', 'military', 'bunker'],

    # Education - EDU1 (Schools/Libraries)
    'EDU1': ['school', 'SCHOOL', 'kindergarten', 'library', 'LIBRARY'],

    # Education - EDU2 (Colleges/Universities)
    'EDU2': ['university', 'college'],

    # Other/Ancillary structures (nulled in output)
    'ANCILLARY': ['shed', 'SHED', 'outbuilding', 'boathouse',
                  'container', 'conservatory'],

    # Lifelines / non-building (nulled in output)
    'LIFELINE': ['bridge', 'storage_tank', 'pumping_station', 'tower'],

    # Historic/Ruins (nulled in output)
    'HISTORIC': ['ruins', 'historic'],

    # Demolished/Invalid (nulled in output)
    'INVALID': ['demolished', 'no', 'N/A', '0', 'OTHER',
                'yes;roof', 'yes;church', '']
}

# Flatten the mapping for easier lookup
type_to_hazus = {}
for hazus_class, building_types in hazus_mapping.items():
    for building_type in building_types:
        type_to_hazus[building_type.lower()] = hazus_class

# Create the categorization
df = df.with_columns(
    pl.col('type')
      .str.to_lowercase()
      .str.strip_chars()
      .replace(type_to_hazus, default='UNCATEGORIZED')
      .alias('hazus_class')
)

# NULL-out requested categories
df = df.with_columns(
    pl.when(pl.col('hazus_class').is_in(
        ['UNCATEGORIZED', 'INVALID', 'HISTORIC', 'LIFELINE', 'ANCILLARY']
    ))
    .then(pl.lit(None))
    .otherwise(pl.col('hazus_class'))
    .alias('type_to_specific')
)

# View results
print("HAZUS Classification Summary:")
print(
    df.group_by('type_to_specific')
      .agg(pl.len().alias('count'))
      .sort('count', descending=True)
)

# View sample mappings
print("\nSample mappings:")
print(
    df.select(['type', 'type_to_specific'])
      .unique()
      .sort('type_to_specific')
)

C:\Users\jasmi\AppData\Local\Temp\ipykernel_4152\663636105.py:122: DeprecationWarning:

the `default` parameter for `replace` is deprecated. Use `replace_strict` instead to set a default while replacing values.
(Deprecated in version 1.0.0)

HAZUS Classification Summary:
shape: (25, 2)
┌──────────────────┬────────┐
│ type_to_specific ┆ count  │
│ ---              ┆ ---    │
│ str              ┆ u32    │
╞══════════════════╪════════╡
│ null             ┆ 585980 │
│ RES1             ┆ 97403  │
│ RES3             ┆ 9531   │
│ COM1             ┆ 1994   │
│ COM4             ┆ 1905   │
│ …                ┆ …      │
│ EDU2             ┆ 42     │
│ COM10            ┆ 12     │
│ COM5             ┆ 2      │
│ RES5             ┆ 2      │
│ RES6             ┆ 1      │
└──────────────────┴────────┘

Sample mappings:
shape: (141, 2)
┌──────────────┬──────────────────┐
│ type         ┆ type_to_specific │
│ ---          ┆ ---              │
│ str          ┆ str              │
╞══════════════╪══════════════════╡
│ storage_tank ┆ null             │
│ parking      ┆ null             │
│ SHED         ┆ null             │
│ CARPORT      ┆ null             │
│ conservatory ┆ null             │
│ …            ┆ …                │
│ hotel        ┆ RES4             │
│ motel        ┆ RES4             │
│ tent         ┆ RES4             │
│ dormitory    ┆ RES5             │
│ nursing_home ┆ RES6             │
└──────────────┴──────────────────┘

'DEVELOPMENT_TYPE' -> 'development_type'

In [27]:
df = df.with_columns(
    pl.col('DEVELOPMENT_TYPE').replace('Nonresidential', None)
).rename({'DEVELOPMENT_TYPE': 'development_type'})

NONRESIDENTIAL_SUBTYPE -> '_subtype_norm' (can drop later) -> 'NONRESIDENTIAL_SUBTYPE_to_specific'

In [28]:
# Map NONRESIDENTIAL_SUBTYPE -> HAZUS specific occupancy
nonres_subtype_to_hazus = {
    'not applicable': None,

    # Agriculture
    'farm related': 'AGR1',
    'greenhouse': 'AGR1',

    # Commercial
    'warehouse': 'COM2',
    'retail': 'COM1',
    'shopping centre': 'COM1',
    'office': 'COM4',
    'commercial (non-office)': 'COM1',
    'automotive services': 'COM3',
    'hotel': 'RES4',

    # Industrial
    'manufacturing': 'IND1',

    # Education
    'education': 'EDU1',
    'library': 'EDU1',

    # Recreation / assembly
    'recreation related': 'COM9',
    'recreational club house': 'COM9',
    'assembly': 'COM9',

    # Government / emergency
    'govt related': 'GOV1',
    'post office': 'GOV1',
    'fire station': 'GOV2',

    # Health
    'health related': 'COM6',

    # Transportation
    'transit station': 'COM8',

    # Non-building / yards / lifelines -> NULL
    'truck parking': None,
    'transit parking': None,
    'rail yard': None,
    'utilities': None,
    'outdoor metal storage': None,
    'lumber yard': None,
    'automotive storage': None,
    'gravel storage': None,
}

# Add the new column to the main dataframe
df = df.with_columns(
    pl.col('NONRESIDENTIAL_SUBTYPE')
      .cast(pl.Utf8)
      .str.to_lowercase()
      .str.strip_chars()
      .replace_strict(nonres_subtype_to_hazus, default=None)
      .alias('NONRESIDENTIAL_SUBTYPE_to_specific')
)

#create summary chart
subtype_counts = (
    df.group_by('NONRESIDENTIAL_SUBTYPE')
      .agg(pl.len().alias('count'))
      .with_columns(
          pl.col('NONRESIDENTIAL_SUBTYPE')
            .cast(pl.Utf8)
            .str.to_lowercase()
            .str.strip_chars()
            .alias('_subtype_norm')
      )
      .with_columns(
          pl.col('_subtype_norm')
            .replace_strict(nonres_subtype_to_hazus, default=None)
            .alias('NONRESIDENTIAL_SUBTYPE_to_specific')
      )
      .drop('_subtype_norm')
      .sort('count', descending=True)
)

print(subtype_counts)
print("\nUnmapped / NULL:")
print(
    subtype_counts
      .filter(pl.col('NONRESIDENTIAL_SUBTYPE_to_specific').is_null())
      .select(['NONRESIDENTIAL_SUBTYPE', 'count'])
)

shape: (30, 3)
┌────────────────────────┬────────┬─────────────────────────────────┐
│ NONRESIDENTIAL_SUBTYPE ┆ count  ┆ NONRESIDENTIAL_SUBTYPE_to_spec… │
│ ---                    ┆ ---    ┆ ---                             │
│ str                    ┆ u32    ┆ str                             │
╞════════════════════════╪════════╪═════════════════════════════════╡
│ null                   ┆ 567106 ┆ null                            │
│ Not Applicable         ┆ 128476 ┆ null                            │
│ Farm Related           ┆ 2308   ┆ AGR1                            │
│ Warehouse              ┆ 1593   ┆ COM2                            │
│ Retail                 ┆ 1278   ┆ COM1                            │
│ …                      ┆ …      ┆ …                               │
│ Library                ┆ 7      ┆ EDU1                            │
│ Transit Parking        ┆ 5      ┆ null                            │
│ Shopping Centre        ┆ 4      ┆ COM1                            │
│ Post Office            ┆ 3      ┆ GOV1                            │
│ Gravel Storage         ┆ 3      ┆ null                            │
└────────────────────────┴────────┴─────────────────────────────────┘

Unmapped / NULL:
shape: (10, 2)
┌────────────────────────┬────────┐
│ NONRESIDENTIAL_SUBTYPE ┆ count  │
│ ---                    ┆ ---    │
│ str                    ┆ u32    │
╞════════════════════════╪════════╡
│ null                   ┆ 567106 │
│ Not Applicable         ┆ 128476 │
│ Truck Parking          ┆ 148    │
│ Rail Yard              ┆ 76     │
│ Utilities              ┆ 72     │
│ Outdoor Metal Storage  ┆ 59     │
│ Lumber Yard            ┆ 58     │
│ Automotive Storage     ┆ 33     │
│ Transit Parking        ┆ 5      │
│ Gravel Storage         ┆ 3      │
└────────────────────────┴────────┘

'DEVELOPMENT_SUBTYPE' -> '_dev_subtype_norm' (can drop later) -> 'DEVELOPMENT_SUBTYPE_to_specific'

In [29]:
# Map DEVELOPMENT_SUBTYPE -> HAZUS specific occupancy
development_subtype_to_hazus = {
    # Residential
    'secondary suite': 'RES1',
    'one family dwelling': 'RES1',
    'two family dwelling': 'RES3',
    'townhouse': 'RES3',
    'row house': 'RES3',
    'low rise apartment': 'RES3',
    'high rise apartment': 'RES3',
    'coach house': 'RES1',
    'mobile house': 'RES2',

    # Agriculture
    'farm related': 'AGR1',

    # Commercial
    'commercial (non-office)': 'COM1',
    'office': 'COM4',

    # Industrial
    'industrial': 'IND1',

    # Government / Education / Health
    'govt related': 'GOV1',
    'education': 'EDU1',
    'health related': 'COM6',

    # Recreation / Assembly
    'recreational club house': 'COM9',
    'assembly': 'COM9',
}

# Add the new column to the main dataframe
df = df.with_columns(
    pl.col('DEVELOPMENT_SUBTYPE')
      .cast(pl.Utf8)
      .str.to_lowercase()
      .str.strip_chars()
      .replace_strict(nonres_subtype_to_hazus, default=None)
      .alias('DEVELOPMENT_SUBTYPE_to_specific')
)

#create summary chart
development_counts = (
    df.group_by('DEVELOPMENT_SUBTYPE')
      .agg(pl.len().alias('count'))
      .with_columns(
          pl.col('DEVELOPMENT_SUBTYPE')
            .cast(pl.Utf8)
            .str.to_lowercase()
            .str.strip_chars()
            .alias('_dev_subtype_norm')
      )
      .with_columns(
          pl.col('_dev_subtype_norm')
            .replace_strict(development_subtype_to_hazus, default=None)
            .alias('DEVELOPMENT_SUBTYPE_to_specific')
      )
      .drop('_dev_subtype_norm')
      .sort('count', descending=True)
)

print(development_counts)
print("\nUnmapped / NULL:")
print(
    development_counts
      .filter(pl.col('DEVELOPMENT_SUBTYPE_to_specific').is_null())
      .select(['DEVELOPMENT_SUBTYPE', 'count'])
)

shape: (19, 3)
┌─────────────────────────┬────────┬─────────────────────────────────┐
│ DEVELOPMENT_SUBTYPE     ┆ count  ┆ DEVELOPMENT_SUBTYPE_to_specifi… │
│ ---                     ┆ ---    ┆ ---                             │
│ str                     ┆ u32    ┆ str                             │
╞═════════════════════════╪════════╪═════════════════════════════════╡
│ null                    ┆ 672488 ┆ null                            │
│ Secondary Suite         ┆ 28912  ┆ RES1                            │
│ One Family Dwelling     ┆ 745    ┆ RES1                            │
│ Industrial              ┆ 440    ┆ IND1                            │
│ Townhouse               ┆ 163    ┆ RES3                            │
│ …                       ┆ …      ┆ …                               │
│ Education               ┆ 12     ┆ EDU1                            │
│ Recreational Club House ┆ 12     ┆ COM9                            │
│ Assembly                ┆ 6      ┆ COM9                            │
│ High Rise Apartment     ┆ 5      ┆ RES3                            │
│ Health Related          ┆ 3      ┆ COM6                            │
└─────────────────────────┴────────┴─────────────────────────────────┘

Unmapped / NULL:
shape: (1, 2)
┌─────────────────────┬────────┐
│ DEVELOPMENT_SUBTYPE ┆ count  │
│ ---                 ┆ ---    │
│ str                 ┆ u32    │
╞═════════════════════╪════════╡
│ null                ┆ 672488 │
└─────────────────────┴────────┘

split BUILDING_U into
- BUILDING_U_to_general
- BUILDING_U_to_specific

In [30]:
# Map BUILDING_U -> general + specific HAZUS occupancy
building_u_to_general_specific = {
    # Residential
    'residential': ('Residential', 'RES1'),
    'residential and commercial': ('Mixed', None),
    'non-market rental residential': ('Residential', 'RES3'),
    'residental': ('Residential', 'RES1'),
    'reidential': ('Residential', 'RES1'),
    'resiential': ('Residential', 'RES1'),
    'reisdential': ('Residential', 'RES1'),
    'residential': ('Residential', 'RES1'),
    'residential ': ('Residential', 'RES1'),

    # Commercial
    'commercial': ('Commercial', 'COM1'),
    'commercial-strata': ('Commercial', 'COM1'),
    'commetcial': ('Commercial', 'COM1'),
    'commericial-industrial': ('Industrial', 'IND1'),
    'commercial-industrial': ('Industrial', 'IND1'),
    'commercial-institutional': ('Mixed', None),

    # Industrial
    'industrial': ('Industrial', 'IND1'),

    # Agriculture
    'agriculture': ('Agriculture', 'AGR1'),
    'truck gardening': ('Agriculture', 'AGR1'),

    # Parks / Recreation
    'parks and recreation': ('Recreation', 'COM9'),
    'recreation': ('Recreation', 'COM9'),
    'civic amenity': ('Recreation', 'COM9'),

    # Institutional / Public
    'institutional and public': ('Government', 'GOV1'),
    'institutional': ('Government', 'GOV1'),
    'public school': ('Education', 'EDU1'),
    'emergency': ('Government', 'GOV2'),

    # Transportation / Parking
    'transportation': ('Transportation', 'COM8'),
    'parking lot': ('Parking', None),

    # Junk / placeholders → NULL
    '': (None, None),
    '<arcgis type="editing"><arrayo': (None, None),
    'site option a': (None, None),
    'site option b': (None, None),
}

# Add the new columns to the main dataframe
df = df.with_columns(
    pl.col('BUILDING_U')
      .cast(pl.Utf8)
      .str.to_lowercase()
      .str.strip_chars()
      .replace_strict(
          {k: v[0] for k, v in building_u_to_general_specific.items()},
          default=None
      )
      .alias('BUILDING_U_to_general'),
    pl.col('BUILDING_U')
      .cast(pl.Utf8)
      .str.to_lowercase()
      .str.strip_chars()
      .replace_strict(
          {k: v[1] for k, v in building_u_to_general_specific.items()},
          default=None
      )
      .alias('BUILDING_U_to_specific')
)

# Create summary counts
building_u_counts = (
    df.group_by('BUILDING_U')
      .agg(pl.len().alias('count'))
      .with_columns(
          pl.col('BUILDING_U')
            .cast(pl.Utf8)
            .str.to_lowercase()
            .str.strip_chars()
            .alias('_building_u_norm')
      )
      .with_columns(
          pl.col('_building_u_norm')
            .replace_strict(
                {k: v[0] for k, v in building_u_to_general_specific.items()},
                default=None
            )
            .alias('BUILDING_U_to_general')
      )
      .with_columns(
          pl.col('_building_u_norm')
            .replace_strict(
                {k: v[1] for k, v in building_u_to_general_specific.items()},
                default=None
            )
            .alias('BUILDING_U_to_specific')
      )
      .drop('_building_u_norm')
      .sort('count', descending=True)
)

print(building_u_counts)

print("\nUnmapped / NULL:")
print(
    building_u_counts
      .filter(
          pl.col('BUILDING_U_to_general').is_null() &
          pl.col('BUILDING_U_to_specific').is_null()
      )
      .select(['BUILDING_U', 'count'])
)

shape: (38, 4)
┌────────────────────────────────┬────────┬───────────────────────┬────────────────────────┐
│ BUILDING_U                     ┆ count  ┆ BUILDING_U_to_general ┆ BUILDING_U_to_specific │
│ ---                            ┆ ---    ┆ ---                   ┆ ---                    │
│ str                            ┆ u32    ┆ str                   ┆ str                    │
╞════════════════════════════════╪════════╪═══════════════════════╪════════════════════════╡
│ null                           ┆ 648397 ┆ null                  ┆ null                   │
│ Residential                    ┆ 50034  ┆ Residential           ┆ RES1                   │
│ Industrial                     ┆ 1814   ┆ Industrial            ┆ IND1                   │
│ Agriculture                    ┆ 926    ┆ Agriculture           ┆ AGR1                   │
│ Commercial                     ┆ 623    ┆ Commercial            ┆ COM1                   │
│ …                              ┆ …      ┆ …                     ┆ …                      │
│ Commericial-Industrial         ┆ 1      ┆ Industrial            ┆ IND1                   │
│ Reisdential                    ┆ 1      ┆ Residential           ┆ RES1                   │
│ Commetcial                     ┆ 1      ┆ Commercial            ┆ COM1                   │
│ 000-000-837                    ┆ 1      ┆ null                  ┆ null                   │
│ YhCeyB5B3Pl+EtrLVEE=</Bytes><S ┆ 1      ┆ null                  ┆ null                   │
└────────────────────────────────┴────────┴───────────────────────┴────────────────────────┘

Unmapped / NULL:
shape: (12, 2)
┌────────────────────────────────┬────────┐
│ BUILDING_U                     ┆ count  │
│ ---                            ┆ ---    │
│ str                            ┆ u32    │
╞════════════════════════════════╪════════╡
│ null                           ┆ 648397 │
│                                ┆ 381    │
│ 000-081-801                    ┆ 2      │
│ 000-008-530                    ┆ 2      │
│ <ArcGIS Type="Editing"><ArrayO ┆ 2      │
│ …                              ┆ …      │
│ Site Option A                  ┆ 1      │
│ 000-085-932                    ┆ 1      │
│ Site Option B                  ┆ 1      │
│ 000-000-837                    ┆ 1      │
│ YhCeyB5B3Pl+EtrLVEE=</Bytes><S ┆ 1      │
└────────────────────────────────┴────────┘

BLDGCLASS -> BLDGCLASS_to_general

In [31]:
# Map BLDGCLASS_ -> general HAZUS occupancy
bldgclass_to_general = {
    'residential': 'Residential',
    'residential auxiliary': 'Residential',
    'auxiliary': None,              # non-primary / ancillary
    'commercial': 'Commercial',
    'industrial': 'Industrial',
    'institutional': 'Government',
    'recreation': 'Recreation',
    'religious': 'Religious',
    'mixed use': 'Mixed',
}

# Add the new column to the main dataframe
df = df.with_columns(
    pl.col('BLDGCLASS_')
      .cast(pl.Utf8)
      .str.to_lowercase()
      .str.strip_chars()
      .replace_strict(nonres_subtype_to_hazus, default=None)
      .alias('BLDGCLASS_to_general')
)

#create summary chart
bldgclass_counts = (
    df.group_by('BLDGCLASS_')
      .agg(pl.len().alias('count'))
      .with_columns(
          pl.col('BLDGCLASS_')
            .cast(pl.Utf8)
            .str.to_lowercase()
            .str.strip_chars()
            .alias('_bldgclass_norm')
      )
      .with_columns(
          pl.col('_bldgclass_norm')
            .replace_strict(bldgclass_to_general, default=None)
            .alias('BLDGCLASS_to_general')
      )
      .drop('_bldgclass_norm')
      .sort('count', descending=True)
)

print(bldgclass_counts)

print("\nUnmapped / NULL:")
print(
    bldgclass_counts
      .filter(pl.col('BLDGCLASS_to_general').is_null())
      .select(['BLDGCLASS_', 'count'])
)

shape: (10, 3)
┌───────────────────────┬────────┬──────────────────────┐
│ BLDGCLASS_            ┆ count  ┆ BLDGCLASS_to_general │
│ ---                   ┆ ---    ┆ ---                  │
│ str                   ┆ u32    ┆ str                  │
╞═══════════════════════╪════════╪══════════════════════╡
│ null                  ┆ 679912 ┆ null                 │
│ RESIDENTIAL           ┆ 21401  ┆ Residential          │
│ COMMERCIAL            ┆ 487    ┆ Commercial           │
│ INDUSTRIAL            ┆ 457    ┆ Industrial           │
│ RESIDENTIAL AUXILIARY ┆ 321    ┆ Residential          │
│ AUXILIARY             ┆ 229    ┆ null                 │
│ INSTITUTIONAL         ┆ 154    ┆ Government           │
│ RECREATION            ┆ 130    ┆ Recreation           │
│ MIXED USE             ┆ 64     ┆ Mixed                │
│ RELIGIOUS             ┆ 30     ┆ Religious            │
└───────────────────────┴────────┴──────────────────────┘

Unmapped / NULL:
shape: (2, 2)
┌────────────┬────────┐
│ BLDGCLASS_ ┆ count  │
│ ---        ┆ ---    │
│ str        ┆ u32    │
╞════════════╪════════╡
│ null       ┆ 679912 │
│ AUXILIARY  ┆ 229    │
└────────────┴────────┘

BLDGTYPE _> BLDG_TYPE_to_specific

In [32]:
# Map BLDGTYPE -> specific HAZUS occupancy
bldgtype_to_specific = {
    'single family': 'RES1',
    'multi family': 'RES3',
    'commercial building': 'COM4',
    'industrial building': 'IND1',

    # Parking / storage accessory -> NULL
    'carport': None,

    # Parks / recreation / community
    'park building': 'COM9',
    'ski': 'COM9',
    'golf': 'COM9',
    'recreation facility': 'COM9',
    'community centre': 'COM9',
    'amenity': 'COM9',

    # Education
    'school': 'EDU1',
    'library': 'EDU1',

    # Government / emergency / public service
    'utility building': 'GOV1',
    'operations centre': 'GOV1',
    'municipal hall': 'GOV1',
    'fire': 'GOV2',
    'police': 'GOV2',

    # Transportation
    'transport building': 'COM8',

    # Agriculture
    'farm building': 'AGR1',
    'stables': 'AGR1',

    # Religion
    'church': 'REL1',
    'mosque': 'REL1',

    # Health / institutional
    'hospital': 'COM6',
    'animal shelter': 'GOV1',

    # Culture
    'museum': 'COM10',

    # Invalid / placeholders -> NULL
    'other': None,
    'n/a': None,
    '': None,

    # Mixed use -> keep as mixed general, but no specific class
    'mixed use': None,
}

# Add the new column to the main dataframe
df = df.with_columns(
    pl.col('BLDGTYPE')
      .cast(pl.Utf8)
      .str.to_lowercase()
      .str.strip_chars()
      .replace_strict(nonres_subtype_to_hazus, default=None)
      .alias('BLDGTYPE_to_specific')
)

#create summary chart

bldgtype_counts = (
    df.group_by('BLDGTYPE')
      .agg(pl.len().alias('count'))
      .with_columns(
          pl.col('BLDGTYPE')
            .cast(pl.Utf8)
            .str.to_lowercase()
            .str.strip_chars()
            .alias('_bldgtype_norm')
      )
      .with_columns(
          pl.col('_bldgtype_norm')
            .replace_strict(bldgtype_to_specific, default=None)
            .alias('BLDGTYPE_to_specific')
      )
      .drop('_bldgtype_norm')
      .sort('count', descending=True)
)

print(bldgtype_counts)

print("\nUnmapped / NULL:")
print(
    bldgtype_counts
      .filter(pl.col('BLDGTYPE_to_specific').is_null())
      .select(['BLDGTYPE', 'count'])
)

shape: (33, 3)
┌─────────────────────┬────────┬──────────────────────┐
│ BLDGTYPE            ┆ count  ┆ BLDGTYPE_to_specific │
│ ---                 ┆ ---    ┆ ---                  │
│ str                 ┆ u32    ┆ str                  │
╞═════════════════════╪════════╪══════════════════════╡
│ null                ┆ 679912 ┆ null                 │
│ SINGLE FAMILY       ┆ 20144  ┆ RES1                 │
│ MULTI FAMILY        ┆ 1251   ┆ RES3                 │
│ COMMERCIAL BUILDING ┆ 490    ┆ COM4                 │
│ INDUSTRIAL BUILDING ┆ 457    ┆ IND1                 │
│ …                   ┆ …      ┆ …                    │
│ MUNICIPAL HALL      ┆ 1      ┆ GOV1                 │
│ MOSQUE              ┆ 1      ┆ REL1                 │
│ MUSEUM              ┆ 1      ┆ COM10                │
│ ANIMAL SHELTER      ┆ 1      ┆ GOV1                 │
│ HOSPITAL            ┆ 1      ┆ COM6                 │
└─────────────────────┴────────┴──────────────────────┘

Unmapped / NULL:
shape: (8, 2)
┌────────────────────┬────────┐
│ BLDGTYPE           ┆ count  │
│ ---                ┆ ---    │
│ str                ┆ u32    │
╞════════════════════╪════════╡
│ null               ┆ 679912 │
│ CARPORT            ┆ 265    │
│ MIXED USE          ┆ 65     │
│ OTHER              ┆ 5      │
│ N/A                ┆ 3      │
│ SHED               ┆ 3      │
│                    ┆ 3      │
│ RECYCLING BUILDING ┆ 2      │
└────────────────────┴────────┘

BLDG_SUBTYP -> BLDG_SUBTYP_to_specific

In [33]:
# Map BLDGSUBTYP -> specific HAZUS occupancy
bldg_subtyp_to_specific = {
    # Residential
    'detached': 'RES1',
    'cabin': 'RES1',
    'coach': 'RES1',
    'houseboat': 'RES1',
    'secondary': 'RES1',   # secondary suite / secondary dwelling
    'duplex': 'RES3',
    'triplex': 'RES3',
    'fourplex': 'RES3',
    'townhouse': 'RES3',
    'low rise apartment': 'RES3',
    'high rise apartment': 'RES3',
    'mixed use - single family': None,
    'mixed use - multi family': None,

    # Education
    'elementary': 'EDU1',
    'post secondary': 'EDU2',
    'daycare centre': 'EDU1',

    # Government / public service / emergency
    'administration': 'GOV1',
    'operational': 'GOV1',
    'maintenance': 'GOV1',
    'road maintenance': 'GOV1',
    'caretaker': 'GOV1',
    'public': 'GOV1',
    'private': None,
    'police station': 'GOV2',
    'search and rescue station': 'GOV2',
    'fire station': 'GOV2',
    'fire training centre': 'GOV2',

    # Agriculture
    'barn': 'AGR1',
    'nursery': 'AGR1',

    # Commercial / retail
    'shop': 'COM1',
    'kiosk': 'COM1',
    'concession': 'COM1',
    'guest services': 'COM4',

    # Recreation / community / park structures
    'clubhouse': 'COM9',
    'interpretive centre': 'COM9',
    'turf centre': 'COM9',
    'batters cage': 'COM9',
    'picnic shelter': 'COM9',
    'gazebo': 'COM9',
    'shelter': 'COM9',
    'scout shelter': 'COM9',
    'youth': 'COM9',

    # Industrial / facilities
    'workshop': 'IND1',
    'workshop ': 'IND1',
    'storage': 'COM2',

    # Lifeline / utility-type (NULL)
    'water tank': None,
    'substation': None,
    'water treatment plant': None,
    'water pump station': None,
    'sewage treatment plant': None,
    'water distribution facility': None,
    'energy recovery facility': None,
    'gvrd transfer station': None,

    # Transportation / non-building (NULL)
    'bus shelter': None,
    'washroom': None,
    'bus washroom': None,

    # Accessory / parking (NULL)
    'garage': None,
    'gatehouse': 'COM4',

    # Invalid / placeholders
    'n/a': None,
    'other': None,
    '': None,
    'general': None,
}


# Add the new column to the main dataframe
df = df.with_columns(
    pl.col('BLDGSUBTYP')
      .cast(pl.Utf8)
      .str.to_lowercase()
      .str.strip_chars()
      .replace_strict(nonres_subtype_to_hazus, default=None)
      .alias('BLDGSUBTYP_to_specific')
)

#create summary chart
bldgsubtyp_counts = (
    df.group_by('BLDGSUBTYP')
      .agg(pl.len().alias('count'))
      .with_columns(
          pl.col('BLDGSUBTYP')
            .cast(pl.Utf8)
            .str.to_lowercase()
            .str.strip_chars()
            .alias('_bldgsubtyp_norm')
      )
      .with_columns(
          pl.col('_bldgsubtyp_norm')
            .replace_strict(bldg_subtyp_to_specific, default=None)
            .alias('BLDG_SUBTYP_to_specific')
      )
      .drop('_bldgsubtyp_norm')
      .sort('count', descending=True)
)

print(bldgsubtyp_counts)

print("\nUnmapped / NULL:")
print(
    bldgsubtyp_counts
      .filter(pl.col('BLDG_SUBTYP_to_specific').is_null())
      .select(['BLDGSUBTYP', 'count'])
)

shape: (62, 3)
┌────────────────────────┬────────┬─────────────────────────┐
│ BLDGSUBTYP             ┆ count  ┆ BLDG_SUBTYP_to_specific │
│ ---                    ┆ ---    ┆ ---                     │
│ str                    ┆ u32    ┆ str                     │
╞════════════════════════╪════════╪═════════════════════════╡
│ null                   ┆ 679912 ┆ null                    │
│ DETACHED               ┆ 20074  ┆ RES1                    │
│ N/A                    ┆ 1328   ┆ null                    │
│ TOWNHOUSE              ┆ 1009   ┆ RES3                    │
│ LOW RISE APARTMENT     ┆ 168    ┆ RES3                    │
│ …                      ┆ …      ┆ …                       │
│ SEWAGE TREATMENT PLANT ┆ 1      ┆ null                    │
│ SCOUT SHELTER          ┆ 1      ┆ COM9                    │
│ GUEST SERVICES         ┆ 1      ┆ COM4                    │
│ GATEHOUSE              ┆ 1      ┆ COM4                    │
│ GARAGE                 ┆ 1      ┆ null                    │
└────────────────────────┴────────┴─────────────────────────┘

Unmapped / NULL:
shape: (20, 2)
┌─────────────────────────────┬────────┐
│ BLDGSUBTYP                  ┆ count  │
│ ---                         ┆ ---    │
│ str                         ┆ u32    │
╞═════════════════════════════╪════════╡
│ null                        ┆ 679912 │
│ N/A                         ┆ 1328   │
│ MIXED USE - MULTI FAMILY    ┆ 42     │
│ WASHROOM                    ┆ 29     │
│                             ┆ 24     │
│ …                           ┆ …      │
│ ENERGY RECOVERY FACILITY    ┆ 1      │
│ GVRD TRANSFER STATION       ┆ 1      │
│ WATER DISTRIBUTION FACILITY ┆ 1      │
│ SEWAGE TREATMENT PLANT      ┆ 1      │
│ GARAGE                      ┆ 1      │
└─────────────────────────────┴────────┘

PRIMARY_USE -> PRIMARY_USE_to_specific (null COMMERCIAL)

In [34]:
# Map PRIMARYUSE -> specific HAZUS occupancy
primaryuse_to_specific = {
    # Residential
    'single family': 'RES1',
    'multi family': 'RES3',

    # Commercial / community
    'commercial': 'COM1',
    'community centre': 'COM9',

    # Education
    'library': 'EDU1',

    # Invalid / placeholders -> NULL
    'n/a': None,
    '': None,
}
# Add the new column to the main dataframe
df = df.with_columns(
    pl.col('PRIMARYUSE')
      .cast(pl.Utf8)
      .str.to_lowercase()
      .str.strip_chars()
      .replace_strict(nonres_subtype_to_hazus, default=None)
      .alias('PRIMARYUSE_to_specific')
)

primaryuse_counts = (
    df.group_by('PRIMARYUSE')
      .agg(pl.len().alias('count'))
      .with_columns(
          pl.col('PRIMARYUSE')
            .cast(pl.Utf8)
            .str.to_lowercase()
            .str.strip_chars()
            .alias('_primaryuse_norm')
      )
      .with_columns(
          pl.col('_primaryuse_norm')
            .replace_strict(primaryuse_to_specific, default=None)
            .alias('PRIMARYUSE_to_specific')
      )
      .drop('_primaryuse_norm')
      .sort('count', descending=True)
)

print(primaryuse_counts)

print("\nUnmapped / NULL:")
print(
    primaryuse_counts
      .filter(pl.col('PRIMARYUSE_to_specific').is_null())
      .select(['PRIMARYUSE', 'count'])
)

shape: (8, 3)
┌──────────────────┬────────┬────────────────────────┐
│ PRIMARYUSE       ┆ count  ┆ PRIMARYUSE_to_specific │
│ ---              ┆ ---    ┆ ---                    │
│ str              ┆ u32    ┆ str                    │
╞══════════════════╪════════╪════════════════════════╡
│ null             ┆ 679912 ┆ null                   │
│ N/A              ┆ 23137  ┆ null                   │
│                  ┆ 65     ┆ null                   │
│ MULTI FAMILY     ┆ 42     ┆ RES3                   │
│ COMMERCIAL       ┆ 19     ┆ COM1                   │
│ SINGLE FAMILY    ┆ 6      ┆ RES1                   │
│ COMMUNITY CENTRE ┆ 3      ┆ COM9                   │
│ LIBRARY          ┆ 1      ┆ EDU1                   │
└──────────────────┴────────┴────────────────────────┘

Unmapped / NULL:
shape: (3, 2)
┌────────────┬────────┐
│ PRIMARYUSE ┆ count  │
│ ---        ┆ ---    │
│ str        ┆ u32    │
╞════════════╪════════╡
│ null       ┆ 679912 │
│ N/A        ┆ 23137  │
│            ┆ 65     │
└────────────┴────────┘

ACTUAL_USE_DESCRIPTION_to_specific

In [35]:
# Map ACTUAL_USE_DESCRIPTION -> specific HAZUS occupancy
actual_use_to_specific = {
    # Residential - single family
    'single family dwelling': 'RES1',
    'residential dwelling with suit': 'RES1',
    '2 acres or more (single family': 'RES1',
    'seasonal dwelling': 'RES1',
    '2 acres or more (seasonal dwel': 'RES1',

    # Residential - attached / multifamily
    'row housing (single unit owner': 'RES3',
    'strata-lot residence (condomin': 'RES3',
    'stratified rental townhouse': 'RES3',
    'stratified rental apartment (f': 'RES3',
    'stratified rental apartment (h': 'RES3',
    'multi-family (apartment block)': 'RES3',
    'multi-family (conversion)': 'RES3',
    'multi-family (vacant)': 'RES3',

    # Duplex / triplex etc.
    'duplex, strata side by side': 'RES3',
    'duplex, non-strata side by sid': 'RES3',
    'duplex, strata front / back': 'RES3',
    'duplex, non-strata up / down': 'RES3',
    'duplex, strata up / down': 'RES3',
    'triplex': 'RES3',

    # Manufactured / mobile
    'manufactured home (within manu': 'RES2',
    'manufactured home (not in manu': 'RES2',
    '2 acres or more (manufactured': 'RES2',

    # Lodging
    'bed & breakfast operation less': 'RES4',

    # Agriculture / farm-related (incl. small fruits / livestock)
    'poultry': 'AGR1',
    'small fruits': 'AGR1',
    'beef': 'AGR1',

    # Industrial (vacant)
    'industrial (vacant)': 'IND1',

    # Ancillary / outbuildings only -> NULL
    '2 acres or more (outbuilding)': None,
    'residential outbuilding only': None,

    # Vacant residential land -> NULL
    'vacant residential less than 2': None,
    '2 acres or more (vacant)': None,

    # Policy / misc -> NULL
    'property subject to section 19': None,
    'other': None,
    'mixed': None,
}

# Add the new column to the main dataframe
df = df.with_columns(
    pl.col('ACTUAL_USE_DESCRIPTION')
      .cast(pl.Utf8)
      .str.to_lowercase()
      .str.strip_chars()
      .alias('_aud_norm')
).with_columns(
    # normalize truncated strings by matching on prefixes
    pl.when(pl.col('_aud_norm').str.starts_with('residential dwelling with suit'))
      .then(pl.lit('residential dwelling with suit'))
    .when(pl.col('_aud_norm').str.starts_with('row housing (single unit owner'))
      .then(pl.lit('row housing (single unit owner'))
    .when(pl.col('_aud_norm').str.starts_with('2 acres or more (single family'))
      .then(pl.lit('2 acres or more (single family'))
    .when(pl.col('_aud_norm').str.starts_with('duplex, strata side by side'))
      .then(pl.lit('duplex, strata side by side'))
    .when(pl.col('_aud_norm').str.starts_with('strata-lot residence (condomin'))
      .then(pl.lit('strata-lot residence (condomin'))
    .when(pl.col('_aud_norm').str.starts_with('duplex, non-strata side by sid'))
      .then(pl.lit('duplex, non-strata side by sid'))
    .when(pl.col('_aud_norm').str.starts_with('duplex, strata front / back'))
      .then(pl.lit('duplex, strata front / back'))
    .when(pl.col('_aud_norm').str.starts_with('manufactured home (within manu'))
      .then(pl.lit('manufactured home (within manu'))
    .when(pl.col('_aud_norm').str.starts_with('manufactured home (not in manu'))
      .then(pl.lit('manufactured home (not in manu'))
    .when(pl.col('_aud_norm').str.starts_with('vacant residential less than 2'))
      .then(pl.lit('vacant residential less than 2'))
    .when(pl.col('_aud_norm').str.starts_with('2 acres or more (vacant)'))
      .then(pl.lit('2 acres or more (vacant)'))
    .when(pl.col('_aud_norm').str.starts_with('stratified rental apartment (f'))
      .then(pl.lit('stratified rental apartment (f'))
    .when(pl.col('_aud_norm').str.starts_with('2 acres or more (outbuilding)'))
      .then(pl.lit('2 acres or more (outbuilding)'))
    .when(pl.col('_aud_norm').str.starts_with('2 acres or more (manufactured'))
      .then(pl.lit('2 acres or more (manufactured'))
    .when(pl.col('_aud_norm').str.starts_with('bed & breakfast operation less'))
      .then(pl.lit('bed & breakfast operation less'))
    .when(pl.col('_aud_norm').str.starts_with('2 acres or more (seasonal dwel'))
      .then(pl.lit('2 acres or more (seasonal dwel'))
    .when(pl.col('_aud_norm').str.starts_with('stratified rental apartment (h'))
      .then(pl.lit('stratified rental apartment (h'))
    .when(pl.col('_aud_norm').str.starts_with('property subject to section 19'))
      .then(pl.lit('property subject to section 19'))
    .otherwise(pl.col('_aud_norm'))
    .alias('_aud_norm2')
).with_columns(
    pl.col('_aud_norm2')
      .replace_strict(actual_use_to_specific, default=None)
      .alias('ACTUAL_USE_DESCRIPTION_to_specific')
).drop(['_aud_norm', '_aud_norm2'])

# Create summary counts
actual_use_counts = (
    df.group_by('ACTUAL_USE_DESCRIPTION')
      .agg(pl.len().alias('count'))
      .with_columns(
          pl.col('ACTUAL_USE_DESCRIPTION')
            .cast(pl.Utf8)
            .str.to_lowercase()
            .str.strip_chars()
            .alias('_aud_norm')
      )
      .with_columns(
          # normalize truncated strings from your printout by matching on prefixes
          pl.when(pl.col('_aud_norm').str.starts_with('residential dwelling with suit'))
            .then(pl.lit('residential dwelling with suit'))
          .when(pl.col('_aud_norm').str.starts_with('row housing (single unit owner'))
            .then(pl.lit('row housing (single unit owner'))
          .when(pl.col('_aud_norm').str.starts_with('2 acres or more (single family'))
            .then(pl.lit('2 acres or more (single family'))
          .when(pl.col('_aud_norm').str.starts_with('duplex, strata side by side'))
            .then(pl.lit('duplex, strata side by side'))
          .when(pl.col('_aud_norm').str.starts_with('strata-lot residence (condomin'))
            .then(pl.lit('strata-lot residence (condomin'))
          .when(pl.col('_aud_norm').str.starts_with('duplex, non-strata side by sid'))
            .then(pl.lit('duplex, non-strata side by sid'))
          .when(pl.col('_aud_norm').str.starts_with('duplex, strata front / back'))
            .then(pl.lit('duplex, strata front / back'))
          .when(pl.col('_aud_norm').str.starts_with('manufactured home (within manu'))
            .then(pl.lit('manufactured home (within manu'))
          .when(pl.col('_aud_norm').str.starts_with('manufactured home (not in manu'))
            .then(pl.lit('manufactured home (not in manu'))
          .when(pl.col('_aud_norm').str.starts_with('vacant residential less than 2'))
            .then(pl.lit('vacant residential less than 2'))
          .when(pl.col('_aud_norm').str.starts_with('2 acres or more (vacant)'))
            .then(pl.lit('2 acres or more (vacant)'))
          .when(pl.col('_aud_norm').str.starts_with('stratified rental apartment (f'))
            .then(pl.lit('stratified rental apartment (f'))
          .when(pl.col('_aud_norm').str.starts_with('2 acres or more (outbuilding)'))
            .then(pl.lit('2 acres or more (outbuilding)'))
          .when(pl.col('_aud_norm').str.starts_with('2 acres or more (manufactured'))
            .then(pl.lit('2 acres or more (manufactured'))
          .when(pl.col('_aud_norm').str.starts_with('bed & breakfast operation less'))
            .then(pl.lit('bed & breakfast operation less'))
          .when(pl.col('_aud_norm').str.starts_with('2 acres or more (seasonal dwel'))
            .then(pl.lit('2 acres or more (seasonal dwel'))
          .when(pl.col('_aud_norm').str.starts_with('stratified rental apartment (h'))
            .then(pl.lit('stratified rental apartment (h'))
          .when(pl.col('_aud_norm').str.starts_with('property subject to section 19'))
            .then(pl.lit('property subject to section 19'))
          .otherwise(pl.col('_aud_norm'))
          .alias('_aud_norm2')
      )
      .with_columns(
          pl.col('_aud_norm2')
            .replace_strict(actual_use_to_specific, default=None)
            .alias('ACTUAL_USE_DESCRIPTION_to_specific')
      )
      .drop(['_aud_norm', '_aud_norm2'])
      .sort('count', descending=True)
)

print(actual_use_counts)

print("\nUnmapped / NULL:")
print(
    actual_use_counts
      .filter(pl.col('ACTUAL_USE_DESCRIPTION_to_specific').is_null())
      .select(['ACTUAL_USE_DESCRIPTION', 'count'])
)

shape: (35, 3)
┌─────────────────────────────────┬────────┬─────────────────────────────────┐
│ ACTUAL_USE_DESCRIPTION          ┆ count  ┆ ACTUAL_USE_DESCRIPTION_to_spec… │
│ ---                             ┆ ---    ┆ ---                             │
│ str                             ┆ u32    ┆ str                             │
╞═════════════════════════════════╪════════╪═════════════════════════════════╡
│ Single Family Dwelling          ┆ 324920 ┆ RES1                            │
│ Residential Dwelling with Suit… ┆ 184756 ┆ RES1                            │
│ null                            ┆ 109945 ┆ null                            │
│ Row Housing (Single Unit Owner… ┆ 30103  ┆ RES3                            │
│ 2 Acres Or More (Single Family… ┆ 14581  ┆ RES1                            │
│ …                               ┆ …      ┆ …                               │
│ Multi-Family (Conversion)       ┆ 9      ┆ RES3                            │
│ Beef                            ┆ 8      ┆ AGR1                            │
│ Industrial (Vacant)             ┆ 3      ┆ IND1                            │
│ Multi-Family (Apartment Block)  ┆ 2      ┆ RES3                            │
│ Mixed                           ┆ 1      ┆ null                            │
└─────────────────────────────────┴────────┴─────────────────────────────────┘

Unmapped / NULL:
shape: (8, 2)
┌─────────────────────────────────┬────────┐
│ ACTUAL_USE_DESCRIPTION          ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ null                            ┆ 109945 │
│ Property Subject To Section 19… ┆ 6905   │
│ Vacant Residential Less Than 2… ┆ 2376   │
│ 2 Acres Or More (Vacant)        ┆ 680    │
│ 2 Acres Or More (Outbuilding)   ┆ 203    │
│ Residential Outbuilding Only    ┆ 135    │
│ Other                           ┆ 13     │
│ Mixed                           ┆ 1      │
└─────────────────────────────────┴────────┘

R_or_C rename to Commercial

In [36]:
df = df.with_columns(
    pl.col('R_or_C')).rename({'R_or_C': 'Commercial'})

Subtype rename to Offices

In [37]:
df = df.with_columns(
    pl.col('Subtype')).rename({'Subtype': 'Offices'})

Need to split up Manual Class Description, will take extra parsing. 
#### What is the Manual Class? 
##### Residential buildings are grouped into manual classes based quality of design and materials, architectural age, and number of storeys. 

Sources: 
1. https://www.bcassessment.ca/Files/Misc/UserGuide/Residential_Inventory_Extract_External_User_Guide.pdf
2. https://www.bcassessment.ca/Files/Misc/UserGuide/Tables/dataadv12.pdf

In [38]:
# Set Polars to show all rows
pl.Config.set_tbl_rows(-1)

#seeing unique values and count
df.group_by('MANUAL_CLASS_DESCRIPTION').agg(pl.len().alias('count')).sort('count', descending=True)

shape: (185, 2)
┌─────────────────────────────────┬────────┐
│ MANUAL_CLASS_DESCRIPTION        ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ null                            ┆ 112984 │
│ 1 STY SFD - After 1960 - Stand… ┆ 109685 │
│ 2 STY SFD - After 1990 Semi-Cu… ┆ 85520  │
│ 1 STY SFD - After 1930 - Stand… ┆ 60976  │
│ 2 STY SFD - After 1990 - Stand… ┆ 42215  │
│ 2 STY SFD - After 1990 - Custo… ┆ 40398  │
│ Strata Townhouse                ┆ 30159  │
│ 2 STY SFD - After 1930 - Semi-… ┆ 28641  │
│ 1 STY SFD - After 1930 - Semi-… ┆ 21777  │
│ 1 STY SFD - After 1990 - Stand… ┆ 21679  │
│ 2 STY SFD - After 1960 - Stand… ┆ 20479  │
│ 1 STY SFD - After 1990 - Semi-… ┆ 16389  │
│ 2 STY SFD - After 1930 - Custo… ┆ 12977  │
│ 1 STY SFD - After 1930 - Basic  ┆ 9159   │
│ 1.5 STY SFD - Before 1930 - Ba… ┆ 8571   │
│ 1 STY SFD - Before 1930 - Basi… ┆ 6825   │
│ 1.5 STY SFD - Before 1930 - St… ┆ 5485   │
│ 1.5 STY SFD - After 1930 - Sta… ┆ 5075   │
│ 2 STY SFD - Before 1930 - Stan… ┆ 4587   │
│ Strata Apartment - Frame        ┆ 4301   │
│ 2 STY SFD - After 1930 - Stand… ┆ 4279   │
│ 2 STY Duplex - After 1990 - St… ┆ 3865   │
│ Non-Manualized Structures       ┆ 3697   │
│ 2 STY SFD - Before 1930 - Basi… ┆ 3557   │
│ 2 STY Duplex - After 1990 - Se… ┆ 3469   │
│ 1 STY Duplex - After 1960 - St… ┆ 2900   │
│ 1.5 STY SFD - After 1930 - Bas… ┆ 2307   │
│ 1.5 STY SFD - After 1960 - Sta… ┆ 2187   │
│ Strata Apartment - Hi-Rise      ┆ 2009   │
│ 1 STY SFD - After 1990 - Custo… ┆ 1816   │
│ 1 STY SFD - After 1930 - Custo… ┆ 1800   │
│ 1.5 STY SFD - After 1930 - Sem… ┆ 1736   │
│ MH - Single Wide - Ave Q        ┆ 1698   │
│ 1 STY Duplex - After 1930 - St… ┆ 1364   │
│ 2 STY SFD - Before 1930 - Cust… ┆ 1351   │
│ 2 STY Duplex - After 1960 - St… ┆ 1082   │
│ MH - Single Wide - Fair Q       ┆ 1055   │
│ 1 STY SFD - Before 1930 - Stan… ┆ 981    │
│ 2 STY Duplex - After 1930 - Se… ┆ 808    │
│ 1.5 STY SFD - After 1990 - Sta… ┆ 805    │
│ 2 STY Row House - After 1990 -… ┆ 770    │
│ 2 STY SFD - After 1930 - Basic  ┆ 748    │
│ 1 STY SFD - All Ages - Basic    ┆ 735    │
│ MH - Double Wide - Ave Q        ┆ 655    │
│ 2 STY Duplex - After 1930 - St… ┆ 651    │
│ 3 STY SFD - After 1990 - Semi-… ┆ 625    │
│ 1 STY Duplex - After 1990 - St… ┆ 608    │
│ 3 STY SFD - After 1990 - Custo… ┆ 590    │
│ 1.5 STY SFD - After 1990 - Sem… ┆ 571    │
│ 1.5 STY SFD - After 1930 - Cus… ┆ 460    │
│ 3 STY SFD - After 1990 - Stand… ┆ 396    │
│ 2 STY Duplex - After 1990 - Cu… ┆ 352    │
│ 3 STY SFD - Before 1930 - Cust… ┆ 330    │
│ 1 STY Duplex - After 1930 - Ba… ┆ 327    │
│ 3 STY Duplex - After 1990 - Se… ┆ 316    │
│ 3 STY Duplex - After 1930 - Se… ┆ 270    │
│ MH - Double Wide - Good Q       ┆ 267    │
│ 1 STY Recr Home - All Ages - B… ┆ 231    │
│ 1.5 STY SFD - After 1990 - Cus… ┆ 224    │
│ 3 STY SFD - After 1930 - Custo… ┆ 211    │
│ 1.5 STY SFD - Before 1930 - Cu… ┆ 207    │
│ 1 STY Duplex - After 1990 - Se… ┆ 189    │
│ 3 STY Duplex - After 1990 - St… ┆ 176    │
│ 3 STY SFD - Before 1930 - Basi… ┆ 172    │
│ 1.5 STY SFD - All Ages - Basic  ┆ 172    │
│ 3 STY SFD - Before 1930 - Stan… ┆ 165    │
│ 1 STY Duplex - After 1930 - Se… ┆ 148    │
│ MH - Single Wide - Low Q        ┆ 140    │
│ 3 STY SFD - After 1930 - Semi-… ┆ 116    │
│ 2 STY Duplex - Before 1930 - S… ┆ 111    │
│ Strata Apartment - Concrete     ┆ 101    │
│ 2 STY Row House - After 1930 -… ┆ 85     │
│ 2 STY SFD - All Ages - Basic    ┆ 70     │
│ 3 STY SFD - After 1960 - Stand… ┆ 69     │
│ 2 STY Duplex - After 1930 - Cu… ┆ 49     │
│ 3 STY Duplex - After 1990 - Cu… ┆ 47     │
│ Barn, General Purpose           ┆ 47     │
│ Warehouse, Storage              ┆ 46     │
│ 2 STY Duplex - After 1930 - Ba… ┆ 46     │
│ Gen Purpose Shed & Outbldg - L… ┆ 45     │
│ Gen Purpose Shed & Outbldg - A… ┆ 40     │
│ 2 STY Row House - After 1990-S… ┆ 39     │
│ 1.5 STY Duplex - After 1960 - … ┆ 38     │
│ 1 STY Duplex - Before 1930 - S… ┆ 38     │
│ MH - Single Wide - Good Q       ┆ 37     │
│ Non-Manualized Structures - Re… ┆ 37     │
│ 1.5 STY Recr Home - All Ages -… ┆ 34     │
│ 2 STY Duplex - Before 1930 - B… ┆ 33     │
│ 1.5 STY Duplex - Before 1930 -… ┆ 31     │
│ Stable                          ┆ 31     │
│ 1.5 STY Duplex - After 1930 - … ┆ 29     │
│ MH - Single Wide - Very Good Q  ┆ 29     │
│ Gen Purpose Shed & Outbldg - B… ┆ 29     │
│ 1.5 STY Duplex - Before 1930 -… ┆ 25     │
│ 1.5 STY Duplex - After 1990 -S… ┆ 21     │
│ Farm Implement Building         ┆ 19     │
│ Domestic Garage - Average Qual… ┆ 17     │
│ 1.5 STY Duplex - After 1930 - … ┆ 17     │
│ 1.5 STY Duplex - After 1990 - … ┆ 16     │
│ Float - Light Duty              ┆ 14     │
│ 2 STY Recr Home - All Ages - B… ┆ 14     │
│ 1 STY Duplex - After 1990- Cus… ┆ 14     │
│ 1 STY Duplex - Before 1930 - B… ┆ 13     │
│ Artist Studio                   ┆ 13     │
│ Relocatable Office              ┆ 12     │
│ Farm Implement Arch-Rib, Quons… ┆ 12     │
│ 1.5 STY Duplex - After 1930 -S… ┆ 12     │
│ Domestic Garage - Low Quality   ┆ 12     │
│ 3 STY SFD - After 1930 - Stand… ┆ 11     │
│ MH - Double Wide - Very Good Q  ┆ 11     │
│ 1 STY SFD - Before 1930 - Cust… ┆ 11     │
│ Equipment (Shop) Building       ┆ 10     │
│ Implmnt Shed & Farm Shltr - Be… ┆ 10     │
│ Retail Store                    ┆ 9      │
│ MH - Double Wide - Fair Q       ┆ 9      │
│ Industrial Light Manufacturing  ┆ 8      │
│ 3 STY Duplex - Before 1930 - S… ┆ 8      │
│ 2 STY Row House - After 1960 -… ┆ 8      │
│ 3 STY Duplex - After 1930 - Cu… ┆ 8      │
│ 1 STY Row House - After 1930 -… ┆ 8      │
│ Greenhouse, Straight Wall, lar… ┆ 8      │
│ Farm Utility Shelter            ┆ 7      │
│ Horse Arena                     ┆ 7      │
│ 3 STY Duplex - After 1960 - St… ┆ 7      │
│ MH - Single Wide - Excellent Q  ┆ 7      │
│ Float - Alternate Light Constr  ┆ 7      │
│ 1 STY Duplex - All Ages - Basi… ┆ 6      │
│ Multiple Residence              ┆ 6      │
│ Campground                      ┆ 6      │
│ Day Care Centre                 ┆ 6      │
│ Domestic Garage 2 STY - Averag… ┆ 6      │
│ 3 STY Duplex - Before 1930 - C… ┆ 6      │
│ Farm Utility Arch-Rib, Quonset  ┆ 5      │
│ 2 STY Duplex - Before 1930 - C… ┆ 5      │
│ Strata Apartment - Brick/Block  ┆ 4      │
│ Laneway 1.5 STY SFD-Aft 1990-S… ┆ 4      │
│ Dormitory                       ┆ 4      │
│ 3 STY Duplex - After 1930 - St… ┆ 4      │
│ 1 STY Row House - After 1930 -… ┆ 4      │
│ 1.5 STY Duplex - After 1990 - … ┆ 4      │
│ 1 STY Row House - All Ages - B… ┆ 4      │
│ Equipment Shed                  ┆ 4      │
│ 1 STY Duplex - After 1990 - Cu… ┆ 4      │
│ 1.5 STY Duplex - Before 1930 -… ┆ 3      │
│ Greenhouse, Mod. Hoop, small    ┆ 3      │
│ MH - Double Wide - Excellent Q  ┆ 3      │
│ Farm Implement Shed             ┆ 3      │
│ 2 STY Row House - After 1930 -… ┆ 3      │
│ 1 STY Row House - After 1990-S… ┆ 3      │
│ Wharf - Light Construction      ┆ 3      │
│ 2 STY Row House - Before 1930 … ┆ 3      │
│ Laneway 2 STY SFD -Aft 1990 -S… ┆ 3      │
│ 1 STY Duplex - Before 1930 - C… ┆ 3      │
│ Tool Shed                       ┆ 3      │
│ Laneway 1 STY SFD - Aft 1990-S… ┆ 3      │
│ Apartment Over Commercial       ┆ 3      │
│ Domestic Garage - Above Averag… ┆ 3      │
│ 3 STY Duplex - Before 1930 - B… ┆ 3      │
│ 1.5 STY Duplex - All Ages - Ba… ┆ 2      │
│ Domestic Carport - Above Avera… ┆ 2      │
│ Service Station - Minimum       ┆ 2      │
│ 2 STY Row House - After 1990 -… ┆ 2      │
│ Miscellaneous                   ┆ 2      │
│ Apartment (High Rise)           ┆ 2      │
│ Farm Utility Building           ┆ 2      │
│ Material Shelter                ┆ 2      │
│ 2 STY Row House - After 1930-S… ┆ 2      │
│ 1.5 STY Row House-After 1990-S… ┆ 2      │
│ 3 STY Row House - After 1990 -… ┆ 2      │
│ Material Storage                ┆ 2      │
│ Greenhouse, Straight Wall, med… ┆ 2      │
│ Apartment - Frame               ┆ 2      │
│ Domestic Carport - Average Qua… ┆ 2      │
│ 3 STY SFD - After 1930 - Basic  ┆ 1      │
│ Domestic Carport - Low Quality  ┆ 1      │
│ Paving - Asphalt                ┆ 1      │
│ 1 STY Duplex - After 1930 - Cu… ┆ 1      │
│ Dairy                           ┆ 1      │
│ 1 STY Row House - After 1990 -… ┆ 1      │
│ 1 STY Row House - After 1960 -… ┆ 1      │
│ Non-Manualized Structures - Co… ┆ 1      │
│ Garage, Storage                 ┆ 1      │
│ Implmnt Shed & Farm Shltr - Av… ┆ 1      │
│ 1 STY Row House - Before 1930 … ┆ 1      │
│ Church                          ┆ 1      │
└─────────────────────────────────┴────────┘

#### *Pattern Observed*
#### [Storeys] [Building Type] - [Architectural Age] - [Build Quality]

#### *Parsing Considerations*
##### 1. Split on the last dash in each string, and work backwards
##### 2. The quality descriptor is always the last segment after a dash
##### 3. Arch Age is *usually* the second to last segment, THOUGH:
##### 4. Some entries are simpler (eg. Strata Townhouse, has no age/quality)
##### 5. Therefore I will extract components based on numbers of parts (based on number of dashes)

MANUAL_CLASS_DESCRIPTION split into:
1. MC_storeys - numerical storey values
2. MC_subtype - building subtype (SFD, Duplex, Strata Townhouse, etc.)
3. MC_age - architectural age (After 1990, Before 1930, etc.)
4. MC_quality - construction quality level (Semi-Custom, Standard, Custom, Basic, etc.)

In [39]:
def parse_manual_class(df):
    """Parse MANUAL_CLASS_DESCRIPTION into components"""
    
    # CRITICAL: Replace "Semi-Custom" with a placeholder BEFORE normalizing dashes
    df = df.with_columns([
        pl.col('MANUAL_CLASS_DESCRIPTION')
          .str.replace_all('Semi-Custom', 'SEMICUSTOM_PLACEHOLDER')  # Protect it
          .str.replace_all(r'\s*-\s*', ' - ')  # Now normalize dashes
          .str.replace_all('SEMICUSTOM_PLACEHOLDER', 'Semi-Custom')  # Restore it
          .alias('_normalized')
    ])
    
    # Extract storeys
    df = df.with_columns([
        pl.col('_normalized')
          .str.extract(r'(\d+\.?\d*)\s*STY', 1)
          .cast(pl.Float64)
          .alias('MC_storeys'),
    ])
    
    # Split into parts
    df = df.with_columns([
        pl.col('_normalized').str.split(' - ').alias('_parts'),
    ])
    
    df = df.with_columns([
        pl.col('_parts').list.len().alias('_n_parts'),
    ])
    
    # Age patterns
    age_patterns = ['Before 1930', 'After 1930', 'After 1960', 'After 1990', 'All Ages', 
                    'Bef 1930', 'Aft 1930', 'Aft 1960', 'Aft 1990']
    age_regex = '|'.join(age_patterns)
    
    # Quality patterns
    quality_patterns = [
        'Semi-Custom', 'Basic', 'Standard', 'Custom',
        'Ave Q', 'Fair Q', 'Good Q', 'Low Q', 'Very Good Q', 'Excellent Q',
        'Lower Qlty', 'Ave Qlty', 'Better Qlty',
        'Average Quality', 'Low Quality', 'Above Average Quality',
        'Minimum', 'Light Duty', 'Light Construction', 'Alternate Light Constr'
    ]
    quality_regex = '|'.join(quality_patterns)
    
    df = df.with_columns([
        # Extract age
        pl.col('_parts')
          .list.eval(pl.element().str.extract(f'^({age_regex})$', 1))
          .list.drop_nulls()
          .list.first()
          .alias('MC_age'),
        
        # Extract quality
        pl.col('_parts')
          .list.eval(pl.element().str.extract(f'^({quality_regex})$', 1))
          .list.drop_nulls()
          .list.first()
          .alias('MC_quality')
    ])
    
    # Build subtype - remove quality with OR without preceding dash
    df = df.with_columns([
        pl.col('_normalized')
          .str.replace_all(r'\d+\.?\d*\s*STY\s*', '')
          .str.replace(f' - ({age_regex})', '')
          .str.replace(f' - ({quality_regex})', '')  # With dash
          .str.replace(f' ({quality_regex})$', '')   # Without dash at end
          .str.strip_chars()
          .str.strip_chars(' -')
          .str.strip_chars()
          .alias('MC_subtype')
    ])
    
    df = df.drop(['_normalized', '_parts', '_n_parts'])
    
    return df

In [40]:
df = parse_manual_class(df)

In [41]:
# Check the new columns, with unique value counts
print("Storeys distribution:")
print(df.group_by('MC_storeys').agg(pl.len().alias('count')).sort('count', descending=True))

print("\nSubtype distribution:")
print(df.group_by('MC_subtype').agg(pl.len().alias('count')).sort('count', descending=True))

print("\nAge distribution:")
print(df.group_by('MC_age').agg(pl.len().alias('count')).sort('count', descending=True))

print("\nQuality distribution:")
print(df.group_by('MC_quality').agg(pl.len().alias('count')).sort('count', descending=True))

Storeys distribution:
shape: (5, 2)
┌────────────┬────────┐
│ MC_storeys ┆ count  │
│ ---        ┆ ---    │
│ f64        ┆ u32    │
╞════════════╪════════╡
│ 1.0        ┆ 257704 │
│ 2.0        ┆ 256228 │
│ null       ┆ 157682 │
│ 1.5        ┆ 28038  │
│ 3.0        ┆ 3533   │
└────────────┴────────┘

Subtype distribution:
shape: (61, 2)
┌─────────────────────────────────┬────────┐
│ MC_subtype                      ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ SFD                             ┆ 527141 │
│ null                            ┆ 112984 │
│ Strata Townhouse                ┆ 30159  │
│ Duplex                          ┆ 17129  │
│ Strata Apartment - Frame        ┆ 4301   │
│ Non - Manualized Structures     ┆ 3697   │
│ MH - Single Wide                ┆ 2966   │
│ Strata Apartment - Hi - Rise    ┆ 2009   │
│ MH - Double Wide                ┆ 945    │
│ Row House                       ┆ 938    │
│ Recr Home                       ┆ 279    │
│ Strata Apartment - Concrete     ┆ 101    │
│ Gen Purpose Shed & Outbldg      ┆ 74     │
│ Barn, General Purpose           ┆ 47     │
│ Warehouse, Storage              ┆ 46     │
│ Gen Purpose Shed & Outbldglty   ┆ 40     │
│ Non - Manualized Structures - … ┆ 37     │
│ Stable                          ┆ 31     │
│ Domestic Garage                 ┆ 26     │
│ Float                           ┆ 21     │
│ Farm Implement Building         ┆ 19     │
│ Artist Studio                   ┆ 13     │
│ Domestic Garageuality           ┆ 12     │
│ Relocatable Office              ┆ 12     │
│ Farm Implement Arch - Rib, Quo… ┆ 12     │
│ Implmnt Shed & Farm Shltr       ┆ 10     │
│ Laneway SFD                     ┆ 10     │
│ Equipment (Shop) Building       ┆ 10     │
│ Retail Store                    ┆ 9      │
│ Greenhouse, Straight Wall, lar… ┆ 8      │
│ Industrial Light Manufacturing  ┆ 8      │
│ Farm Utility Shelter            ┆ 7      │
│ Horse Arena                     ┆ 7      │
│ Campground                      ┆ 6      │
│ Multiple Residence              ┆ 6      │
│ Day Care Centre                 ┆ 6      │
│ Farm Utility Arch - Rib, Quons… ┆ 5      │
│ Equipment Shed                  ┆ 4      │
│ Strata Apartment - Brick/Block  ┆ 4      │
│ Dormitory                       ┆ 4      │
│ Domestic Carport                ┆ 4      │
│ Apartment Over Commercial       ┆ 3      │
│ Farm Implement Shed             ┆ 3      │
│ Tool Shed                       ┆ 3      │
│ Wharf                           ┆ 3      │
│ Greenhouse, Mod. Hoop, small    ┆ 3      │
│ Service Station                 ┆ 2      │
│ Material Storage                ┆ 2      │
│ Farm Utility Building           ┆ 2      │
│ Material Shelter                ┆ 2      │
│ Apartment - Frame               ┆ 2      │
│ Miscellaneous                   ┆ 2      │
│ Greenhouse, Straight Wall, med… ┆ 2      │
│ Apartment (High Rise)           ┆ 2      │
│ Non - Manualized Structures - … ┆ 1      │
│ Garage, Storage                 ┆ 1      │
│ Implmnt Shed & Farm Shltrlty    ┆ 1      │
│ Church                          ┆ 1      │
│ Paving - Asphalt                ┆ 1      │
│ Domestic Carportuality          ┆ 1      │
│ Dairy                           ┆ 1      │
└─────────────────────────────────┴────────┘

Age distribution:
shape: (7, 2)
┌─────────────┬────────┐
│ MC_age      ┆ count  │
│ ---         ┆ ---    │
│ str         ┆ u32    │
╞═════════════╪════════╡
│ null        ┆ 243208 │
│ After 1930  ┆ 154110 │
│ After 1960  ┆ 136456 │
│ After 1990  ┆ 135608 │
│ Before 1930 ┆ 32525  │
│ All Ages    ┆ 1268   │
│ Aft 1990    ┆ 10     │
└─────────────┴────────┘

Quality distribution:
shape: (21, 2)
┌────────────────────────┬────────┐
│ MC_quality             ┆ count  │
│ ---                    ┆ ---    │
│ str                    ┆ u32    │
╞════════════════════════╪════════╡
│ Standard               ┆ 290868 │
│ null                   ┆ 239103 │
│ Semi-Custom            ┆ 75144  │
│ Custom                 ┆ 60876  │
│ Basic                  ┆ 33089  │
│ Ave Q                  ┆ 2353   │
│ Fair Q                 ┆ 1064   │
│ Good Q                 ┆ 304    │
│ Low Q                  ┆ 140    │
│ Lower Qlty             ┆ 45     │
│ Ave Qlty               ┆ 41     │
│ Very Good Q            ┆ 40     │
│ Better Qlty            ┆ 39     │
│ Average Quality        ┆ 25     │
│ Light Duty             ┆ 14     │
│ Low Quality            ┆ 13     │
│ Excellent Q            ┆ 10     │
│ Alternate Light Constr ┆ 7      │
│ Above Average Quality  ┆ 5      │
│ Light Construction     ┆ 3      │
│ Minimum                ┆ 2      │
└────────────────────────┴────────┘

MC_subtype > MC_subtype_to_specific

In [42]:
# Map MC_subtype -> specific HAZUS occupancy classes
mc_subtype_to_specific = {
    # RES1 - Single Family Dwelling
    'SFD': 'RES1',
    'Laneway SFD': 'RES1',
    'Recr Home': 'RES1',
    
    # RES2 - Mobile/Manufactured Home
    'MH - Single Wide': 'RES2',
    'MH - Double Wide': 'RES2',
    
    # RES3 - Multi-Family / Townhouse / Row / Duplex
    'Strata Townhouse': 'RES3',
    'Duplex': 'RES3',
    'Row House': 'RES3',
    'Strata Apartment - Frame': 'RES3',
    'Strata Apartment - Concrete': 'RES3',
    'Strata Apartment - Brick/Block': 'RES3',
    'Strata Apartment - Hi - Rise': 'RES3',
    'Multiple Residence': 'RES3',
    'Apartment - Frame': 'RES3',
    'Apartment (High Rise)': 'RES3',
    'Apartment Over Commercial': 'RES3',
    
    # RES4 - Temporary Lodging (Dormitory, some commercial residential)
    'Dormitory': 'RES4',
    
    # COM2 - Retail Trade (small stores)
    'Retail Store': 'COM2',
    
    # COM3 - Personal/Repair Services
    'Service Station': 'COM3',
    
    # COM4 - Professional/Technical Services
    'Artist Studio': 'COM4',
    'Relocatable Office': 'COM4',
    
    # COM8 - Entertainment & Recreation
    'Campground': 'COM8',
    
    # EDU1 - Schools/Libraries (Day Care)
    'Day Care Centre': 'EDU1',
    
    # REL1 - Church/Religious
    'Church': 'REL1',
    
    # IND2 - Light Industrial
    'Industrial Light Manufacturing': 'IND2',
    
    # IND5 - Warehouse/Storage
    'Warehouse, Storage': 'IND5',
    'Equipment (Shop) Building': 'IND5',
    'Material Storage': 'IND5',
    'Garage, Storage': 'IND5',
    
    # AGR1 - Agriculture
    'Barn, General Purpose': 'AGR1',
    'Stable': 'AGR1',
    'Farm Implement Building': 'AGR1',
    'Farm Implement Arch - Rib, Quonset': 'AGR1',
    'Implmnt Shed & Farm Shltr': 'AGR1',
    'Farm Utility Shelter': 'AGR1',
    'Horse Arena': 'AGR1',
    'Farm Utility Arch - Rib, Quonset': 'AGR1',
    'Farm Implement Shed': 'AGR1',
    'Greenhouse, Straight Wall, large': 'AGR1',
    'Greenhouse, Mod. Hoop, small': 'AGR1',
    'Greenhouse, Straight Wall, medium': 'AGR1',
    'Farm Utility Building': 'AGR1',
    'Implmnt Shed & Farm Shltrlty': 'AGR1',
    'Dairy': 'AGR1',
    
    # Outbuildings / Accessory structures -> NULL (not main buildings)
    'Gen Purpose Shed & Outbldg': None,
    'Gen Purpose Shed & Outbldglty': None,
    'Domestic Garage': None,
    'Domestic Garageuality': None,
    'Domestic Carport': None,
    'Domestic Carportuality': None,
    'Equipment Shed': None,
    'Tool Shed': None,
    'Material Shelter': None,
    
    # Infrastructure / Non-building -> NULL
    'Float': None,
    'Wharf': None,
    'Paving - Asphalt': None,
    
    # Non-standard / unclassifiable -> NULL
    'Non - Manualized Structures': None,
    'Non - Manualized Structures - Quality': None,
    'Non - Manualized Structures - Quality 2': None,
    'Miscellaneous': None,
}

# Add the new column to the main dataframe
df = df.with_columns(
    pl.col('MC_subtype')
      .cast(pl.Utf8)
      .str.strip_chars()
      .alias('_mc_norm')
).with_columns(
    # Handle truncated strings by matching on prefixes
    pl.when(pl.col('_mc_norm').str.starts_with('Farm Implement Arch - Rib, Quo'))
      .then(pl.lit('Farm Implement Arch - Rib, Quonset'))
    .when(pl.col('_mc_norm').str.starts_with('Farm Utility Arch - Rib, Quons'))
      .then(pl.lit('Farm Utility Arch - Rib, Quonset'))
    .when(pl.col('_mc_norm').str.starts_with('Greenhouse, Straight Wall, lar'))
      .then(pl.lit('Greenhouse, Straight Wall, large'))
    .when(pl.col('_mc_norm').str.starts_with('Greenhouse, Straight Wall, med'))
      .then(pl.lit('Greenhouse, Straight Wall, medium'))
    .when(pl.col('_mc_norm').str.starts_with('Non - Manualized Structures - …'))
      .then(pl.lit('Non - Manualized Structures - Quality'))
    .otherwise(pl.col('_mc_norm'))
    .alias('_mc_norm2')
).with_columns(
    pl.col('_mc_norm2')
      .replace_strict(mc_subtype_to_specific, default=None)
      .alias('MC_subtype_to_specific')
).drop(['_mc_norm', '_mc_norm2'])

# Verify the new column was created
print("New column created: MC_subtype_to_specific")
print("="*80)
print(f"Total rows in dataframe: {df.height:,}")
print(f"\nColumn exists: {'MC_subtype_to_specific' in df.columns}")

# Show sample of the new column
print("\n" + "="*80)
print("Sample of MC_subtype -> MC_subtype_to_specific mapping:")
print("="*80)
sample = (df
    .select(['MC_subtype', 'MC_subtype_to_specific'])
    .unique()
    .sort('MC_subtype')
    .head(20))
print(sample)

# Create summary statistics
print("\n" + "="*80)
print("MC_subtype_to_specific Distribution:")
print("="*80)
mc_summary = (
    df.group_by('MC_subtype_to_specific')
      .agg(pl.len().alias('count'))
      .sort('count', descending=True)
)
print(mc_summary)

# Overall coverage statistics
total = df.height
mapped = df.filter(pl.col('MC_subtype_to_specific').is_not_null()).height
unmapped = total - mapped

print("\n" + "="*80)
print("COVERAGE SUMMARY:")
print("="*80)
print(f"Total rows:                    {total:>10,}")
print(f"Mapped to HAZUS occupancy:     {mapped:>10,} ({mapped/total*100:>5.1f}%)")
print(f"Unmapped (NULL):               {unmapped:>10,} ({unmapped/total*100:>5.1f}%)")

# Show which MC_subtypes are unmapped
print("\n" + "="*80)
print("Unmapped MC_subtype values (accessory structures):")
print("="*80)
unmapped_types = (
    df.filter(pl.col('MC_subtype_to_specific').is_null())
      .group_by('MC_subtype')
      .agg(pl.len().alias('count'))
      .sort('count', descending=True)
)
print(unmapped_types)

'''

This code will:

1. **Create the new column** `MC_subtype_to_specific` in your dataframe
2. **Handle truncated strings** that appear in your data (the "..." truncations)
3. **Map MC_subtype values** to HAZUS occupancy classes
4. **Show verification output**:
   - Confirmation the column was created
   - Sample mappings
   - Distribution of HAZUS occupancy classes
   - Coverage statistics
   - List of unmapped values (accessory structures)

The column will contain HAZUS occupancy codes like `RES1`, `RES2`, `RES3`, etc., or `NULL` for accessory structures and non-buildings.

'''

New column created: MC_subtype_to_specific
================================================================================
Total rows in dataframe: 703,185

Column exists: True

================================================================================
Sample of MC_subtype -> MC_subtype_to_specific mapping:
================================================================================
shape: (20, 2)
┌─────────────────────────────────┬────────────────────────┐
│ MC_subtype                      ┆ MC_subtype_to_specific │
│ ---                             ┆ ---                    │
│ str                             ┆ str                    │
╞═════════════════════════════════╪════════════════════════╡
│ null                            ┆ null                   │
│ Apartment (High Rise)           ┆ RES3                   │
│ Apartment - Frame               ┆ RES3                   │
│ Apartment Over Commercial       ┆ RES3                   │
│ Artist Studio                   ┆ COM4                   │
│ Barn, General Purpose           ┆ AGR1                   │
│ Campground                      ┆ COM8                   │
│ Church                          ┆ REL1                   │
│ Dairy                           ┆ AGR1                   │
│ Day Care Centre                 ┆ EDU1                   │
│ Domestic Carport                ┆ null                   │
│ Domestic Carportuality          ┆ null                   │
│ Domestic Garage                 ┆ null                   │
│ Domestic Garageuality           ┆ null                   │
│ Dormitory                       ┆ RES4                   │
│ Duplex                          ┆ RES3                   │
│ Equipment (Shop) Building       ┆ IND5                   │
│ Equipment Shed                  ┆ null                   │
│ Farm Implement Arch - Rib, Quo… ┆ AGR1                   │
│ Farm Implement Building         ┆ AGR1                   │
└─────────────────────────────────┴────────────────────────┘

================================================================================
MC_subtype_to_specific Distribution:
================================================================================
shape: (14, 2)
┌────────────────────────┬────────┐
│ MC_subtype_to_specific ┆ count  │
│ ---                    ┆ ---    │
│ str                    ┆ u32    │
╞════════════════════════╪════════╡
│ RES1                   ┆ 527430 │
│ null                   ┆ 116912 │
│ RES3                   ┆ 54654  │
│ RES2                   ┆ 3911   │
│ AGR1                   ┆ 158    │
│ IND5                   ┆ 59     │
│ COM4                   ┆ 25     │
│ COM2                   ┆ 9      │
│ IND2                   ┆ 8      │
│ EDU1                   ┆ 6      │
│ COM8                   ┆ 6      │
│ RES4                   ┆ 4      │
│ COM3                   ┆ 2      │
│ REL1                   ┆ 1      │
└────────────────────────┴────────┘

================================================================================
COVERAGE SUMMARY:
================================================================================
Total rows:                       703,185
Mapped to HAZUS occupancy:        586,273 ( 83.4%)
Unmapped (NULL):                  116,912 ( 16.6%)

================================================================================
Unmapped MC_subtype values (accessory structures):
================================================================================
shape: (17, 2)
┌─────────────────────────────────┬────────┐
│ MC_subtype                      ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ null                            ┆ 112984 │
│ Non - Manualized Structures     ┆ 3697   │
│ Gen Purpose Shed & Outbldg      ┆ 74     │
│ Gen Purpose Shed & Outbldglty   ┆ 40     │
│ Non - Manualized Structures - … ┆ 37     │
│ Domestic Garage                 ┆ 26     │
│ Float                           ┆ 21     │
│ Domestic Garageuality           ┆ 12     │
│ Equipment Shed                  ┆ 4      │
│ Domestic Carport                ┆ 4      │
│ Wharf                           ┆ 3      │
│ Tool Shed                       ┆ 3      │
│ Miscellaneous                   ┆ 2      │
│ Material Shelter                ┆ 2      │
│ Non - Manualized Structures - … ┆ 1      │
│ Domestic Carportuality          ┆ 1      │
│ Paving - Asphalt                ┆ 1      │
└─────────────────────────────────┴────────┘

'\n\nThis code will:\n\n1. **Create the new column** `MC_subtype_to_specific` in your dataframe\n2. **Handle truncated strings** that appear in your data (the "..." truncations)\n3. **Map MC_subtype values** to HAZUS occupancy classes\n4. **Show verification output**:\n   - Confirmation the column was created\n   - Sample mappings\n   - Distribution of HAZUS occupancy classes\n   - Coverage statistics\n   - List of unmapped values (accessory structures)\n\nThe column will contain HAZUS occupancy codes like `RES1`, `RES2`, `RES3`, etc., or `NULL` for accessory structures and non-buildings.\n\n'

In [43]:
df.describe()

shape: (9, 57)
┌────────────┬──────────┬────────────────┬──────────┬───┬─────────────┬────────────────┬───────────────┬───────────────┐
│ statistic  ┆ Height_M ┆ name           ┆ type     ┆ … ┆ MC_age      ┆ MC_quality     ┆ MC_subtype    ┆ MC_subtype_to │
│ ---        ┆ ---      ┆ ---            ┆ ---      ┆   ┆ ---         ┆ ---            ┆ ---           ┆ _specific     │
│ str        ┆ f64      ┆ str            ┆ str      ┆   ┆ str         ┆ str            ┆ str           ┆ ---           │
│            ┆          ┆                ┆          ┆   ┆             ┆                ┆               ┆ str           │
╞════════════╪══════════╪════════════════╪══════════╪═══╪═════════════╪════════════════╪═══════════════╪═══════════════╡
│ count      ┆ 178287.0 ┆ 329381         ┆ 329381   ┆ … ┆ 459977      ┆ 464082         ┆ 590201        ┆ 586273        │
│ null_count ┆ 524898.0 ┆ 373804         ┆ 373804   ┆ … ┆ 243208      ┆ 239103         ┆ 112984        ┆ 116912        │
│ mean       ┆ 7.130547 ┆ null           ┆ null     ┆ … ┆ null        ┆ null           ┆ null          ┆ null          │
│ std        ┆ 3.64762  ┆ null           ┆ null     ┆ … ┆ null        ┆ null           ┆ null          ┆ null          │
│ min        ┆ -0.13    ┆                ┆          ┆ … ┆ Aft 1990    ┆ Above Average  ┆ Apartment     ┆ AGR1          │
│            ┆          ┆                ┆          ┆   ┆             ┆ Quality        ┆ (High Rise)   ┆               │
│ 25%        ┆ 5.051146 ┆ null           ┆ null     ┆ … ┆ null        ┆ null           ┆ null          ┆ null          │
│ 50%        ┆ 7.27     ┆ null           ┆ null     ┆ … ┆ null        ┆ null           ┆ null          ┆ null          │
│ 75%        ┆ 9.16     ┆ null           ┆ null     ┆ … ┆ null        ┆ null           ┆ null          ┆ null          │
│ max        ┆ 164.46   ┆ 大統華 T&T     ┆ yes;roof ┆ … ┆ Before 1930 ┆ Very Good Q    ┆ Wharf         ┆ RES4          │
│            ┆          ┆ Supermarket    ┆          ┆   ┆             ┆                ┆               ┆               │
└────────────┴──────────┴────────────────┴──────────┴───┴─────────────┴────────────────┴───────────────┴───────────────┘

In [44]:
#CHECKPOINT - FINISHED ALL THE OCCUPANCY CLASS CLEANING

df.write_parquet('occupancyclass_cleaned.parquet')

---
### Cleaning Construction-related fields
---
- STRUCTURAL rename > Construction_Typology_Code

- STRUCTUR00 rename > Construction_Typology_Description

- CONSTRUCTION_CODE - according to the investigation below, DROP

- FOUNDATION_TYPE - Keep in lieu of CONSTRUCTION_CODE

In [45]:
df = pl.read_parquet('occupancyclass_cleaned.parquet')

STRUCTURAL > Construction_Typology_Code

In [46]:
df.head()

shape: (5, 56)
┌──────────┬──────┬──────────┬────────────┬───┬────────────┬─────────────┬────────────┬────────────────────────┐
│ Height_M ┆ name ┆ type     ┆ Height_Flr ┆ … ┆ MC_age     ┆ MC_quality  ┆ MC_subtype ┆ MC_subtype_to_specific │
│ ---      ┆ ---  ┆ ---      ┆ ---        ┆   ┆ ---        ┆ ---         ┆ ---        ┆ ---                    │
│ f64      ┆ str  ┆ str      ┆ f64        ┆   ┆ str        ┆ str         ┆ str        ┆ str                    │
╞══════════╪══════╪══════════╪════════════╪═══╪════════════╪═════════════╪════════════╪════════════════════════╡
│ 5.55     ┆      ┆ detached ┆ null       ┆ … ┆ After 1930 ┆ Standard    ┆ SFD        ┆ RES1                   │
│ 10.31    ┆      ┆ detached ┆ null       ┆ … ┆ null       ┆ null        ┆ SFD        ┆ RES1                   │
│ 5.79     ┆      ┆ detached ┆ null       ┆ … ┆ After 1930 ┆ Standard    ┆ SFD        ┆ RES1                   │
│ 10.11    ┆      ┆ detached ┆ null       ┆ … ┆ After 1990 ┆ Semi-Custom ┆ SFD        ┆ RES1                   │
│ 9.03     ┆      ┆ detached ┆ null       ┆ … ┆ After 1990 ┆ Standard    ┆ SFD        ┆ RES1                   │
└──────────┴──────┴──────────┴────────────┴───┴────────────┴─────────────┴────────────┴────────────────────────┘

In [47]:
df = df.with_columns(
    pl.col('STRUCTURAL')).rename({'STRUCTURAL': 'Construction_Typology_Code'})

STRUCTUR00 > Construction_Typology_Description

In [48]:
df = df.with_columns(
    pl.col('STRUCTUR00')).rename({'STRUCTUR00': 'Construction_Typology_Description'})

CONSTRUCTION_CODE vs FOUNDATION_TYPE?

In [49]:
# Cross-tab CONSTRUCTION_CODE vs FOUNDATION_TYPE
ct = (
    df.group_by(['CONSTRUCTION_CODE', 'FOUNDATION_TYPE'])
      .agg(pl.len().alias('n'))
      .sort(['CONSTRUCTION_CODE', 'n'], descending=[False, True])
)
print(ct)

# For each construction code, what foundation types dominate?
dominant = (
    ct.with_columns(pl.col('n').sum().over('CONSTRUCTION_CODE').alias('total'))
      .with_columns((pl.col('n') / pl.col('total')).alias('share'))
      .sort(['CONSTRUCTION_CODE', 'share'], descending=[False, True])
)
print(dominant)

shape: (20, 3)
┌───────────────────┬──────────────────┬────────┐
│ CONSTRUCTION_CODE ┆ FOUNDATION_TYPE  ┆ n      │
│ ---               ┆ ---              ┆ ---    │
│ str               ┆ str              ┆ u32    │
╞═══════════════════╪══════════════════╪════════╡
│ null              ┆ Basement         ┆ 333569 │
│ null              ┆ null             ┆ 116748 │
│ null              ┆ Partial Basement ┆ 97573  │
│ null              ┆ Crawl            ┆ 72735  │
│ null              ┆ Slab             ┆ 44812  │
│ B                 ┆ null             ┆ 2312   │
│ B                 ┆ Partial Basement ┆ 5      │
│ C                 ┆ null             ┆ 41     │
│ C                 ┆ Crawl            ┆ 5      │
│ C                 ┆ Slab             ┆ 1      │
│ C                 ┆ Basement         ┆ 1      │
│ D                 ┆ null             ┆ 33118  │
│ D                 ┆ Crawl            ┆ 1643   │
│ D                 ┆ Basement         ┆ 524    │
│ D                 ┆ Slab             ┆ 23     │
│ D                 ┆ Partial Basement ┆ 7      │
│ P                 ┆ null             ┆ 1      │
│ S                 ┆ null             ┆ 47     │
│ S                 ┆ Basement         ┆ 13     │
│ S                 ┆ Crawl            ┆ 7      │
└───────────────────┴──────────────────┴────────┘
shape: (20, 5)
┌───────────────────┬──────────────────┬────────┬────────┬──────────┐
│ CONSTRUCTION_CODE ┆ FOUNDATION_TYPE  ┆ n      ┆ total  ┆ share    │
│ ---               ┆ ---              ┆ ---    ┆ ---    ┆ ---      │
│ str               ┆ str              ┆ u32    ┆ u32    ┆ f64      │
╞═══════════════════╪══════════════════╪════════╪════════╪══════════╡
│ null              ┆ Basement         ┆ 333569 ┆ 665437 ┆ 0.501278 │
│ null              ┆ null             ┆ 116748 ┆ 665437 ┆ 0.175446 │
│ null              ┆ Partial Basement ┆ 97573  ┆ 665437 ┆ 0.14663  │
│ null              ┆ Crawl            ┆ 72735  ┆ 665437 ┆ 0.109304 │
│ null              ┆ Slab             ┆ 44812  ┆ 665437 ┆ 0.067342 │
│ B                 ┆ null             ┆ 2312   ┆ 2317   ┆ 0.997842 │
│ B                 ┆ Partial Basement ┆ 5      ┆ 2317   ┆ 0.002158 │
│ C                 ┆ null             ┆ 41     ┆ 48     ┆ 0.854167 │
│ C                 ┆ Crawl            ┆ 5      ┆ 48     ┆ 0.104167 │
│ C                 ┆ Slab             ┆ 1      ┆ 48     ┆ 0.020833 │
│ C                 ┆ Basement         ┆ 1      ┆ 48     ┆ 0.020833 │
│ D                 ┆ null             ┆ 33118  ┆ 35315  ┆ 0.937788 │
│ D                 ┆ Crawl            ┆ 1643   ┆ 35315  ┆ 0.046524 │
│ D                 ┆ Basement         ┆ 524    ┆ 35315  ┆ 0.014838 │
│ D                 ┆ Slab             ┆ 23     ┆ 35315  ┆ 0.000651 │
│ D                 ┆ Partial Basement ┆ 7      ┆ 35315  ┆ 0.000198 │
│ P                 ┆ null             ┆ 1      ┆ 1      ┆ 1.0      │
│ S                 ┆ null             ┆ 47     ┆ 67     ┆ 0.701493 │
│ S                 ┆ Basement         ┆ 13     ┆ 67     ┆ 0.19403  │
│ S                 ┆ Crawl            ┆ 7      ┆ 67     ┆ 0.104478 │
└───────────────────┴──────────────────┴────────┴────────┴──────────┘

therefore, CONSTRUCTION_CODE can be dropped

In [50]:
df = df.drop('CONSTRUCTION_CODE')

In [51]:
#CHECKPOINT - FINISHED ALL THE CONSTRUCTION_TYPOLOGY CLEANING

df.write_parquet('occupancy_and_construction_cleaned.parquet')

---
### Cleaning Seismic Code and Design Quality fields
---

- year_built: 
1. first combine CONSTRUCTION_YEAR + Year_Built + YEAR_BUILT
2. impute any nulls with MC_age
3. categorize age into:
   | DesignLevelID | EqDesignLevelId | DesignLevelDesc | Description |
|:-------------:|:---------------:|:----------------|:------------|
| 1 | PC | Pre-Code | **Pre-Code (Pre-1975):** Buildings constructed before 1975 generally had minimal or no specific seismic design requirements compared to modern standards. These buildings are considered to have the highest seismic risk today and may require retrofitting to improve performance. |
| 2 | LC | Low Code | **Low Code (1975–1990):** Seismic requirements began to be included in the building codes in the 1950s, but the 1975-1990 period saw relatively modest requirements. These standards are still considered "low code" by modern assessments. |
| 3 | MC | Moderate Code | **Moderate Code (1990–2005):** The 1990s and early 2000s saw progressively improved and strengthened provisions in the National Building Code of Canada (NBC), which Vancouver adopted into its own building bylaws. |
| 4 | HC | High Code | **High Code (Post-2005):** Modern seismic design in Vancouver follows the rigorous standards of the current BC Building Code and Vancouver Building By-law, which are based on the latest editions of the NBC (e.g., NBC 2020). |

- MC_quality -> build_quality
categorize into: 
| Construction Quality | High-Code | Moderate-Code | Low-Code | None |
|---------------------|-----------|---------------|----------|---------|
| Superior | Special$^1$ | High-Code | Moderate-Code | Low-Code |
| Ordinary | High-Code | Moderate-Code | Low-Code | Pre-Code |
| Inferior | Moderate-Code | Low-Code | Pre-Code | Pre-Code |

$^1$ Special designation for superior construction quality with high-code seismic design level.

In [52]:
# overlap summary table to analyze and combine accordingly
from typing import Optional

def create_overlap_summary_table(
    df: pl.DataFrame,
    col1: str,
    col2: str,
    col3: Optional[str] = None,
    col4: Optional[str] = None,
    col5: Optional[str] = None,
):
    """
    Create a visual summary table of row overlap for up to 5 fields.
    """
    cols = [col1, col2, col3, col4, col5]
    cols = [c for c in cols if c is not None]

    group_exprs = [
        pl.col(c).is_not_null().alias(f"Has_{c}")
        for c in cols
    ]

    return (
        df.group_by(group_exprs)
          .len()
          .sort("len", descending=True)
    )

In [53]:
df = pl.read_parquet('occupancy_and_construction_cleaned.parquet')

---
year_built = CONSTRUCTION_YEAR + Year_Built + YEAR_BUILT

---

In [54]:
df.select(['CONSTRUCTION_YEAR', 'YearBuilt', 'YEAR_BUILT']).schema

Schema([('CONSTRUCTION_YEAR', String),
        ('YearBuilt', Float64),
        ('YEAR_BUILT', Float64)])

In [55]:
# 1. convert schema to integers (no decimals needed)

df = df.with_columns([
    pl.col('CONSTRUCTION_YEAR').cast(pl.Int32, strict=False),
    pl.col('YearBuilt').cast(pl.Int32, strict=False),
    pl.col('YEAR_BUILT').cast(pl.Int32, strict=False)
])

In [56]:
# Visual summary table, (check in "COMBINING" section to see this function)
create_overlap_summary_table(df, 'CONSTRUCTION_YEAR', 'YearBuilt', 'YEAR_BUILT')

shape: (8, 4)
┌───────────────────────┬───────────────┬────────────────┬────────┐
│ Has_CONSTRUCTION_YEAR ┆ Has_YearBuilt ┆ Has_YEAR_BUILT ┆ len    │
│ ---                   ┆ ---           ┆ ---            ┆ ---    │
│ bool                  ┆ bool          ┆ bool           ┆ u32    │
╞═══════════════════════╪═══════════════╪════════════════╪════════╡
│ false                 ┆ false         ┆ true           ┆ 462869 │
│ true                  ┆ false         ┆ true           ┆ 155677 │
│ false                 ┆ false         ┆ false          ┆ 70694  │
│ true                  ┆ false         ┆ false          ┆ 12785  │
│ false                 ┆ true          ┆ false          ┆ 884    │
│ true                  ┆ true          ┆ false          ┆ 170    │
│ false                 ┆ true          ┆ true           ┆ 97     │
│ true                  ┆ true          ┆ true           ┆ 9      │
└───────────────────────┴───────────────┴────────────────┴────────┘

In [57]:
#change the 0's to null values in CONSTRUCTION_YEAR
df = df.with_columns([
    pl.when(pl.col('CONSTRUCTION_YEAR') == 0)
      .then(None)
      .otherwise(pl.col('CONSTRUCTION_YEAR'))
      .alias('CONSTRUCTION_YEAR')
])

In [58]:
# 2. Create merged column using MINIMUM (oldest) year
df = df.with_columns([
    # Take the minimum (oldest) non-null year across all three columns
    pl.min_horizontal(['CONSTRUCTION_YEAR', 'YearBuilt', 'YEAR_BUILT'])
      .alias('year_built'),
])

In [59]:
df.select('year_built').head(20)

shape: (20, 1)
┌────────────┐
│ year_built │
│ ---        │
│ i32        │
╞════════════╡
│ 1958       │
│ 2011       │
│ 1958       │
│ 2008       │
│ 1968       │
│ 2016       │
│ 2016       │
│ 2016       │
│ 2016       │
│ 1966       │
│ null       │
│ 2015       │
│ null       │
│ 2016       │
│ 2016       │
│ 2016       │
│ 2012       │
│ 2012       │
│ 2013       │
│ 2013       │
└────────────┘

In [60]:
#drop old columns
df = df.drop(['CONSTRUCTION_YEAR', 'YearBuilt', 'YEAR_BUILT'])

In [61]:
#now lets see if we need to impute some nulls with MC_age
create_overlap_summary_table(df, 'year_built', "MC_age")

shape: (4, 3)
┌────────────────┬────────────┬────────┐
│ Has_year_built ┆ Has_MC_age ┆ len    │
│ ---            ┆ ---        ┆ ---    │
│ bool           ┆ bool       ┆ u32    │
╞════════════════╪════════════╪════════╡
│ true           ┆ true       ┆ 459777 │
│ true           ┆ false      ┆ 171737 │
│ false          ┆ false      ┆ 71471  │
│ false          ┆ true       ┆ 200    │
└────────────────┴────────────┴────────┘

In [62]:
#turn year_built into string for combination

df = df.with_columns([
    pl.col('year_built').cast(pl.String, strict=False)
])

In [63]:
df = df.with_columns(
    pl.when(pl.col("year_built").is_null() & pl.col("MC_age").is_not_null())
      .then(pl.col("MC_age").str.extract_all(r"\d{4}").list.first().cast(pl.Int64, strict=False))
      .otherwise(pl.col("year_built"))
      .alias("year_built")
)

In [64]:
create_overlap_summary_table(df, 'year_built', "MC_age")

shape: (4, 3)
┌────────────────┬────────────┬────────┐
│ Has_year_built ┆ Has_MC_age ┆ len    │
│ ---            ┆ ---        ┆ ---    │
│ bool           ┆ bool       ┆ u32    │
╞════════════════╪════════════╪════════╡
│ true           ┆ true       ┆ 459975 │
│ true           ┆ false      ┆ 171737 │
│ false          ┆ false      ┆ 71471  │
│ false          ┆ true       ┆ 2      │
└────────────────┴────────────┴────────┘

In [65]:
#turn it back into int64

df = df.with_columns([
    pl.col('year_built').cast(pl.Int64, strict=False)
])

---
MC_quality -> seismic_build_quality
---
need to categorize into: 
- Superior
- Ordinary	
- Inferior

In [66]:
df.group_by("MC_quality").len().sort("len", descending=True)

shape: (21, 2)
┌────────────────────────┬────────┐
│ MC_quality             ┆ len    │
│ ---                    ┆ ---    │
│ str                    ┆ u32    │
╞════════════════════════╪════════╡
│ Standard               ┆ 290868 │
│ null                   ┆ 239103 │
│ Semi-Custom            ┆ 75144  │
│ Custom                 ┆ 60876  │
│ Basic                  ┆ 33089  │
│ Ave Q                  ┆ 2353   │
│ Fair Q                 ┆ 1064   │
│ Good Q                 ┆ 304    │
│ Low Q                  ┆ 140    │
│ Lower Qlty             ┆ 45     │
│ Ave Qlty               ┆ 41     │
│ Very Good Q            ┆ 40     │
│ Better Qlty            ┆ 39     │
│ Average Quality        ┆ 25     │
│ Light Duty             ┆ 14     │
│ Low Quality            ┆ 13     │
│ Excellent Q            ┆ 10     │
│ Alternate Light Constr ┆ 7      │
│ Above Average Quality  ┆ 5      │
│ Light Construction     ┆ 3      │
│ Minimum                ┆ 2      │
└────────────────────────┴────────┘

In [67]:
df = df.with_columns(
    pl.when(
        pl.col("MC_quality").is_in([
            "Excellent Q",
            "Very Good Q",
            "Good Q",
            "Above Average Quality",
            "Better Qlty",
            "Custom",
            "Semi-Custom",
        ])
    ).then(pl.lit("superior"))

    .when(
        pl.col("MC_quality").is_in([
            "Standard",
            "Ave Q",
            "Ave Qlty",
            "Average Quality",
            "Basic",
            "Fair Q",
        ])
    ).then(pl.lit("ordinary"))

    .when(
        pl.col("MC_quality").is_in([
            "Low Q",
            "Low Quality",
            "Lower Qlty",
            "Minimum",
            "Light Duty",
            "Light Construction",
            "Alternate Light Constr",
        ])
    ).then(pl.lit("inferior"))

    .otherwise(pl.lit(None))
    .alias("seismic_build_quality")
)

In [68]:
df.group_by("seismic_build_quality").len().sort("len", descending=True)

shape: (4, 2)
┌───────────────────────┬────────┐
│ seismic_build_quality ┆ len    │
│ ---                   ┆ ---    │
│ str                   ┆ u32    │
╞═══════════════════════╪════════╡
│ ordinary              ┆ 327440 │
│ null                  ┆ 239103 │
│ superior              ┆ 136418 │
│ inferior              ┆ 224    │
└───────────────────────┴────────┘

In [69]:
df.write_parquet('all_clean.parquet')

In [70]:
df.head()

shape: (5, 54)
┌──────────┬──────┬──────────┬────────────┬───┬────────────┬───────────────────────┬────────────┬──────────────────────┐
│ Height_M ┆ name ┆ type     ┆ Height_Flr ┆ … ┆ MC_subtype ┆ MC_subtype_to_specifi ┆ year_built ┆ seismic_build_qualit │
│ ---      ┆ ---  ┆ ---      ┆ ---        ┆   ┆ ---        ┆ c                     ┆ ---        ┆ y                    │
│ f64      ┆ str  ┆ str      ┆ f64        ┆   ┆ str        ┆ ---                   ┆ i64        ┆ ---                  │
│          ┆      ┆          ┆            ┆   ┆            ┆ str                   ┆            ┆ str                  │
╞══════════╪══════╪══════════╪════════════╪═══╪════════════╪═══════════════════════╪════════════╪══════════════════════╡
│ 5.55     ┆      ┆ detached ┆ null       ┆ … ┆ SFD        ┆ RES1                  ┆ 1958       ┆ ordinary             │
│ 10.31    ┆      ┆ detached ┆ null       ┆ … ┆ SFD        ┆ RES1                  ┆ 2011       ┆ null                 │
│ 5.79     ┆      ┆ detached ┆ null       ┆ … ┆ SFD        ┆ RES1                  ┆ 1958       ┆ ordinary             │
│ 10.11    ┆      ┆ detached ┆ null       ┆ … ┆ SFD        ┆ RES1                  ┆ 2008       ┆ superior             │
│ 9.03     ┆      ┆ detached ┆ null       ┆ … ┆ SFD        ┆ RES1                  ┆ 1968       ┆ ordinary             │
└──────────┴──────┴──────────┴────────────┴───┴────────────┴───────────────────────┴────────────┴──────────────────────┘

In [71]:
df = pl.read_parquet('all_clean.parquet')

In [72]:
df.describe()

shape: (9, 55)
┌────────────┬──────────┬────────────────┬──────────┬───┬────────────────┬───────────────┬─────────────┬───────────────┐
│ statistic  ┆ Height_M ┆ name           ┆ type     ┆ … ┆ MC_subtype     ┆ MC_subtype_to ┆ year_built  ┆ seismic_build │
│ ---        ┆ ---      ┆ ---            ┆ ---      ┆   ┆ ---            ┆ _specific     ┆ ---         ┆ _quality      │
│ str        ┆ f64      ┆ str            ┆ str      ┆   ┆ str            ┆ ---           ┆ f64         ┆ ---           │
│            ┆          ┆                ┆          ┆   ┆                ┆ str           ┆             ┆ str           │
╞════════════╪══════════╪════════════════╪══════════╪═══╪════════════════╪═══════════════╪═════════════╪═══════════════╡
│ count      ┆ 178287.0 ┆ 329381         ┆ 329381   ┆ … ┆ 590201         ┆ 586273        ┆ 631712.0    ┆ 464082        │
│ null_count ┆ 524898.0 ┆ 373804         ┆ 373804   ┆ … ┆ 112984         ┆ 116912        ┆ 71473.0     ┆ 239103        │
│ mean       ┆ 7.130547 ┆ null           ┆ null     ┆ … ┆ null           ┆ null          ┆ 1981.447123 ┆ null          │
│ std        ┆ 3.64762  ┆ null           ┆ null     ┆ … ┆ null           ┆ null          ┆ 25.550448   ┆ null          │
│ min        ┆ -0.13    ┆                ┆          ┆ … ┆ Apartment      ┆ AGR1          ┆ 1862.0      ┆ inferior      │
│            ┆          ┆                ┆          ┆   ┆ (High Rise)    ┆               ┆             ┆               │
│ 25%        ┆ 5.051146 ┆ null           ┆ null     ┆ … ┆ null           ┆ null          ┆ 1966.0      ┆ null          │
│ 50%        ┆ 7.27     ┆ null           ┆ null     ┆ … ┆ null           ┆ null          ┆ 1986.0      ┆ null          │
│ 75%        ┆ 9.16     ┆ null           ┆ null     ┆ … ┆ null           ┆ null          ┆ 2002.0      ┆ null          │
│ max        ┆ 164.46   ┆ 大統華 T&T     ┆ yes;roof ┆ … ┆ Wharf          ┆ RES4          ┆ 2025.0      ┆ superior      │
│            ┆          ┆ Supermarket    ┆          ┆   ┆                ┆               ┆             ┆               │
└────────────┴──────────┴────────────────┴──────────┴───┴────────────────┴───────────────┴─────────────┴───────────────┘

In [73]:
#oops, drop all cleaned columns:
df = df.drop(['type', 'NONRESIDENTIAL_SUBTYPE', 'DEVELOPMENT_SUBTYPE', 'BUILDING_U', 'BLDGCLASS_', 'BLDGTYPE', 'BLDGSUBTYP', 'PRIMARYUSE', 'ACTUAL_USE_CODE', 'ACTUAL_USE_DESCRIPTION'])

In [74]:
df.write_parquet('all_clean_ready_to_combine.parquet')

In [75]:
df.head()

shape: (5, 44)
┌──────────┬──────┬────────────┬──────────────────┬───┬────────────┬───────────────────┬────────────┬──────────────────┐
│ Height_M ┆ name ┆ Height_Flr ┆ development_type ┆ … ┆ MC_subtype ┆ MC_subtype_to_spe ┆ year_built ┆ seismic_build_qu │
│ ---      ┆ ---  ┆ ---        ┆ ---              ┆   ┆ ---        ┆ cific             ┆ ---        ┆ ality            │
│ f64      ┆ str  ┆ f64        ┆ str              ┆   ┆ str        ┆ ---               ┆ i64        ┆ ---              │
│          ┆      ┆            ┆                  ┆   ┆            ┆ str               ┆            ┆ str              │
╞══════════╪══════╪════════════╪══════════════════╪═══╪════════════╪═══════════════════╪════════════╪══════════════════╡
│ 5.55     ┆      ┆ null       ┆ null             ┆ … ┆ SFD        ┆ RES1              ┆ 1958       ┆ ordinary         │
│ 10.31    ┆      ┆ null       ┆ null             ┆ … ┆ SFD        ┆ RES1              ┆ 2011       ┆ null             │
│ 5.79     ┆      ┆ null       ┆ null             ┆ … ┆ SFD        ┆ RES1              ┆ 1958       ┆ ordinary         │
│ 10.11    ┆      ┆ null       ┆ null             ┆ … ┆ SFD        ┆ RES1              ┆ 2008       ┆ superior         │
│ 9.03     ┆      ┆ null       ┆ null             ┆ … ┆ SFD        ┆ RES1              ┆ 1968       ┆ ordinary         │
└──────────┴──────┴────────────┴──────────────────┴───┴────────────┴───────────────────┴────────────┴──────────────────┘